apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: shlink
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  characterSet: utf8
  collate: utf8_general_ci
  cleanupPolicy: Skip # keep the database when deleting this resource
  requeueInterval: 30s
  retryInterval: 5s
