apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: shlink
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  passwordSecretKeyRef:
    name: shlink-secrets
    key: DB_PASSWORD
  # This field defaults to 10
  maxUserConnections: 20
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
