apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: vaultwarden
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: vaultwarden
  table: "*"
  username: vaultwarden
  grantOption: true
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
