keys:
  - &users
    - &caleb_pgp 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - &caleb_age age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - &jadonLee8 age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
  - &hosts
    - &cluster_pgp 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B

creation_rules:
  - path_regex: k3s\.enc\.yaml$
    encrypted_regex: ^client-key(-data)?$
    key_groups:
      - pgp:
          - *caleb_pgp
        age:
          - *caleb_age
          - *jadonLee8
  - path_regex: secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - pgp:
          - *caleb_pgp
          - *cluster_pgp
        age:
          - *caleb_age
          - *jadonLee8
stores:
  yaml:
    indent: 2
