apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXpneE56TTFNVFV3SGhjTk1qVXdNVEk1TVRjMU9ETTFXaGNOTXpVd01USTNNVGMxT0RNMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXpneE56TTFNVFV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTL3lSdnU2UGJwYnBoUDZHalpzNzlNWEZxc1pWbmd3Rlk4ZzY5Z1pValoKT2xyZ0swZ1NhUkhjNWVxbWQyVUVNU3FIendpM2JiL0dPc2RKQjFhM3BQcmdvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUMzb2thS2pZLytxbmk5eXJnOGtxCnpiV0NGcTR3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU9mM0htMTZlYXM5ZWN1MkVsRUNpWVRyT0JiSGRoYkEKQUU1eU54OXVGcUloQWlFQXhMelV2ZjAxbThOVEZOY1dicTd0VFRvTnU5QVJjY244dkNsVk9pcDY0NWc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://ieee-tamu.engr.tamu.edu:6443
    name: ieee-tamu
contexts:
  - context:
      cluster: ieee-tamu
      user: ieee-tamu-admin
    name: ieee-tamu
current-context: ieee-tamu
kind: Config
users:
  - name: ieee-tamu-admin
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJV05tNEJRanpVNm93Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOek00TVRjek5URTFNQjRYRFRJMU1ERXlPVEUzTlRnek5Wb1hEVEkyTVRFeQpNREU1TWpNMU9Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJEUVlmb25EVEI1d29JMFoKSEVWL3Zvc0pPREo2Y1lCUUp4TitoNTJXRk9YYWh1WHdXUDdaWjdyNmdVZEJDNk1mWDNUWUJGa1o5QmFpcmtjVgpMbGU1NWthalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUm9Vc04yK0VBclJ2YXZnNFR2MHVrS2hqaW5QakFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQXd5Yy9tYWpvWkQ3OEpxM25GdzRZSThrS1JCM2NSL1luZFpKTURRQWFSYTBDSUZQMkZnNmpYejNoUUZYUAo0eGVYZjlsSlNGV3k5WG5ER0F6ZU5jaUo5UXkvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTXpneE56TTFNVFV3SGhjTk1qVXdNVEk1TVRjMU9ETTFXaGNOTXpVd01USTNNVGMxT0RNMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTXpneE56TTFNVFV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSM2x2UUduM0E0aFVJTnMxYUNuTjByZU03N2orSjV0ZXl1ZVZ3NHJJQVoKYmxOZ3o1eVJmRFV4VEFHOForaEc2SlB4bW9OSlVyelEreGN0RlpXN2NaQklvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWFGTERkdmhBSzBiMnI0T0U3OUxwCkNvWTRwejR3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU1zNjNIOFhjL2M0Ylc0VW9lbkk2UG5weVROUFFUZHMKck1UMXdndnJpQ0RBQWlFQXdtMnBERnlqMnQrUFJDWVVVSURBa2dMc2JWQnFjOUpVQ2NZSHMrcjhFZjQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      client-key-data: ENC[AES256_GCM,data:JjU3PBShgxCh0imAStDQbL3YVnqVgsTtMKQsIFTEcCEOCKyaEBRJqxsT2DXDNUdojHQXrEbhiE6Vkcaij3Qgk/KRhHMH8gNQ7xKLMT/aQA5LZaHtRGh2re4tMS/aNjlUuNlB0YiNdUr36AXs3f5fyzKTxeplSGESCrlGuIJ/QHtQ4tCC/g906OX+LtroJRFqfM651uZkq3/11OJc0YdhuokRsm9uNk4JXxSo75C2U9bQNQ4ypmzgQ44yiAES4sBOMWq2+hjPdtpFuzKT8KMvCIjVqJ/Gj+QlBfFO1jfDF8HUVIIozLpoBXg8oC3qu2WFd3GfLYbpxWmFwf83lGmvloSfeOg0UOoM+hUCGwHIffwxvhWQsWElWpn231oe73QHK/4wPXn2BJxs5WCSoZ+yOw==,iv:h7EFgxdruLtc0M7TFxGsls/4On0rvnELzzNW1sIyDyA=,tag:6rRP8uLePKjll0B4vAoJfw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOE9QcXl0UWV0R01wQjJv
        OTZUMFpPSjNHYlNRL2ZYNUNmOGpubXFtL1FrCkp5c21xVDA3eTVvQm50TndEVGhS
        WUplMnVmaTdJdDQyNVhrcmh1c3lkZFEKLS0tIDRpZXUyU3RTeE5zcUtrWWo5bjJU
        MklJcmNma2FnUUhFZnlSVFl3eE5lWEUK4Rmo4Bo26R6DTr19ib4FliBhCGjtpkPX
        qaG+ZlKa+xj8nK5KGnmpX6eIra4cTMWuBEGheyk30xWbVX3iru3DvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUnBSSXRvN3dDdDY1a09X
        bzZock5rNitoNzFsd2w1OENKWVJBSjh0M1dNCk5ZZ0VEMmNNYUJ0UWpheDYxa1kz
        ckRKWEVGbGRBRlJmbVR4VXdxQjh1NTAKLS0tIDhaZno1RVRHbG8yd3E0blZ5WFk1
        Mkpxbm1HSE4vaG1rT0hPK015SENlQk0KvlKYkNw7H1PTLAEXOK9W7zcy40I2fauW
        +OwEan/0h07Hup8O65sZRuf8JOAuvRdyeirskVM7VYa2GXkpqJxqeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^client-key(-data)?$
  lastmodified: "2026-02-02T21:48:22Z"
  mac: ENC[AES256_GCM,data:Q4pIoH8etoNvccrsnBzAumceQHr055g0WVds+6mn1vn7vn32IgXWMd1BwvYneARC7SQCeKx7dqQuJKV50M0wzxDbVVGJIcVU3RsnUJUri3JX7hHmnuatIlUSuThkiS1wYEGbuRNJCSwrD+sFAucuANbZyBVGaWUgH6llDD7wti0=,iv:akOgWFOTRF+dD3a6vm238BDXovo4o7W6PRhgSztvzzk=,tag:ZnzvRs4XoXi5yJi4HpM4rw==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:34Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIARAAho3nPqt/XByYN8Bxnu8UMI01YIGgzpERDIyh9qLaoMyk
        RdA/RaBhnpUBGYfwgutpo9ZRqfbk3OmKr2HrYFjJPM1x6KZS8Of7Rta7c7Ssay4V
        NJiXc0PtURvk4JR+zKCiWz+wckprAkjSceRTC8M82WdTlSwhJyZBpxtwSbWTmgQ4
        dhmbUmHmot7nz8oh3HqqYM1X0i/6sxfP55zd4gFqOMRTdkZzt6lJ8uZBTHqpbUKL
        8QaMW65sZm5NV1h4CvloV3QydDTDyFuliVMuIWwr5B4HdnUYfKHTQ/cPvEtkwnAG
        o5wwSETNpgW4o2bziilxVdHjaFzmqXnRefs4HUaCEve8xbyzBhOu/40qDjj5YtjN
        I49zQ+ttBa8UGh8PPgVFw/QA40xKsxgk2Od151wreGO5NE0l/PPvBCL4MKAKd9+R
        Ztz/5oEl5u0TAW9Sqy8TEswie+ip9iMF9musEuFQjjK0YoOp3zEcB0htsmDb+uyn
        yf4NRjbAYZEAoMiXeQCmkxl0/jXfcBCnTtsV/BQfMVYGoYw+7IrwUH5ZgDlVkh4A
        FBOOdiXdhbpt6eHLfJmK+YEvHGESKmOy7k9T5DuBH2/nRnG4K3zyPeVWFG21BQxe
        aMXO/9VcZAHuhBSXzocCRHFh2ItJudonyAffLjEsrn7rMZoKDOsF5mVG9uxjyeLS
        XAG0E3SBo3FnkLykMwb1LHAsyMCi2i4jKgcPUG3fqehL8MoENhmRDm8ef7gA39ux
        g1PUXiWVpqtNemDQUbrVL8seYdy9Fs2M5j3kuPcCGWL7f7aspAroBj8bpzqU
        =Cl05
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
  version: 3.10.2
