apiVersion: k8s.mariadb.com/v1alpha1
kind: Restore
metadata:
  name: restore
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  backupRef:
    name: cf-s3-backup
    namespace: mariadb
  targetRecoveryTime: 2025-02-17T18:09:01Z
