apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: containerssh-guests
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`containerssh.ieeetamu.org`)
      kind: Rule
      services:
        - name: containerssh-guests
          port: 80
