apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: containerssh
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/logs
      - pods/exec
    verbs:
      - '*'
