apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
spec:
  chart:
    spec:
      chart: mariadb-operator-crds
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      # renovate: datasource=helm depName=mariadb-operator-crds registryUrl=https://helm.mariadb.com/mariadb-operator
      version: "0.37.1"
  interval: 1h0m0s
