apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: monica
spec:
  mariaDbRef:
    name: monica-db
  privileges:
    - "ALL PRIVILEGES"
  database: monica
  table: "*"
  username: monica
  grantOption: true
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
