apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: portal
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
  cleanupPolicy: Skip # keep the database when deleting this resource
  requeueInterval: 30s
  retryInterval: 5s
