apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: portal
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  passwordSecretKeyRef:
    name: portal-secrets
    key: DB_PASSWORD
  maxUserConnections: 20
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
