apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord
spec:
  selector:
    matchLabels:
      app: discord
  replicas: 1
  template:
    metadata:
      labels:
        app: discord
    spec:
      containers:
        - name: discord
          image: ghcr.io/ieee-tamu/discord-bot:0.0.1
          envFrom:
            - configMapRef:
                name: discord-config
            - secretRef:
                name: discord-secrets
