apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: discord
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: discord
  table: "*"
  username: discord
  grantOption: true
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
