apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflared
  labels:
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app: cloudflared
  namespaceSelector:
    matchNames:
      - cloudflared
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      path: /metrics
