apiVersion: v1
kind: Secret
metadata:
  name: brevo-secrets
  namespace: email
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:OuaH3HcxLhWJXl3LzTI+eKgfImLBxgYbVyrH1si1PdezR3ssHqZnCkVPHMwhWGsySKyC63vNr8diO3LEhEkbliMvhd00F58FO5Jl3MzTePWxDZI8FNKSQnzW,iv:RmRWpx5gtKQWX/EFfXL7Ei1x6VJmUmF3qdxYnZFWJRQ=,tag:3X8k9txdmpbyd8F7OdSu6Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NUY3eTUxTkdNMHkzZWNS
        TVhOeVR4MzFyYmpCaXZheStBbHZySzVmZ2hjCm9FQ05iWkJhcXIyYitqZ3pTc1pD
        VUhoZE9XVFpVcERGZnRLdlRtc2dvSUEKLS0tIGFYTUh0QStBK0YzeXhqbTdsTU91
        QmNVdVFXSTFVRDdyT3RhZTl1N21ZNzAKe4POSS3jj4gyUU6frxrUaAaLsOfFitnX
        Obo9rm1LJp/e2FDdcMuULHK8Y2MDptQGNAujWT47XRkRwdPEoQFW8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqa1B4ZkUrSWdneGpjcmZ1
        WitWakJERHcxMUlLSUoxOFlVMHVUbk5qUTNVClBzRHJCR2VNcW9XL2NuZzZnMmx0
        eHRiSzRaM3UweDVkbWxmNXMxelgvTTQKLS0tIGJibGZJR2hQYW1HS0JSbzJkTTc1
        SnBwQkl0Q3YxVFRKTUVJMXpGSXh3Z0kKtYSZDZrQmlYGiY0MEp8iPObgq5sZRpP9
        B1TppTi9ES1/tdR1NnbNNlAXvA//asCzuJeQ+hkmRrW92S5FI1cnug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-02-18T22:50:10Z"
  mac: ENC[AES256_GCM,data:cOW//5cv9yO1d7xdEoD5h3LsoQ5jhCciPvczb8yiVGL80ldnmLfyWKjTEb+xK8JYCM0byivocgKdMe6swA08Ry4JMW2Oee05kQte4JxSnUpwElGnkpBwF55f4P1vrsaM4fJmjH2vTdrBVYEqM6NRh7+PTSr+LfBCvXjpv4s7RoE=,iv:LVjij3tdxyqFJmTqe8BUjF6XwwpsC/9pptHNZxZYi10=,tag:Z9jiSmNJmWwF/YPVy08zJA==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:40Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ/+POXUsXNpEGuEKPZNEPqUYe2cxwodvtdwT7We7KTqzYqD
        OEyVNhJ6sqGB1Iug6aG8fS410i+0HHL+Q1pC+1RekkeVdkIOtHy7iZtzJmrFr08/
        9WVk9OgRIyrgZMh3vJHOGZqhH8CMB5K8/Ag+Sg3ETXxKr0K2YGcQbhSxTlHqMcuR
        QO6wEILpehPd3PlP2XBIaWCjPW3BGunLB28NkM5CShqJKjW6WJBNnSu3d7ou7zx8
        qPciUs4n0LCtP33o9WlPiamLlATwnfkNfYg0GMFoaktf+NFyPwMBBWLFSA6x1ynk
        UG/06O/6psQFiaZDJdnkkBoW4XyclKxLRxLhJXCoY/7W6P5LBsADxj7L9bHBLrTW
        fmGt0En1o9FUci/Sx3UJZfW7fQAfCTRQYuZmb9/VTf1uzs/feT9+IgUB9sFjBIRm
        86duw0X54EI7Y1WRsyREXMbHZ0hlivBCpxU+yrF6IsPEYUh6WEXPaddq2ZovTnyw
        MQMKzDIJn8SYmAkMIuWUSworRqpuNVeaxOQKm/IUktLBuNk/uigzqsLxOOMu+GpU
        v165qCRufCleDcWczwfjEwzBPcV4tEbjpn5aw0Mliddc9DFEEV5nWZMHY591RSM+
        TzsAQNbX5CsJvDN19z58cvbEQVZHKvkPFjKsXjOqcgJ8UCdGUsP7pKpZrvdHIr7S
        XAGrOwNpd+5kTtFEApwtQl2BLyRnnDrQItmNiVFvw6wHt7QwIgUbMnMecifJ3B/i
        kjGlJSfEmJdukHDr8d4vOvoWOM1Yn3AzfTW7Zvynjj0X4XKPl9PQ/A0bGWQR
        =/eBM
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:40Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ/+PGI76eF2Rjq3kobOBr+bJFWBtPQigt6eByBccOPhid/E
        yK7ebGjKmvbJaiAkH/gouZoxsGu69iR02TQRA5ggC42DU/qtsZYHioW0045sLRjL
        M0U18Qfr7Ah9pXr+MogdbBvnMSEZbeP84A+xaHrE1smosbVxk4AVmnlqeQJVSg2H
        YgF7M0va1dRzpx7S8KIvCsiqyBzr9IgMhHBPFp71RHK/H6TLzCyTJw2NCPZEyPNP
        cQlm0CEbMUMeuxP3ZVpz+XbsIi/aAOWbRU1o8ENPF9i7cZ2XfAadxDOF5fgJys79
        eQr1QxGyqs7Z4WahkO0qzdtYjFcDybqWkYHCpc98bXdzF8PnezhLjg+xeX0wdVZh
        L5BQy5tFCg6x3JzCYpUw2rn2jhVBP5SkD6punAhj1+pkVFQ4WW1mfiT1Yd2PjXqv
        +3BM0PJsK4M7sPxep55TV0yVMylpsuUdfJ1ko97uYleVOpp6QQ4jnotC0tL7nHtw
        aujs+v/rkzdkzsQY02ve8xVynQMKzoCqOFfzTcyJkpbGPmU257SXoPvLGPWO566r
        njfEcGmannxWdBENVP1c9ZRx5ubp14lh08In2e40WhqfmBtqYnA6kKzTU8+IVV+8
        56rzJW9T9u9bMryHKvZLgfoR6RfaKIPjy661NvV1ZhkGQiBEzi850NYcrjTXVzjS
        XAFGGbjIsfqZAoqUSh9mPJq9pTxTsisI4XPgiSYnnt5qdOMESJsXyMGLuGECP7Lk
        idN7Sd1X0Y74PvvU1fYNclN9LJiKUr8U6waL+D2oMQX2U0Vnfw6gHCa2BtEe
        =fA9S
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.9.2
