apiVersion: v1
kind: Secret
metadata:
  name: brevo-secrets
  namespace: email
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:OuaH3HcxLhWJXl3LzTI+eKgfImLBxgYbVyrH1si1PdezR3ssHqZnCkVPHMwhWGsySKyC63vNr8diO3LEhEkbliMvhd00F58FO5Jl3MzTePWxDZI8FNKSQnzW,iv:RmRWpx5gtKQWX/EFfXL7Ei1x6VJmUmF3qdxYnZFWJRQ=,tag:3X8k9txdmpbyd8F7OdSu6Q==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSWZYTDVvSzdMcEFUN0FN
        bkhQRWd1WUhDUkFEMzR6MmRVOE1FZlhKR2lnClA5NEgzN1pFUTNtaTJWcU05TzlE
        ZytTRGhoTlVKMUtVbXl4OVF2cHhheWsKLS0tIGVkeGY2aG1sL0J2NmtLS0RPN1Vx
        QndQdlh5aytrdUExUUVKcHlqZENOTUkKtwKVuL+HBVbHWAIbuPY8xRuXfQN/hQQz
        D3Or0+0c4+w3tiZo0YEeb99QG4x6/f60P5pn4eZtknfjIfPQB72ftQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ25FT2Z0YnczbnUrWmMv
        WUV6SWhZc21kdm1qLzBnSkh6dFZVSWU3NzA0CnR2MmhrMUxHQVZtaGN3cm9Za3cr
        YWJxdmRyNG1Qa0dXZENSZGh3OCtxN3cKLS0tIGpFYVZHR2tBTHl0TU5YT0ZhdVR1
        b09LbEtqQ2ZUUlBrQkhpOFdJRHc0M1UKHdwRzF6DI493Vvx1w/OyOT1oZY5zkXai
        /d6Ol4KzRKmvMrNXUNyIzzF3mHGU05N9A3I8Zbt1qYkJXN9/y0Y9WQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T22:50:10Z"
  mac: ENC[AES256_GCM,data:cOW//5cv9yO1d7xdEoD5h3LsoQ5jhCciPvczb8yiVGL80ldnmLfyWKjTEb+xK8JYCM0byivocgKdMe6swA08Ry4JMW2Oee05kQte4JxSnUpwElGnkpBwF55f4P1vrsaM4fJmjH2vTdrBVYEqM6NRh7+PTSr+LfBCvXjpv4s7RoE=,iv:LVjij3tdxyqFJmTqe8BUjF6XwwpsC/9pptHNZxZYi10=,tag:Z9jiSmNJmWwF/YPVy08zJA==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:21Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ/+NfOqK5PIXZ/MeFR0ddkQPk5koMrTnIBI04l4Pf2qIyA6
        jXTMAzZLBrruy6+rWLA20Ojdsm1Q0kJSPLAi6WSBOP7+sAjULQR3QNR6eQ63m7vD
        7xLieWR+XYi3MgScJ9sSZKnaOIsYuNAH2v/cKdRBkt4lbU204e91XtfxmStquuVf
        bBN0SooWvlNzh8zc2I/TEdXwwj7q/X10PMbnEXB9CIK2D+BDRSqYixtxopxSTK/5
        ACGAp6IJsGSjSz8Xj0g9E8eOzgQSxDd8sdRMwcCeemvx+dYxI3lFx8bvEzMg1KPp
        Gb9Hf3kNhTBuR3e17IifOpb24Rcac6/Bu9mrIeFKgg+rckZ1yQKMtOWdi88B1Tab
        iChYFDLK66hE3ohkt4zhzPHsmINwol/HxQTV4eX3xJ1ppfUOYZe2TwZBU1SErhGF
        H0KAhvZ5eH60JU0Fj1DUgMf7CqoMj3yz7ILfEBX6eJXlv9UqhpGOQOkHhxIJ/17Q
        7mFT2O1ulSqjB6FDIoyHwyWKqOeWf7ifaIgnC4eJLxyZTzdPA6YS/lMPuWN5cLrk
        ynRVIFB02wuLxt98DgKcbUL0c+DrdqXrVitLicNOOtcE+HhNzTYJrn9pCxe9H9SH
        QjzYjUxs10hGOlcpkjiwg2nF/KDh6njX+YqzvHpGBAg+aMzP8UJr4OOyxqgYssrS
        XAH5c8BHfXORZdVS46p5BMH439KT+X2VW84FH9ug8X/Xe7bx3q6e4iBGYG8tAhT4
        JmqHvcKs5Lr5DVm2bODMFaIgTFDR8+qnSPjXCD6oJCoGYnqqkLf6IBT0GdPv
        =gyD+
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:21Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ/+NuXf90tmw2gAvFNdIXlFffpQelFNkLzCCvzCb0jVspYh
        3SBCDy4P6HsIebhRrqZUJZlKy9pHqC9Z+PDydJ5kLEWyDV2kK2rKYePPcChvQ9Yy
        gv8HXizgepWy/UCE+VLCFPiC0WUBTkG//VShWr2nvtJAu08hP/ohlwv6bZmflggm
        gzq1K2WRu043PibuLvy4pF+X0lSui6IvIZ2P/uJww2I2c3L6pBbhKfbU1bMiNij/
        4+vQTQQj2PtDOF+0/ePCySIVm/5wNI2vvBVKgEZHtdqZ5PBFMWT7460C15A9uEzq
        ChQP1r29WiA2IUvGOR4Dtj5qxoTYREv/gFBR0Qctcso/8xxuMYrdYilQ3OLsRSGw
        S/8if/XRJRTeM+vwfnewWlN9eOP1CEeOkiKu5syF5WodEBJHAhREXTes92dP37Eo
        7obKC0kNd8bz/BQpZ6rwStrsEia+2xI+3+LRAYeLqKRYpNXFd+0QiSK/BA6sf0ML
        UZkw22lfSSS6LnC2VXgCWV/QWrktkTscEdbjIDKqGI8M313mvLms1IWyHYksgliW
        2SNwYIO8bbPDdVdlr5nDODW0KrgnQSfbWxFseijgBGdVpzMKLze2cx+TNXkyLZGQ
        v98L1wUS2O9pRpjeVkNnDTPRcRtbvke9TKn90bZ83WrxMF0gm2TnuODFxPCj6B/S
        XAGXxi8NtRWAuwerIl3PlBSwcsWXJlF24M5pKEVEKiB3VIGY77Oiz31BPsPET3YQ
        +JgH7+rMKc4zTTRqac2l/ApBGhOlKE2RL49C1MIWjxtamFuL2Q//t1nJ8WiL
        =7JnH
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
