apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
stringData:
  credentials.json: ENC[AES256_GCM,data:5wEjrx058lCCor1I9lCZo5fWdeajJgpTM1gQZpHb6oyMIa/1Hs2urBCosKEKxoU2hCRX1xc4EUscqU7C8FlU4xbFGxQ22V3ERJF2MYhv37ALcqFtL63yJaIiz7EVm1TX+2cvS9s3Pez7MutGd4Gd6ZCAY6SIJc2SvKZ1Q+PjEpP3mWweS8eDlcuKYpAnEbRyw8NJ8A9HXzoH2FOaV4fIZC4=,iv:WeGJ/rOVs2eGVo0v2Tfm9A8AWMYxnxvNPaBRFb0/0Lg=,tag:svLb3bD0NwH2grHwe87p2w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNlRUeExPZ0k1Y2lmQnhy
        VlVqdGtZUGVwQVdrQUZYbGt6bEZINGFzWUJRCkczV0Rjelp2cTYxTTRFWUZmZ2VG
        N0ZPTkIxZTN1TmlWcmNoNDVKbUFRYmsKLS0tIGFER0tsWkxxZXdLbkd5NGRVTmE2
        M0JGL3FodEV0QkxqNXVuSGJjY1ViVVkK/4/FcdRPnZV0w+GgIpPtZTXLuU/S35Nf
        rY9uk7r0uEsETXnBwzC6ygEARf5xL7lOsOf9XUaS31RjnTQb4XJjOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QkNYR3AxcWZ5cWRHbnNJ
        MTJLVk96cWFNNGtlSUZvcWloRU5kMitEYmdrCm9oU0lzb2VKZ2pFcmJXWnN1TkhR
        SnpodDZ3QlVuOGROUk1hckdOSm5XWjQKLS0tIGI2ZzBKc2VRazNVa3pmUUszQkhn
        OERWVW1yM3AyY01VMmpWTEY0Q3BOajAKeBdqxGD24XrIa51fxOqcyKgsXO6VbKNJ
        fhId7FFWPyn5FsNoO56ySCOWdIW1YhZ8mHdoXdZx7jJ4f9tGKIneGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-04-22T19:01:37Z"
  mac: ENC[AES256_GCM,data:Eh1TG0I5FxklWxvBn8laJzhhI3lTXLSOBTbuxFcLhRko7PfcDSKnbBgo3Ro/NnygevIIXPlLsHhT3I+cizPBdC5RRRQYZPPYx6eSvhycMBMJ+esKLLJtG53E2r+2fZ85OVuJZ9K5rbtjEICX1pCC9TS9NtOpfzBiYTK6HyFqr6A=,iv:KX3GbzScMmDMObp2czfJYYj0H/tdYoQKuvkENPffVlo=,tag:SMRKswN/FEcYnnkbuRgcpQ==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:41Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//Us9LVkN7eKiTipNK5Yv2+pHiY+91Nb2hzwdpjM6OzrSU
        wR6XRBnaXVonPFzruKNtNkqFmKfdUi26oWIVaiPeRSCNfBG/sP7LG7JCsW/EDjWS
        Zs8C3EVcgVpHC3VP6RIKnNV94yeK3K6qrayn4LqO0Ba0/5XwhvmeEzSA2kMBeo/D
        cLWXMpJlT3pnTV/fsrXKoG+xUFZxOfSwKyDOZLUPiISwn7l+Zr79tV0jsOYhqbBQ
        ipSvxHkbEuvUknxF4oI9U5SYpJtUy1JC4Cgt3aSFVMoeVU46K5BffkXiOjulF1em
        vpYSfZri1MVH9iFKKLWDCYfx1C78oHVh45GIJtzzoM8Zot7WVCXAaeKSAZ311lON
        ZPQgRA/xQCnCEBXvFvAU/gddrenZe90nxcDS6vCY9SEGxkUIP4mMJtMbdeMTB076
        tlXjgkTOhgg9IlGIRJ2H10SvvA9v4CROCbhz2NOYWYX6NHZ9wifIAJqzO8blMt4+
        6u/ZztgBTsAL1xdCX2cGzSb92X+q3UQEsWcAleae3CHvTXNOc4ixK+nfkBRd1raz
        +A6vTFQKRuS/y9rTut7CttzH/5UqU/X7INNqxU4Epl920BlrKaRy6hyoDVD6TNYP
        Ze8ciSCXkOQKWOegvVR+JXje22dzvlbKnZ+mOXH7z6mVj/tP+DaPFXAQ/MJFCZDS
        XAHrG8+u7fEyWeyhsjqfgbdVII47CEtMyW5D9o++a3EKrOQP//OJp8p+++4PUHO4
        XD9uaK9Rq/Blu3+/zhyobZMUYaKMHWoNOsqip12+4Tn8zQXAt13nN9pS4LhX
        =q7no
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:41Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ/8DOHlrFB5XGbnPZAyCj7+yzskwDQJDYvMVc1ApYd6a4gf
        72ZEXpK1ig7bpYx0BgcIOq078NaO74HkWDBtNu8h1ab8S+Vww7koy3RDDRgga0L1
        8Bo+YE//msNA5no7r/iSV3+kShEDdBQnv4y4yy3MHS53SgE+FX+0c0NXGQj9TCcl
        0eTRRzM2AZjKekVlxWRYF165EAbfV82CZIkCM92p6FZ+oJHBqciU0kbAOdutsX9y
        y12mF78xDDiQ2ITjDVrFGt/DW7SJHUilCUdEcR0uZpxK9VMnSr7L67ceecWauMYo
        XyZsx1zV70UqXMNDLqHLx7LbcG11EoHh+TAKASsP11N+nyAa8OQ3ZNLuY6DCd1A6
        POfzCy5xYOTKmnnhLHEA9SPhMZ8s9qIyLi31sNWN/Ey2l8awlVApIU1nk677AdMS
        PlVGGjrHtdJjYVzGscbTJgfEukmfBOw5i/52LiJScEl4sHHqlxWjYTM8PsUQwVTv
        CaaAkGMk/lk1ytncMH488gjMraZ9TSpUI+ajpsC5UhWE7cA8PSWKpMKujW6QUk4c
        9CNyMgTZVU5vbTYK85PmsZDbqYMnSq6+OOCcFFp73/vq/rANOb5F8BJAyekA1wXN
        0ILG9fBaLWTGzJOBYiLtoNLoufnt9vtlJp95uLb4mIE+LGyAG+nbWKYF9JLaWbTS
        XAEKyq9aTX4H+Zti+35WkMMG1z83Y+dE61fq3bmAxjb1NEnkee0lFUOA+wWBb8qe
        PMjQ09UzD/z2mqAjQLkPCljV68FlQWKhGikaqi157dqVDaPj02n8l0NvK4r/
        =FE0Z
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.9.2
