apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
stringData:
  credentials.json: ENC[AES256_GCM,data:5wEjrx058lCCor1I9lCZo5fWdeajJgpTM1gQZpHb6oyMIa/1Hs2urBCosKEKxoU2hCRX1xc4EUscqU7C8FlU4xbFGxQ22V3ERJF2MYhv37ALcqFtL63yJaIiz7EVm1TX+2cvS9s3Pez7MutGd4Gd6ZCAY6SIJc2SvKZ1Q+PjEpP3mWweS8eDlcuKYpAnEbRyw8NJ8A9HXzoH2FOaV4fIZC4=,iv:WeGJ/rOVs2eGVo0v2Tfm9A8AWMYxnxvNPaBRFb0/0Lg=,tag:svLb3bD0NwH2grHwe87p2w==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ0o1Y0o3YWVveTllek4x
        cnEvaFd6OFZFbU1tcExFb0g4VHNyK3R0Q1R3CkFGcjRLcVdicXA5Mk5qMHZEaER6
        WEI5S1lQSkp4bnhXcDFsOEFXYzBBNkUKLS0tIEpRWTVVem5zdCt5elFBOU5tVXFN
        SDg0ZW1CZXZEZ1NuL0FONkhTaGQrSk0KbnekYGRZHYie/3LldDXmyn9jCa5dNoHK
        flzXhouM5kLefI6Jviz6gtOB17CJHw3giqpF1hym78TO2SzFUDgQ2A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Ri9VbFZrMjhlV09Ld0sr
        Zmt3TG8vK0tpTWxEdXZVQTcyaUZpQWNzcjJrCnJJWGFTdlI1Wm9TWEczS0FKWlho
        VUJHYWk4UmFva1JRS3hRNUpWOWdPR0EKLS0tIENqR3hJMzZKY2ovWUgvNVRoZyth
        bTZxQUgvMm5SdmkvVzNsVTI4L1pLT1kKOO3+7mOgPtY5Kl5wTaroGfnbob85urk+
        zHXxLQ/krn2UCTIa9n+8J4gHeRWCKLWZ1Oum+M0vpVRR+mDzdBAGvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-22T19:01:37Z"
  mac: ENC[AES256_GCM,data:Eh1TG0I5FxklWxvBn8laJzhhI3lTXLSOBTbuxFcLhRko7PfcDSKnbBgo3Ro/NnygevIIXPlLsHhT3I+cizPBdC5RRRQYZPPYx6eSvhycMBMJ+esKLLJtG53E2r+2fZ85OVuJZ9K5rbtjEICX1pCC9TS9NtOpfzBiYTK6HyFqr6A=,iv:KX3GbzScMmDMObp2czfJYYj0H/tdYoQKuvkENPffVlo=,tag:SMRKswN/FEcYnnkbuRgcpQ==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIARAAry702yiIzB3e9qpWkKd/hCdFaqvk6L7Yx4t5gk0GBGnw
        C7juxxIfPLjd4uT1Sfy2yInnANavnmUdJlGu7aKRWl2ngOFD/yHkqGZD+2cA2ck5
        NuSp9zq/fjBRRvk9D9gVJR1Ee8S49g7EnpiZYSpaD7+xQZZHqHGfKVSlrRHIm+Vg
        b/JgO5GwVKa5rLV3ledWUNzW7RGbV+JG4nygzGHR6aAgPUH64Dcjs/5GvdqmVVdf
        9h8W0uIkr7+fOD3ILa/bxZaIY1VkVfG6BMHo2ZWmful0L5Pbz2gZ0hJe4y2Kuw/o
        CB1ds9NWU6AcNcT+WXH3o9pZq2mfUrvhlGyRJi74LrOvW6DywCjN+q/Gedn6EiFV
        TOWWakB2IwUzk8uR+Vp4sIMrnpfOcN5pVJGZMxZKtKmexKvkaK/a5/Q70L11kBdS
        OOisHukcvSH0bBTEmoegfT18qRNEbXiA/ccHfOx/YGjN/9jkAxkdSVt25VUc+IeL
        p4N14aBabMReLdVBdxGzdr7NQ9S4HeefxZgxBqdGGvp4kFBHZDLMqLx/49So/z3E
        ESzk1r9HZ+ZqZvn/bN+7u8EnFpgcFf3o2VduQhTEo52AvQe52vf9UPFMIZTUvSoW
        YBPA+s2Q9uCzymGR+U61h8H13sCzoxm2Krwj2LQpQfgB4mS4h7bE+NMAfBcNcsDS
        XAFNjoVOWKqAH0sU5wMaZWUTMNSa9l6ksbUVXdtjd7z5I8p8gVCKfOM9CwL3hTlL
        +LeQ66PTcDWv+Lefd9MfYre8YcGOC/paB7HW6UlrIVAhV5DvNA3tTg/aVMmM
        =Eqza
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ/8CxoBucY38alZCHKnUJGAWzSoiQZGzA+IaSLVBf2cnwqU
        PtcH1RmqXkkCTtKDIXYH9xLa3XCsrvqF3vRIrZk9WLgy4PLXxm3LtCZnp9+gkkll
        jp0pHc2ELs2P+ZvxLLW2X10UsXvwWsVZqKl0XZJ1RU9qvO57FW4cuq6h+9yCRKGx
        hcFTL538K3IZj9h7OqdqKYwY1NdY9rbldTe/jVQdKfTSZTBTmftAzrlz0h7VvyIF
        fZ6qe425txkNINCD2GgZgp0RDj5OQ3jVMiC/8CvIwz3yfqVHWWh4iaSH1adW6KcG
        WOHOACNsyNCuwsyTvbP0PAEaYqeNriOWbMOqpy26mT5q9I2dfni0Lfj3UTLbGjbq
        1ErC++erM42UA9C7xX47vbKPhmPTZm5r4a7TbroSBNFqFwcJEz2yIuvkYbjKs3Cb
        R7Te2Opk12o4pNAk6CCZGb0ImaBXPUkYKyOAZo5i8eVIlBF+kfJReMEDnmtc9pFC
        UT+F9JVCuBCh845MKcCRhLiiZdYWYJeBS32Tv7TUEUkmfkN/JN9JFNVK5sHuZBru
        SmApHgWSEtNWkv2OxJ5C7g6GsyQ2ChYhTZMoydd6QrM2XdIZR0pNxXdWXQprgGFV
        aXOBqk/qRTFCzm06Q5g2xdUyJXq9vgHIjO/Er6HXwfsLqaoOUUWL1kLsvYMbtnrS
        XAGxouKa8dS3dn4uwHW7qKDR04rINT+ObYR0RRFHLjI+E8UDPTSrce00EN5SDuxF
        J872RMuKTNse493Nql3S7lQGvJFP1h4nqh+NLeg7PMXenRGlgkyWpTBW2D2x
        =t6DS
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
