apiVersion: v1
kind: Secret
metadata:
  name: discord-secrets
  namespace: discord
type: Opaque
stringData:
  DISCORD_TOKEN: ENC[AES256_GCM,data:IvVH2ee3lDQrchAY2uhQn0nY/LZBiucBw5SrhdmCtn8Bt1G8KG3Zuty18MsgaETAMGpdeZ9Nyo3kYjsDfIoAu366+tZC23rx,iv:ayqm812guFy7U6ETprmS0vNYPptEjFz+aANSXd5PqQE=,tag:ew0t8EFYE0znCLktJVk7nQ==,type:str]
  GROUPME_BOT_ID: ENC[AES256_GCM,data:+EdXlmfSZtuIz6wJHKGtxMSaWbTg79wNX6U=,iv:olc+UxNisFE6LIyWt0azEBwgyO5ccMTD8jYLnqnjtQw=,tag:h6OqeYTs9ZGkUXtiP+lc8A==,type:str]
  GROUPME_TOKEN: ENC[AES256_GCM,data:ZzuyZ2MeHtU3/91uUm9HEBeVuizYvQLvT2t/XTTT//9/kupK1HbALg==,iv:E7lrWa+fi0kPRVaCFSHnaG5eKRChabCL3G4LlFBb8wA=,tag:pM2N/QGIDR2athzueQBSwg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT2Rzb1RZTWF0Ympzd2I4
        MHNiZnVqVml2NDN5b3dCbzhLQ0RNcVBiYzBRClZlTmdEWWF3WUNtc3lXTWxOLyta
        bGJzcWNvTzN3T0RYZDZoZ0xLRWtNNkEKLS0tIEs3ZlQ3ZEJnZWJNMWlLOXNtYjdl
        eStYSUl6aVhMWnZMUkJQaE9XdUFnRjgKynn824ARWmRsJylUtxrOjMx3yj9SYdz0
        6Z1E1o38ul6qLagrMoBdeIoZjQdUo+XyiylK0xizJCpy/k8ZUrmzxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSXEwMDltZ3ZId0kvYTll
        dHhMaTVENFE3V1IzQ2wxRGVTQU8ySDAra0RFCmtLa0xuRXhZelhhbzFtcU80cHJ0
        bXNHNlVZZVU5cU1DQW1NL3o5dnVReHMKLS0tIE1yTzRQRmkxeDhqemdnTG14NEtl
        azVNbU1Ud1FsZGlQQnVJZlMzSFVXTTQKugPdQ+bU4NMX7emYcdMB8ab03+cLCtNe
        7XaBUrIp/MKCt8S7wA77VLdhuJdbz2LkA0cZWICT1bWQndbGX+HXoQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-03-06T17:29:27Z"
  mac: ENC[AES256_GCM,data:oPFzNoqVamjrHxJi4cadxejMbiUrCSTHDphl1+rRv+VNMjB0H2YnbQfHS7uHPE3P1oizFtGPx+QS0LVCy19yqGyWTf18hVzB2ckK1Lyi3vPKEFRg57e+eyiEdOwxnlWfjtpefZbvnDzl9AAgjbnjb2Ip+Dg65VC/iacpMi7hjDk=,iv:splmmRDqK1MhvDGKukh9giI452TjLDOdssFcY+j/u9A=,tag:gChfyolzBmNMmxjvKNGYKw==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ/+MKUdGBxVzYqdF61/KoA0wB3+o0Vchtteo86lyph5+5Vp
        9RGJb4/TOvbvQik/jNRe4Es8cajO//JEs0wmwF2lgZ/C6KGe6aFBmh/hTMA/NUPp
        gZBVvH4igxsObY+F1V2gbuozsJOrdLGw+b5JNXa3g3jXzp+xoIIneFNt/liMZ9uU
        bA9OHugqcoShbBAaClD1hYzGDRNNxt7Vwc/CZNcV7iRrcaciQ7hoph+h01aZ9U4D
        j9MeinVYdutoGIKDXg/WouS4DLKtQP9A1LZePLVdlGf4YVUkgoM/w/qYumQv7Wo1
        9+2p4lXSHhZhoVhbZ232u1CQLtUoowKknigf1N7e4lio7R8uVdleatV3/pYQ+LGD
        5tGKWjV3X5BuF+7kXzzYWmewcSPFX09zqvC/MesdsUHnpYakjcl4piTavqWU3iwA
        J1brz+aB5ImWEnXTzOlEYnG7TNeutOwXxAqq5XCD1u8HMTNO9vwqF0E69kJ1vWA2
        fPb+2mjQofP52mep/j/QTkoH+NEoO9LWpgKKFP4O7Ec3Vn+xHr1dhGs+2tmSINwg
        Kg8Apk8ULsR4hUVt+urDCIZabhqRuaE7in1OHhEhvaluNAqqayatGr3gcfFBtzJY
        4ze57/AXfOHLtoeYH6DFaymyjSS8ZTvCQdDFDQbIXxPoH26Gudkl8VVMS9Nja6XS
        XAGc2cURoyJM9sDoAK304qBUs5mXyR1khTvubqK6kX9SRoYzSwzFFErD/CPzeFVH
        JJuU53cf7EGp/8FKDbhCklK5GySNRmwfMdFPIIcFOhWzmEnNhssrXV7m2ryY
        =g/Fz
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ/+NoDIqTIcpcSjAH1EK4Rn6SpSZO+Cs/vG9tEua/PsFOML
        pYCENghNMt8XAE8guuG0khnyiBp4ZmtmH+twjQlSVoRJ8T1hkFOwN5IfuQ8jEHa1
        w+Syq9vTyI9NXIM1tHW0ExJ0Oe49oMR8rpDqfZ+uuJ3VQVWji8YxuF/Vkr/s95qc
        yXUqYyIUCDXIBYMuiL3PmEKHBMDVOa57o50EZqM810d2Lj5y9l7O/g6IZApMyRMu
        YrAfR0VAG5/wgn3i6bx+tRt7dX+Q6odtl5gCIWqPwjSpKmeWk8iGgYPIONB4w1SV
        /Mpjyegzx1zs3NiCgelIbgESDRQlCq62xtAhM5p9cs2p7WHq1Lv1WPH1jWl3X7DA
        wM9FmIlve7pmj9rvRf5UitsWl7/3bDENYID2/qI+Mu3w5kxzeDtWRnPI8BBjN4bW
        4rzVhWPKSpAI+/vFZjpnfk6LjALUe8KCJ2NxiBhfWX57OXsTxPKNUYajynQdRjyD
        boaGnniCPGICRt9+kKi2uejFESCyUIqAAaLvLoLAUai+qGS2vLmEDHUb6PiyFiL1
        RXlBRi/Z4h7SQtJdf0htCPuWlSkSAH7F0EKcmKLv9mGmfczUF26o6deLCqW1+sAl
        oSCJ1pVxoRheH2U/Q5iBmckGeQ45WD2aDEENKllJu1gDYaDJKKNTV7uQup7zyiLS
        XAHVXsFAasObbualQX8zpSzYEVadihdOw/EsRMyA6s5SldQAfsDyTl6O7salHVHL
        OIC3lh5ObL6qGxooZmMopwpOlqkm1a1deszhQlTlg+gq+SyyQbHbpNfIMhF4
        =pOyv
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.10.2
