apiVersion: v1
kind: Secret
metadata:
  name: discord-secrets
  namespace: discord
type: Opaque
stringData:
  DISCORD_TOKEN: ENC[AES256_GCM,data:qsJ8ht3iQmlEHm/Cibf7bbYv1cj9U58CPB/zqk//2A1oe8jCZbf8uxMBnGdozXr8HTwACuqyqNUUYMc+QRL6Xg7wkJMdSZve,iv:t7SSTx4icxw6HSFVZ0LDMkIcJFX8KzzqRV4cfW3jUcA=,tag:g+V8/4yreNDq6k9crXo6TQ==,type:str]
  GROUPME_BOT_ID: ENC[AES256_GCM,data:+EdXlmfSZtuIz6wJHKGtxMSaWbTg79wNX6U=,iv:olc+UxNisFE6LIyWt0azEBwgyO5ccMTD8jYLnqnjtQw=,tag:h6OqeYTs9ZGkUXtiP+lc8A==,type:str]
  GROUPME_TOKEN: ENC[AES256_GCM,data:wJRCHVB33SbTnh1v8eSCSQnlxSAwl5OeJrW6NLKYiF2Z2fi8UX6xEA==,iv:3RM+ZuoiISvDIji6hHSr2afyv1jZ04CcsdTCVnxJhEE=,tag:SMJVYnak1B3czaiaQOzhLA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-02-26T21:34:18Z"
  mac: ENC[AES256_GCM,data:MJEmqjOsgmG7j38E5LmLVWD96rdx/bhfBz4jLyTeoSe/q5mHGkxGMjg8A/Sp5PpaxMu6cQ7BB22U7l1ai8VTaXYq/QqrZn3EjzHCXSF7hX3HY6ZPvuB7jFrg6ta9mTpvpeLMAKdfK0roW1baVsG7sP3/gOuk5QoUP7N9kNxION0=,iv:o3UX9ttnymLuDdBXniYm2KBpJaZYq1Wo/AONDDNoqUE=,tag:m4/D3exmgly6n4wSJIhyAw==,type:str]
  pgp:
    - created_at: "2025-02-18T03:13:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAwAAAAAAAAAAAQ/9FgVEfzWJtMO34zDU1h561PN8Jz3HJgQ+JnNLF0BrbwUa
        4VM/9JNl4TX7pvZTeVSIwYQGTC/WoVYMIXQ9u8IPc6EgMZZ2qfwkSjwQ4Ghld3Nm
        /eWbGKUTVeDLnk3GuJejxUmyQr+3Mz9/GGAeWJseQ/ozU0kAPM8jVG/s0vlkCOP2
        Hrc68T+r828APelKb6zQEtIiBc29jVUmQ8b8tcZzX59zrsRGMGJaQpq20iTLuKZg
        0oTePzeCDVCyUNsOwgxkXo9teAlxEBTjFsjS+kB03vxEkVIVVfpqrAUu6ti06gji
        RrFpzxtanRc7sgT+mRLvFnggpkJTAtcGdAOWOvAyBdKFSS/+nZoy5m8NwiCaigv6
        TEFoibPpefm2ilvrWgiZQneXd6utpI1BD8MiTCxShZirU/rpDa5BeFJ+uumgVYuB
        h+D+BKZc1mtt+nfnkftyQf9L9mnnejGmVNWDjIKaQUFOE7k6MbWPwc03RbMChabl
        RiYNgssp8WRG+uhAryXky/csCIniquloxgG3fcEuUpUkKmbhfvLSibPm6LtkNXrb
        P1muuG8T0/idlH+g+qhu/xVYU3vCaMlVc3VOTl798jDUH4mm0C8+EGBBCzUm2a72
        s/NApVOMr+vzpHduh0dembpHZRqTAFsfH2yGRfvLIA8Dw6fyEgWRz7boNlnkA17U
        aAEJAhBxkNqXnThFUTWGZ/YVZSpMPbmVhpsqRJbKLcGxObjT1aZX2C355ZfCffhB
        2fQfZbuOcw/H6A7CcV8KESqZ6oCc87FaiQdkiQIEWaX2lQ+jLbtPb8y2h0rpwFkq
        gpfsto09wRQJ
        =eRkV
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2025-02-18T03:13:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAwAAAAAAAAAAAQ/9ESxXL1bRVt2izIZjHmiW22m+KfXlQxWcOpFg4BvlioFs
        YY+YadGIYpYIpGZ6Q6fWM152bXLil480n2hM8sd8l6K8nJTbYojd1DgjekvXfXgQ
        vXoj4t5GzugUo2wn/4NzEoeK2NYavgBboWp1jEEETToOtuJZSiLNCkevKxs6C/n5
        cTDcHPdnC7Gz6aAj1Qm3WdDFTuXJI/WReCpH6rAywRC/7rIet6093spvKENufkQV
        IomuOA5FJTWDCR8ipsJHj5pnhc44Mdt8R2DbiO0jK+2HhHWKpvZou77BCqkFZmah
        M6ODS96lqm37YGxZvo3ahrnelzhr0A8Qyj4oFyT5DHuPwbhOAc3y4Zy+VxrLrI+m
        LR6Zi0yiOqQLM+prFNKHK7MnBnKXpvHAwSVtDlgiDj9Cs7OTVEPjoOYB2M/BI/pJ
        y0ILXUbe/0jrNpm7Zk1ulavt0LGdJ/vPzrut9Ew3Id6H4tg2/PiEfc2gJnJ4Qwun
        WugDg9vrGPMVp+XSRUq2QmHN3J1RvPKn5C5AaRE7e4tF6k7lIxi8+P+fjwUbgOMK
        pZ9MObVm1EzpcgxzFYn0InaM7FKZw7g5pkDXiT2lNkFm5Qch6Qq81XgTobSv6e6f
        A1O8Be7D9Cxos0HMwIe58D1Cm3ICP/jR59/HCqHM5HNSBmOoCT4fhwvNfdMBeiPS
        XgHlt9KxKZD5RlBwVMuOGf6lWuRewswdMVvyPTaF1tMV7rqH4+4GgC5dUE58HR3J
        Z0Z3B7EyxWdcrr2n38liequi9f2BwLJmxSlhWP7eHsBozw6Sc4PX2gu5RErrLHY=
        =QVGr
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
