apiVersion: v1
kind: Secret
metadata:
  name: discord-secrets
  namespace: discord
type: Opaque
stringData:
  DISCORD_TOKEN: ENC[AES256_GCM,data:IvVH2ee3lDQrchAY2uhQn0nY/LZBiucBw5SrhdmCtn8Bt1G8KG3Zuty18MsgaETAMGpdeZ9Nyo3kYjsDfIoAu366+tZC23rx,iv:ayqm812guFy7U6ETprmS0vNYPptEjFz+aANSXd5PqQE=,tag:ew0t8EFYE0znCLktJVk7nQ==,type:str]
  GROUPME_BOT_ID: ENC[AES256_GCM,data:+EdXlmfSZtuIz6wJHKGtxMSaWbTg79wNX6U=,iv:olc+UxNisFE6LIyWt0azEBwgyO5ccMTD8jYLnqnjtQw=,tag:h6OqeYTs9ZGkUXtiP+lc8A==,type:str]
  GROUPME_TOKEN: ENC[AES256_GCM,data:ZzuyZ2MeHtU3/91uUm9HEBeVuizYvQLvT2t/XTTT//9/kupK1HbALg==,iv:E7lrWa+fi0kPRVaCFSHnaG5eKRChabCL3G4LlFBb8wA=,tag:pM2N/QGIDR2athzueQBSwg==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraDRjRmsvREljMHQwcjJa
        bWIvRDV0VWdvN0NRL08vdUxRMkwwdDRZMUFjCnVKTEp1WEY3b1oyWmo1aG9LVCtv
        RmdmK09LOW5MSk5kbTJsUFFjdi92SDgKLS0tIHRPVDFpWll4eWdhZXNDVGxyZ2tU
        a2d5bmRyTTA5MHFCeldMNnQ4QmNQcjAKYBs5FrjpbCivLSZX+rDaAfMudb4XKiKh
        coLoT16VB4cVmeel1EoPbA23iCXo4v6RDltLO0j2tPn0kyhe5raO+Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SkRzWlE1VDFJWFF6N1Er
        aWNrQnBvVm9SOVJXSlA5Q3dDc0YrYVUvWVcwCndxNG52ZjMxWWk4Z2xzZzhablA2
        UFhrWXZ5clpEcW9OcEJ1TU83elNRdVUKLS0tIG9BWTF6MGJzQlpieFVhc2FVVlRX
        RGR5TjFtS1lTaktNQlJKb1NNSmU2M0EKHLpsnV8K1U7/pPmOrWYm7tVXXj4mXFTj
        Fi/W/X2Q3z6mKBHGVqXLZELkL2Hp5aHDz4LCCYBDe2x3gNpu+puFNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T17:29:27Z"
  mac: ENC[AES256_GCM,data:oPFzNoqVamjrHxJi4cadxejMbiUrCSTHDphl1+rRv+VNMjB0H2YnbQfHS7uHPE3P1oizFtGPx+QS0LVCy19yqGyWTf18hVzB2ckK1Lyi3vPKEFRg57e+eyiEdOwxnlWfjtpefZbvnDzl9AAgjbnjb2Ip+Dg65VC/iacpMi7hjDk=,iv:splmmRDqK1MhvDGKukh9giI452TjLDOdssFcY+j/u9A=,tag:gChfyolzBmNMmxjvKNGYKw==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:39Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ/+LyEoiM85aN6Cqd5RGioCk7UXkyBOjj6UMlN2kfOz38PP
        FVXH1boZjD58N15glF5lyok0bJbLtyvESrc+29wvyDhQQDrHEo4Mpn6UpS2BU8Sg
        III5IG2so4B7+gI2H80rU9b1o8Y+R8j/hdn7/TCVMivz4W/wAz2WFddMK8osmSRH
        EnfzmsF4ubSokh9zUOXnq0innYIXiFq8KKFmJsTs5MGgzlOsH1PJwiVZlcIhHXj9
        g0C+jaUL0eCRD7g6UoMnG3y65fLBkv2XIztKnZEGi8LGyy7Y0r/n32xKOGCLJdP9
        tEJjYAV5cn8RpY8S0bR60VNnVwN76Q+2wgkWv4C4m41Y1fwRLcn9ekes0+J8Ja9i
        OdVSEvhz1mu0U483EoJ5U0ouzkn2Gfx3E0VcQTTcQJw/ZV8rN/hdORhmCIqJptcG
        XbYNQsP6iBPpyodfEcSnPoJrbt0H+27Xc8t4sL5O1m7qcyMU8EVujsQ8C1ouUy6E
        LYosGEbk/8CfD1jpwL/qrtNPwqx6o/uXxYSvkPtael+4ZSOaKWlaD9KRGX5SE+qc
        btdlpUqunM37wBcLOcIbTSDCmHtIImnm8Y4jLA+SVxF7PTtjEDqP0gy8uA0xfjYh
        g4Y1h86cBvTU7GD1v/zeIccB1HIizZ2XPdaXVHSNx3v82fPzk13pCc0Nyl/od4TS
        XAElP/VjKNoW/IsIhJilMJApou9vxu4/wexwKtOhpuZR0oAGmWZ6ee/F7pI1SsAi
        tWPH+jyt9tJsiVM2GABrJPwTEmKfraqSqBJYVnH3KI4biK03Ykfn07zZkaap
        =6SPp
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:39Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAx9zxIup25w+9bkGv/ZzEGb042hCcLGLftUBsk1g2XHMJ
        4da6SAApU8UBcn31UUESMckt50ghMa/b8PobdBCPwxT/Tcnm5ESf93yKyk2oSxXz
        d8XPEIyR8XQ96ozsZsR6OyQbfd5UkkBKBhpdU/0HypfqcTLoLwIX+p0vsQ73gloz
        IBVB9hvzCGLEL+HrtxOE/q7S9NW4m6K9np5SlNsrJ1kUxCv9EBPsJR4iKU9jxHFY
        SF6rLKhujypNw4nxe8fMsJ99dfYJxpegYN3Z06fYyzBcvCQfK9jQqURns1c0l7A9
        Rp5PQZASIaNqCT5Fn1gqOgz1erqolQVBrdeecJlvP0/NkzNOudDovxEysayTI1Jo
        BQQofccREl2kmzE0xL3ayxb4Yscht3B0NC6PcI3uYSTAa2HqVqm726/mFooqPA33
        DYjE7kDGRULAShmodj2BpZGnbzGfMOIPLjdkumsBQ+J35bGUU0d7+RYfEPPEJwhT
        gLeLGVpHEsQXiKXQc2hwEir+ZytOWvcNiYBu2vGGGUPIznyHCmdWYfSGmn0rZUOR
        DDN2HNjTMRw0pkoo3a61aIRW8Gtgg/3u5c/560TLkuCxA2waCrvUI6YkHfbau5KE
        6wiJJuMI38L1UUrJrL/EMNIJY3dqV9RmnY8vy2uF0mwc7BQYGG8ldip51uk8q/fS
        XAGEFC2gOLHgyJVUy9/3XMm2XblGXzricbVCFKjdkafK/feSisMLJvqfGudsbxyq
        6l9/lvST6JlNuWIg63bTTs8MgYlRxD9ZXuEorkJorYGdvfy3di25xG0SpX52
        =p1Il
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
