apiVersion: v1
kind: Secret
metadata:
  name: kumo-dkim-secrets
  namespace: email
type: Opaque
stringData:
  cluster.key: ENC[AES256_GCM,data:ZMRF/vCD11NcHl7xHveI1APh0KGwFGPVPWQ/JJsRg/s0UEA2vtYc/Y89n9ahoOPecwH71NagrwEBfkpxTtogAoV5ihedIzvLTCnan6jU7RH0nAPQVbWVEcoY8rybOSBAl63CIVfEnaDfbQAJUKycf5ZcQztdaGAR0gb0xt6q/St3NmC3eG8F9DB7Ohd8LGkuKmlmtTO3fIy2ypWKBAXKXJvWO+ifOv2nBHlwSFsL3qKcGsmo8akxaPKMXhdqAJfjIJFhUZ32t09HBT4HuNA4TUFjvLYbDqv6OLxiN3zqoRt0L8CVqyCxTEwv2MVOwEvMLL7OhFVEZ8tO2rmLB6kgNr4i2piesOh6FRAw9lyKyJqPJAiceOhTov2PlL+OVmjTRDTcWlwp1piCctXrrcfytPxyvtBYB2wvHiGnyNfiWSPJGs9++7ywOIuM7LDy2FK9X+nyiLOxCWk54u0ZTpLKCoEsSFEOui1+lqCUSvzWDsrNzTgP9V994nXtTg8Gx70p1JWU+5FLMe2sl1o0aQYXqfJwlcN8F0hNAQ5AHybViHDpkluVPX7PImZZm6LJ8V/sbda4dxRQro860Xpj8NJH/XCVr008KgKWCv1NpBXUhWQkwQ3X4xM0KT2JHW5Uf60B3x/epw/YCrJ+Ps3d8fTDMLSjtd642LTgg3cHVww6EMln63xa8fXP2EBIgRssCxBEYl9JpvhGL2vCiaJGKy4236ftV1+HY0pAiRmkJapsZttYOqWWPVE09irpRMbHl4SR/T7mw3mNoEHNFpw2QN5IObXblBuLIMKiY96MGo+haY6445wXZmbyP8IZ1ZuYh9zxfwfEePGXlBLsAeyy8vDxt/amYzkvB/2FGZEyQzAEGkhNhSqxVL+ifF8u2gkQBNs3w5WttnqQkf84LGB0ixAOWgQIRP+U6cr6PX06BpVjBBHw1pmN0aR21pH6J1U1Zry4CpmtlKocDdDbH9Nj+UbIRTMNZfBCvR0pqp72H9wy3pcuw/ql/HBRpzSOm9FMzxuvFIgtm7aq5VDrW8u+ooK9zdtCCbC9MB9AIbYMfZYxLt1vXzjykXVQ0PvRDyTq+NHSemYXmVZphSjJexmjpOH9E0A+gXiyC9YLYEPil0qekxdZa3EEZaz2fmh0hH0dTAEXx0A5dndiLFv+nbCTkVdGxJvjavGE4s4=,iv:GTSlDHDkyVsNn3xNsSnaughM4e7sDZYdgKHNvCFPQfg=,tag:XlRIRoYWDD0fzQoJngaolg==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dGs2ejJiNG1NLzd0cGtJ
        VndGMHpoTFR0dC9NM2FKNTJsbzRXUEVRMnhVCldFcDlnbVBZM2l3OFdMelE2MnYy
        ZmlLWkpXcm5MQWNHamRZWm1WN0pxY0kKLS0tIGtTMGlQUERKVDhLSGF6REtXODVB
        TXI1cFpvRnVzSmM4ajVlbDczM1o4YjgKcLY2kjUf11w1Ehqrdbqs1WoBrRAMGymz
        Ht2JopC5hmASk36CIO8g1qCFBxVGuGDd+xCIdGdVyIJjkWCExL/y3A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUWtkbGdzd1VTVWZraGNu
        Ly9QdzgyQzB4WTVETE9CM1RZc2VZTkQvQUFjCktzOVJ6N0Z4K1lwanJXVktOU0R1
        R2hITEM2Z1pmeWJJQ043WlJvT3g1a0UKLS0tIEJOU1dYdld3REprK3ljVHFJVEVh
        YnRiSGgwM2l4ekFiL1d4UWd2aDFybEUKbJKU0j9bNfk5zXQtIMb4Y3fFyXp8Kxfa
        v/GV4UntyJbJ/clgT9D5AM9NGSbL5I78B96/o+35pEfmQyiOvpci9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-17T05:45:31Z"
  mac: ENC[AES256_GCM,data:f1DvfbDwiESLm838izNcXQMal39JdgVtzHp+2AtDmk1h9lXJpN9wUNzylHZI0eJ8CR5ZS1ERGk7hbr8pbGk2I+rpKlYRVfq/jcLm+XyAHYyvTVtvPKA4z8gpNQ4yxaGBEbD9NqcIc0L6fwnXhAhKVn4ydhqCjXyEQCFHD0q2v2A=,iv:u230KioBMXIT0qXoqQ6Lom4X/Yx2wKOVwlxyup1tCj0=,tag:pjY5aPu6qxJTCtCLh6eN5Q==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:41Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ/9FzcN/xk/oQmRL+kj7Oi1SQ3Fxt2HvZQN+d0E0B4xW6TS
        /S2b9UEfB8msI/gf1U/b0siiqErq4DawOR+upt48BmBhRulSfEAStVtvedSnltiy
        j9DP/YY1vpkiArX+JkERPW8H3nENKoN4MH45O1dAiila3NkTbCNCKmnyKPHbiXal
        FguirE8ZWhz77/6jDErs6JgLzer7Zl5QfFGOK1IgK3YO80MF6unqzOt1rfCMFyFN
        rnzO0ZJJEOg+Rvpym0OqVYyHIiPvV92Fj/C9n5PXuM3aXnfydX9AAAruXmtPeIma
        HgMjQSQbbjr3/bUjPhirHc/FCH+qs0t9twHY98z2NjL7OIAaHHoA99qWV1VIYmGK
        ZKYXmMaK6EJNeM/FVeJqeCyo4yIm9cTOE/53V3Vf6B8imGuLZQQqjbSW6qS5RznE
        d+yd2sjoBMgGbXNfPiugIMDwS+pEhDdCbVDyCJRSqMmUuYdFN24exmt29l5zxcVu
        cA3mm/yso4bAWUlV7Yfw7k0uZFpD5935z+sFkguBVn+izaKjyMAl77cs+aqU21f9
        1kopZs99EtipU/YtQdlKbodq/GcIVYWcMlI4phCLL6w5Q6QdupepzI8HpVB5cqMA
        9yh+AMG5Ssw6xnYyb2jUs9JzZrJpWvFZ3gw/c/bGD8qKZS9kSTHrLyLV+paKCvHS
        XAGpBnLzMEE5sVKYTKB3lVXHpM9GseESB8OKMc2EUmQrlmlFF+x4EX60gXgEwhll
        NNRuGBESwlza0CffQlk9lem7EeL9U6jxMxS7lKmmMSYG7Vy0KY9pJ8HLe2pD
        =Wbp4
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:41Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAArOV145NNADoaCJ5nY6u7TeJdGKjMyJ5lGCDrOslKXSCU
        2YRn8ZQmDBIWP10DxKmaVrzOaPpQChswwg60Pf48SdOyjJnGhbxaVDWnyGJXD4kz
        e+VqZXKGRNSEyJG/QM3KD28pe6iHgaSdMq62mzBVOR2z623ktgq1Bwi99KyqPzxB
        m5KjVIVd31ePHBwCHkbkoVMI71PIgVW9THR6OG8SUGvUiK5yDMVCAuqTVX3DoIVa
        FP3N5ttIW7XSN8cGR10cc5Q5qC6bug5wh4t4A9DdYnP4udw3uI1p5C2RIg85hmUF
        tnJtClb+B1TKSMODj9z5eewJGTeI96KIBy0y5c6DxIaBJcGCGzaYiIgIiwuU1IR4
        RY/elHr5zlpskzih+snv1ZnK70wTCfID/9q1c8wnVwV5YStIsioLr4Rf85BcY4mg
        VWZCwEOBY7VXfdLV8Ri5CXBeHy5LjJ1Qt3CqFeBNdUTPg4TOhsx7Ghe6hd89fHws
        tFfBGZqgPnq+fB5sYls7cIWy3RtcAk3oXfhgWczjhFAV+i9JDj96j2M7adI3Ofdc
        /QiAlcivqhwbreSajYmjfMk2bvreDOoReAZonn2nOltlz0ZB79k3e5gAO6M/Raxh
        ULWUju03L5AQ5+ER9EPZRFAYcG6uoWDWJZiSRZw7uIEPPSgS6oF4OprbMQTE0m3S
        XAGEqy9ENmCmBx3NdyC90ydu1jk6D9JZdxIUx32qSOK0zSlmomh4MupJ06Qmgx0N
        D9K0gv4gEcnFecvIZmIKAau+OqGTkr06qfuIs3yWd9k4DOpvxtbqP+0rRYy6
        =bGGE
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
