apiVersion: v1
kind: Secret
metadata:
  name: kumo-dkim-secrets
  namespace: email
type: Opaque
stringData:
  cluster.key: ENC[AES256_GCM,data:ZMRF/vCD11NcHl7xHveI1APh0KGwFGPVPWQ/JJsRg/s0UEA2vtYc/Y89n9ahoOPecwH71NagrwEBfkpxTtogAoV5ihedIzvLTCnan6jU7RH0nAPQVbWVEcoY8rybOSBAl63CIVfEnaDfbQAJUKycf5ZcQztdaGAR0gb0xt6q/St3NmC3eG8F9DB7Ohd8LGkuKmlmtTO3fIy2ypWKBAXKXJvWO+ifOv2nBHlwSFsL3qKcGsmo8akxaPKMXhdqAJfjIJFhUZ32t09HBT4HuNA4TUFjvLYbDqv6OLxiN3zqoRt0L8CVqyCxTEwv2MVOwEvMLL7OhFVEZ8tO2rmLB6kgNr4i2piesOh6FRAw9lyKyJqPJAiceOhTov2PlL+OVmjTRDTcWlwp1piCctXrrcfytPxyvtBYB2wvHiGnyNfiWSPJGs9++7ywOIuM7LDy2FK9X+nyiLOxCWk54u0ZTpLKCoEsSFEOui1+lqCUSvzWDsrNzTgP9V994nXtTg8Gx70p1JWU+5FLMe2sl1o0aQYXqfJwlcN8F0hNAQ5AHybViHDpkluVPX7PImZZm6LJ8V/sbda4dxRQro860Xpj8NJH/XCVr008KgKWCv1NpBXUhWQkwQ3X4xM0KT2JHW5Uf60B3x/epw/YCrJ+Ps3d8fTDMLSjtd642LTgg3cHVww6EMln63xa8fXP2EBIgRssCxBEYl9JpvhGL2vCiaJGKy4236ftV1+HY0pAiRmkJapsZttYOqWWPVE09irpRMbHl4SR/T7mw3mNoEHNFpw2QN5IObXblBuLIMKiY96MGo+haY6445wXZmbyP8IZ1ZuYh9zxfwfEePGXlBLsAeyy8vDxt/amYzkvB/2FGZEyQzAEGkhNhSqxVL+ifF8u2gkQBNs3w5WttnqQkf84LGB0ixAOWgQIRP+U6cr6PX06BpVjBBHw1pmN0aR21pH6J1U1Zry4CpmtlKocDdDbH9Nj+UbIRTMNZfBCvR0pqp72H9wy3pcuw/ql/HBRpzSOm9FMzxuvFIgtm7aq5VDrW8u+ooK9zdtCCbC9MB9AIbYMfZYxLt1vXzjykXVQ0PvRDyTq+NHSemYXmVZphSjJexmjpOH9E0A+gXiyC9YLYEPil0qekxdZa3EEZaz2fmh0hH0dTAEXx0A5dndiLFv+nbCTkVdGxJvjavGE4s4=,iv:GTSlDHDkyVsNn3xNsSnaughM4e7sDZYdgKHNvCFPQfg=,tag:XlRIRoYWDD0fzQoJngaolg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-02-17T05:45:31Z"
  mac: ENC[AES256_GCM,data:f1DvfbDwiESLm838izNcXQMal39JdgVtzHp+2AtDmk1h9lXJpN9wUNzylHZI0eJ8CR5ZS1ERGk7hbr8pbGk2I+rpKlYRVfq/jcLm+XyAHYyvTVtvPKA4z8gpNQ4yxaGBEbD9NqcIc0L6fwnXhAhKVn4ydhqCjXyEQCFHD0q2v2A=,iv:u230KioBMXIT0qXoqQ6Lom4X/Yx2wKOVwlxyup1tCj0=,tag:pjY5aPu6qxJTCtCLh6eN5Q==,type:str]
  pgp:
    - created_at: "2025-02-18T03:13:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAwAAAAAAAAAAAQ/9FgVEfzWJtMO34zDU1h561PN8Jz3HJgQ+JnNLF0BrbwUa
        4VM/9JNl4TX7pvZTeVSIwYQGTC/WoVYMIXQ9u8IPc6EgMZZ2qfwkSjwQ4Ghld3Nm
        /eWbGKUTVeDLnk3GuJejxUmyQr+3Mz9/GGAeWJseQ/ozU0kAPM8jVG/s0vlkCOP2
        Hrc68T+r828APelKb6zQEtIiBc29jVUmQ8b8tcZzX59zrsRGMGJaQpq20iTLuKZg
        0oTePzeCDVCyUNsOwgxkXo9teAlxEBTjFsjS+kB03vxEkVIVVfpqrAUu6ti06gji
        RrFpzxtanRc7sgT+mRLvFnggpkJTAtcGdAOWOvAyBdKFSS/+nZoy5m8NwiCaigv6
        TEFoibPpefm2ilvrWgiZQneXd6utpI1BD8MiTCxShZirU/rpDa5BeFJ+uumgVYuB
        h+D+BKZc1mtt+nfnkftyQf9L9mnnejGmVNWDjIKaQUFOE7k6MbWPwc03RbMChabl
        RiYNgssp8WRG+uhAryXky/csCIniquloxgG3fcEuUpUkKmbhfvLSibPm6LtkNXrb
        P1muuG8T0/idlH+g+qhu/xVYU3vCaMlVc3VOTl798jDUH4mm0C8+EGBBCzUm2a72
        s/NApVOMr+vzpHduh0dembpHZRqTAFsfH2yGRfvLIA8Dw6fyEgWRz7boNlnkA17U
        aAEJAhBxkNqXnThFUTWGZ/YVZSpMPbmVhpsqRJbKLcGxObjT1aZX2C355ZfCffhB
        2fQfZbuOcw/H6A7CcV8KESqZ6oCc87FaiQdkiQIEWaX2lQ+jLbtPb8y2h0rpwFkq
        gpfsto09wRQJ
        =eRkV
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2025-02-18T03:13:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAwAAAAAAAAAAAQ/9ESxXL1bRVt2izIZjHmiW22m+KfXlQxWcOpFg4BvlioFs
        YY+YadGIYpYIpGZ6Q6fWM152bXLil480n2hM8sd8l6K8nJTbYojd1DgjekvXfXgQ
        vXoj4t5GzugUo2wn/4NzEoeK2NYavgBboWp1jEEETToOtuJZSiLNCkevKxs6C/n5
        cTDcHPdnC7Gz6aAj1Qm3WdDFTuXJI/WReCpH6rAywRC/7rIet6093spvKENufkQV
        IomuOA5FJTWDCR8ipsJHj5pnhc44Mdt8R2DbiO0jK+2HhHWKpvZou77BCqkFZmah
        M6ODS96lqm37YGxZvo3ahrnelzhr0A8Qyj4oFyT5DHuPwbhOAc3y4Zy+VxrLrI+m
        LR6Zi0yiOqQLM+prFNKHK7MnBnKXpvHAwSVtDlgiDj9Cs7OTVEPjoOYB2M/BI/pJ
        y0ILXUbe/0jrNpm7Zk1ulavt0LGdJ/vPzrut9Ew3Id6H4tg2/PiEfc2gJnJ4Qwun
        WugDg9vrGPMVp+XSRUq2QmHN3J1RvPKn5C5AaRE7e4tF6k7lIxi8+P+fjwUbgOMK
        pZ9MObVm1EzpcgxzFYn0InaM7FKZw7g5pkDXiT2lNkFm5Qch6Qq81XgTobSv6e6f
        A1O8Be7D9Cxos0HMwIe58D1Cm3ICP/jR59/HCqHM5HNSBmOoCT4fhwvNfdMBeiPS
        XgHlt9KxKZD5RlBwVMuOGf6lWuRewswdMVvyPTaF1tMV7rqH4+4GgC5dUE58HR3J
        Z0Z3B7EyxWdcrr2n38liequi9f2BwLJmxSlhWP7eHsBozw6Sc4PX2gu5RErrLHY=
        =QVGr
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
