apiVersion: v1
kind: Secret
metadata:
  name: kumo-dkim-secrets
  namespace: email
type: Opaque
stringData:
  cluster.key: ENC[AES256_GCM,data:ZMRF/vCD11NcHl7xHveI1APh0KGwFGPVPWQ/JJsRg/s0UEA2vtYc/Y89n9ahoOPecwH71NagrwEBfkpxTtogAoV5ihedIzvLTCnan6jU7RH0nAPQVbWVEcoY8rybOSBAl63CIVfEnaDfbQAJUKycf5ZcQztdaGAR0gb0xt6q/St3NmC3eG8F9DB7Ohd8LGkuKmlmtTO3fIy2ypWKBAXKXJvWO+ifOv2nBHlwSFsL3qKcGsmo8akxaPKMXhdqAJfjIJFhUZ32t09HBT4HuNA4TUFjvLYbDqv6OLxiN3zqoRt0L8CVqyCxTEwv2MVOwEvMLL7OhFVEZ8tO2rmLB6kgNr4i2piesOh6FRAw9lyKyJqPJAiceOhTov2PlL+OVmjTRDTcWlwp1piCctXrrcfytPxyvtBYB2wvHiGnyNfiWSPJGs9++7ywOIuM7LDy2FK9X+nyiLOxCWk54u0ZTpLKCoEsSFEOui1+lqCUSvzWDsrNzTgP9V994nXtTg8Gx70p1JWU+5FLMe2sl1o0aQYXqfJwlcN8F0hNAQ5AHybViHDpkluVPX7PImZZm6LJ8V/sbda4dxRQro860Xpj8NJH/XCVr008KgKWCv1NpBXUhWQkwQ3X4xM0KT2JHW5Uf60B3x/epw/YCrJ+Ps3d8fTDMLSjtd642LTgg3cHVww6EMln63xa8fXP2EBIgRssCxBEYl9JpvhGL2vCiaJGKy4236ftV1+HY0pAiRmkJapsZttYOqWWPVE09irpRMbHl4SR/T7mw3mNoEHNFpw2QN5IObXblBuLIMKiY96MGo+haY6445wXZmbyP8IZ1ZuYh9zxfwfEePGXlBLsAeyy8vDxt/amYzkvB/2FGZEyQzAEGkhNhSqxVL+ifF8u2gkQBNs3w5WttnqQkf84LGB0ixAOWgQIRP+U6cr6PX06BpVjBBHw1pmN0aR21pH6J1U1Zry4CpmtlKocDdDbH9Nj+UbIRTMNZfBCvR0pqp72H9wy3pcuw/ql/HBRpzSOm9FMzxuvFIgtm7aq5VDrW8u+ooK9zdtCCbC9MB9AIbYMfZYxLt1vXzjykXVQ0PvRDyTq+NHSemYXmVZphSjJexmjpOH9E0A+gXiyC9YLYEPil0qekxdZa3EEZaz2fmh0hH0dTAEXx0A5dndiLFv+nbCTkVdGxJvjavGE4s4=,iv:GTSlDHDkyVsNn3xNsSnaughM4e7sDZYdgKHNvCFPQfg=,tag:XlRIRoYWDD0fzQoJngaolg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbDdRYWYwaXpKTVQxSkVK
        a3BCQW82T1BGRUlaOEljR1pGQTVFaE5PbVF3CkQrVXcrVXhhaERVdTd6UkxvbU9H
        cUF1T1MxbGxmRU1MR3BuLzhuRno1OE0KLS0tIGppc29uSTlBT1Boa0k4M3RMRnAw
        SVByb0orQ1JuVHZSY210c0xZMGxLTXMKVWtJgLkCvwg2wTABNIPEvMX+9FhpDU0Z
        2T7Cuq7j1CkUEK5sfyEf/QY3032zlL6AIdP61B+GcywVDGZmz9LYOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTC9Cb0gveHZVSDJTeDRi
        aHQrSjhFUWpCRDRFWUZiS3BlSnlseWhQYVNnCnRiTzBLczdxSVF6TzRqZWc3OE1O
        NWkySUsxOGVxS1RIM1MyU01jWmxsalEKLS0tIFRXMnNxMFFxd0lYZ00rNDJ5NExl
        Vmx2QTdnWHhaeGpDRm15dG1qd3FFeUkKoLTcpTY2+XA2VmDcd7ESbdW0bhumeF1T
        09AuAsszWPHpXk3y5T3O1/dk2g0AxxERX7PhncyBFuVnrEjQWYoqSA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-02-17T05:45:31Z"
  mac: ENC[AES256_GCM,data:f1DvfbDwiESLm838izNcXQMal39JdgVtzHp+2AtDmk1h9lXJpN9wUNzylHZI0eJ8CR5ZS1ERGk7hbr8pbGk2I+rpKlYRVfq/jcLm+XyAHYyvTVtvPKA4z8gpNQ4yxaGBEbD9NqcIc0L6fwnXhAhKVn4ydhqCjXyEQCFHD0q2v2A=,iv:u230KioBMXIT0qXoqQ6Lom4X/Yx2wKOVwlxyup1tCj0=,tag:pjY5aPu6qxJTCtCLh6eN5Q==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//REA4SHo92D+OFTGwNrYXBXG2zc9w4FbTQCoBiLOA2XQS
        0Lo4ObF98M8bKp2tSgcIVgixux9zSenZScwqzwpYvoDaFejSrGmPOlMBOy/KXGHU
        mnMd/x7zCr8ydveL7AETRUcQTMPGvNRbxcoeUM1qcrh3x2YhOpW+2rdonvoAY9t7
        mEFUmys4r0MUTwG53RS7wdTJBjXg9HuxtIrY/LitZGVzdtgTVBV59IazXEcxVmUG
        4V0U05rMEK/SQsYQL5m3aM8woe3S+gBcdVoKV3OeypWjIHoBk+JDg0u3beUdzZ/O
        EkYizVaJfhQljqIg31WEKGJ+z7zxzarWC0/zQzbUnKbDS88Vk1ecJn9wy+vAKZgX
        spkLE6zWq9Y962QOpUz6VkUKUXnVh/qXi5OR4n5+r0npAjOBSC5V4P6qvFTaUsoX
        8llYLp9GfKIIjOwJjeHM38qdn9R1j5hUCaz4z225x/6tUJGdsCFO7BBp+8+UmeHL
        WCuSrqLJHxsBfFDW6RHzNgQujLYVllZgh+t+ulcaU6RHSKW+3LnAGknExeok46G5
        FOY3vhgUmC+ip4U294NJUzfM8HV47zUol3tvpxmRcnqvP0O3u+yyMeVw04iD8JHG
        t6k/qkziFYum0KgU9mpxzbDj0jWZvHVTAnSYWhhlImKlLGQ8CCcgjEd0/XlnkcLS
        XAFKiPIih86BeLozZ93wVa/ms/bY9GJuOFHFLBOQS0eqXRKLueuw+LRhq06NVaoR
        OtEjebvST5VpG8+JdQ3S8ybdwDMabC8xpQ5H/CSLXrw3z/MQAfOP8Q0nUCe0
        =FxPN
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAhltFBV4yZ/chu9CHhJ+Ik5FMam2Ixo5wGELSLgI9WRJh
        t9XJe15/Rxyg8WqrONp78FE17kcVWcsNfsmBajPRY0R/4hpmlKMI4HL39zA1W4Ta
        DleoNVXtZOkJDwxwK+9HjxD5CjFvmj0HpB7sNQF2X3HPGNJvPzcS162eDOQnTdb5
        xATcuTDlzn3mcnAUO7B4IkeW1C50AmhV6Mb9A64xMgLzKP+51np6Rw55Yza1vbl9
        9Qr0/iEWFvP2UVd1hCbxGFEdJwrSl52HRCK6o3qv/U2tP2zryrOhjaUqLIuqcLX6
        aZGugKBeFZLWaw/f3qeFzZXW98we5RUyhXeH1RemkdKM1mp7XZNGBPwlS7ONkNZj
        Fs78vMEfBFt2ek7VCUJToaTrZoDuRT2AUPc8zTCpC5UAOm/hKWzVYDthtwF7Vk/e
        Ez+wE+zjdFbOvVwQuh/PCLjtajRGvPo2Yx0YgctUQDevYvQMuhGN5tRIWH5JPyKd
        g+/38f35IYFf8ckPEgjo7xZZJ0/caltBH15WkvaeORmwPE2xHYBSzzafQ99bbDq7
        EMY/UC7I5xq32VgrYLz+luQWKeNnsCpmjOqlGx3mVadI03r8jKzZPsvMo1ohGy8y
        7oypEi+FtYCcKqFBRteIyzDlnUu1L3AYZ/GkS+X3rxvHIsp9zpkCxcMh4Lti84XS
        XAFam4c1mEsEMc3+PhDzNkeB1LfvhGIz3AV3E1zYbTaVj/AvuenyCyLbFqIVIXKV
        Crlz/8u3nGFpFFK1O3R5Zl5XEak183wLcc7K0yTatfgn6KE4moo66NQHf25w
        =UZzz
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.9.2
