apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:CHVwnztK+YoRCQ==,iv:F976VC8pFhnL8RxiDgCd8x6sBcyE0ELlpEG1t3F3Jdw=,tag:9R3/cMM9PeXPGG8C1v28CQ==,type:str]
  admin-password: ENC[AES256_GCM,data:VoAVixtivTVFMe7ZULXreg==,iv:XQGjJFS/dw/7wC+aK0GRq1uv8EXwuQ+3xcwxzaesCno=,tag:NYwq1Cri0hxPYS8FCVHP9w==,type:str]
  #ENC[AES256_GCM,data:L6B2Xfzhcaz+8O5pFks=,iv:8NuZnk2KYIq5cvLlX3I+iSWrzY0YCjQjlBr1t49zJBE=,tag:pmyXP8SIScQoNoSRK6B7+A==,type:comment]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNXYxc21YMkhFRDl4Vmkx
        dE50YmxWbmRreFJQVkZXUzJLSkpWUzYwb0NJCkJWYWhLU1IzcURYNFBQZDdqZGVn
        bWpuMWtiekIwNTNTNDdWN2FiTTR1ODgKLS0tIHVFOFRwbUJ6Z2NpanlqaXZzUzR1
        b1hFTHdhY3ZhdkFqd2xLWFBXOWFsNGsKa8DRpG5XWMd/Vyk1FAAou36K3J7rgHf6
        t6qTe7Jgb1+esmLxrUR01oRMaUFN7lozagK47arF6IlrDVpgQ7995Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ3hQdjcrdUJSR3dWRngx
        NTY1QmF6MnppVVlGeGFQVXczeHZZaU9JTkFVCkd3cHE0dFZKRFk1Q1BMaVA3Rk5v
        dHd5dzF3WUdITUliMGxXRzhTNm1xZkkKLS0tIDdkZU9oVXc3bDZaRVZFRWtYWHN2
        cXovVG00REhkM1JkTjNnODNyM2dFYUEKcHaO7hJjwet4Dta5BpG/xlM7ejxsEY/u
        lrwjCRHXV7MK/C0vzpudX+QuIfPn0almwngB/hu8BdpevvencjHEQQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-01-12T00:38:39Z"
  mac: ENC[AES256_GCM,data:Bzlt3GDZghs2dBfMU0gL2EtGdC1EhLDj+Wg87eya70c5ebqYUw47k7/qAb33Q4xvbP2cohmjmBz6DSjX02DEmXkUDOJg6TBindrg0rWwxFoVw+i3RbXXP4kMMe44XQ7XHZIbms3gz9gOsvH/q6Zl+7Lk1REBV47TMOs9lZM6XkE=,iv:kwC0hR+RLFOt7BCOm3uCrwWPOJnlW8D3LXe7nrjcVQc=,tag:t0DrIg/gv4SlOy3a2gOsmw==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIARAAnomFkT8IAZBF4b8/m4Q/reOEVqD0GISADm7SpHfL6WE3
        hiDP/Xc4oP8OQEyZp8aJW41DiPr6DVcLD8U7GYMROCB0jmeF5BjVqoIDLmW/X2zz
        t/aN5G082Apt640gklQTNfDFL0xEgdKfLaVMymTWNf59wET5Nw5dTmioEPp9kZMG
        ATcPWKYflMZAjwbRh7pO9rujXdvfy7NZXH7ZZetSLwEx/pdJQVfTmnU/cMMroeqk
        memaNlrGKiZz3wmauJ/T4Xi5s/VYYMRPCsuc6Ej+8sFoUlnjrOq7ENhhfqVBTf11
        HutNF6DC+kRDD9Pfxkmxq2ZLw2/rOpAY7xRrvXJKKUqNGOOheYP2AzGQgOggNzH6
        stuxslMHcwHcAdRcx9VaPUarzQr0n2vHe0kTRMkKXVhm8gCM+/0xk8Ilb6fpMCHq
        tEIgVXN65r3zocrnKTtRWsNQYZqpPXoQ8wjTr1OGZL0yVG8ZCikZ30FCBZK++HGx
        FjNkVUNmLmJrT+KhGVHiIBEKvIVQ4PsfAhiQ666Ycg+Eo4vegYL2Qo7cBbAbMmQY
        WvPJ0ApdAywc2ToIbv84zaIEH7yH/4kbE4YWdYLFCLBY5nJ3wXLzkYuUXQ6eZ6ov
        sHC/Q3A9geXyXHqa3si1tidZJKO6EA6tq/w+NWtqckQ14mW31idZKZ7TDtZ81EDS
        XgGfOPTPLHsOzA2R6YyRdhxzlUVwVhwo/MOIqxi6RmfSuT1/anISoSrceWsqv1OX
        STIZ2HpIqW0sj+TXQzxr0qEDyOL5jBT421Rf+jcSBQ618JJIDYQEPHEhjtej+lU=
        =7Xz9
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ//XIfpTE0oPTVyWAfSZmZLbuml875gCQ1+v7QJhAq0Kdac
        D2Iz5Ytwg3ttS7gN/s77SXHMCp0B+Ga6LWvwWaIYuKTfCD/Z4FuIFCNtVE3djyHh
        2vpNX4AWfVaSBV5qSohkdQ8h+09VEYuhDLzrh02W6OWyDkBhsHcHIbd2O8UyI+27
        Mf4xJ+LNCxQr4nllpOeeabmMJvX0LQJUycUo0snL1mI0EE842Rp8ZpG+f5W5AJEM
        XwDuAvtXQjg8Eb5cNTc99EFzFK+lOmJYVz7ieMAH5gYSWdRHLlvScwtK3wzuQQUX
        q/iRbVZHrLClnndptLIZRC4txl+N3c5omC/UhgFut76bFS0gp1+Foe5R91GWv7jt
        TVCCB7oeR4yyXavrsK399RF7TuGNCOe+pUQXef2PQkbLQ7YpXab0cbdj3u2YAjf8
        8lLBXDBDWsKe2bHTLqpnhD7ZrlgTIH5/2X0zV4XS856WrN4DKxtmQ+RtcYndhtOb
        28IgHP070+b7FoCiSlcIEmEIKLsufMdZ9ont2F9/RG0xh1Hc50Ad6l8Hpb1jRj+4
        0ljS2k4QuzuFSLNobm7TYWPXoKp4K8+B0qD8DER/N83qxG78rlX/XJLjZR4WDf2n
        l5VgtDRE2jDH72vSvqPVlC6i+wh8MGu8taB0iNNWeCw6Ay+cBW0WOLlUCh0g6tvS
        XgHiKQgOzS8221VYJhJ0C/teBO4l8zBMEUBrcyEsJ5i5Z74ds9IE3XO8SEqQieIZ
        fooJaTyCtxuaueuThYjapA5VLL3u5qsYb8tJWbdTJmFVZkmOkgn2wCOIhEDIl3c=
        =VUf9
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.10.2
