apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:CHVwnztK+YoRCQ==,iv:F976VC8pFhnL8RxiDgCd8x6sBcyE0ELlpEG1t3F3Jdw=,tag:9R3/cMM9PeXPGG8C1v28CQ==,type:str]
  admin-password: ENC[AES256_GCM,data:VoAVixtivTVFMe7ZULXreg==,iv:XQGjJFS/dw/7wC+aK0GRq1uv8EXwuQ+3xcwxzaesCno=,tag:NYwq1Cri0hxPYS8FCVHP9w==,type:str]
  #ENC[AES256_GCM,data:L6B2Xfzhcaz+8O5pFks=,iv:8NuZnk2KYIq5cvLlX3I+iSWrzY0YCjQjlBr1t49zJBE=,tag:pmyXP8SIScQoNoSRK6B7+A==,type:comment]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M1Z4eTJTRjNSemFBSzJW
        T05sZ1RTVGsxOGdMa0tWVHJrT3NDWVlZZUhBCkNnTjJZbURCRGtHdHBqSjAyS21T
        Mk9TQmtoWlRDV2J3UkZCZ1BOUFA2d1UKLS0tIFhiSkpKaU13QjZTY3RPWWJsVTNE
        c2l4MXQxYWZxU1ZTK1poWjFWZTdFakEKlkz6hi/8q68JcxiO07pLMelkysvuFgof
        WYUn+Xr7fV49brVlFm7rlx4BOQcKqQnKXN+7cZY6aqtrTkjVjDswAQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQm1Pbkx0R3JzWmJ5TVNL
        czZRK1hla3BYWlV0MjZXTzB6YTY5MXA1RkY4Ck0yZzkwL1Q2UXorSW1DL3pJWmJI
        Y0tlQjdGZEZiK3hTZThXaHlXWEw1SlUKLS0tIEQwZjM2dDZObzhsNnhaNW8wcXlF
        amVxUTNsbzVRcWdvTWNCbmI4KysvQ2sKAQV62n5RoXLWrgvsSVsBFeWW1Fmx6mRI
        6SCzwoATLukBO7MbePRUzPpzpPcEgCHgNSsQTDgd+modre0AFFKC3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T00:38:39Z"
  mac: ENC[AES256_GCM,data:Bzlt3GDZghs2dBfMU0gL2EtGdC1EhLDj+Wg87eya70c5ebqYUw47k7/qAb33Q4xvbP2cohmjmBz6DSjX02DEmXkUDOJg6TBindrg0rWwxFoVw+i3RbXXP4kMMe44XQ7XHZIbms3gz9gOsvH/q6Zl+7Lk1REBV47TMOs9lZM6XkE=,iv:kwC0hR+RLFOt7BCOm3uCrwWPOJnlW8D3LXe7nrjcVQc=,tag:t0DrIg/gv4SlOy3a2gOsmw==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIARAAiCtzaRYstjid8Va6uHwsvHOkFg6dTqD8lrh1+7dWytXL
        e+Gk4AcNHIcfSP5JKvd/HQq3e/LCEsnuxiZuvCirCW6Od/xnz0vywkZ7rPdDt3PS
        t8MLiCYO96/FnbRtNs+r6OqcUl0fPRZtkRRXYIDTLc8mvaJDHQUDsvzfCSVqYn5r
        k734pFOt+Er+RjLuEHpJhgkG7oqVqRpSSVW+5A7oJR8Alb208LkfisMONQZ2Bzmb
        FbyNS8k0ELCcDOxW60FZoa3uYAd92qUNLQe1w3nfFQYmp9EUpART3iG/KuLYEbuQ
        Zjn4bJql647qWqDJ+VsFooEvVuxYikFZzDTUp32tltnjCcPggNPsykGMGa0Qy5Bn
        KSt6A1e67dEUE+8zcLIuB84LBO/hvHG1zBOEmg8a9CvvMCdqDduvSjrpXqj77cvb
        l1bZ7eFExnqlKQ77B7A+TTHToVe+mAEMvCjgtI4zthkOKeF/hAgByb41QDmx6f0n
        +gedmck9PHR32kO1lEMm/UpLa2oWMFKjSqiX6Mbt96Izy6MQM8xfOVn8Juog2I35
        3IB+DRhfxezrI8kUgsS7+Rw3iKqqdqQ7s/rbqzvFChj5jLGhug1zvHsjnW8nHn+/
        zyrW8jbyuRwtfuU2aKk8w0ACXq2Qh7t4OFSUjyhIW+smiN24ilZDgZM155UN0xPS
        XgFoNKziSt9ASwjMltwou4/E1jDiN7FQgRIGy7+9A5bC126snbnurlW/HItelIb2
        ow0f3P22fTIjDrzejFODii/TWEZWJIBJWUOLpIbPYG7YxzBJ7nd24OtZ/2ggbPw=
        =L7FU
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAp4sHTnk5IuuAfkNeB6+hOk+LJqqiUsDky0IpVakUFVEm
        P/xAOn5xHUrzwXofNNxoUnSL9nwwQgOkaUiYIaWQLOlLRDmcZ8Z+M7QFEPX1vGIb
        g5xrME9U8mm1KvWrCIpjQj56zW2bg/yg/B0tyl8FoAUVUGiNVEz8afu44lNsMWaf
        XcDhJXh3tzZF9gCm1xrGWg/d+9YhbKNHFP4w5/iw0/B9Pd+F6LHaop2+mfjvlWRK
        Xz1CFEkPBB9ZM2N80Z7BncLoAE2rxygZH6hMFjFZ3Nc31X4ni496KwU5qYDSOt1I
        HjlQPrgdRZt9evSmII6+XFaV06XkRoYOaB5oAlAucq1euw3/kJVEIFkXPiYU4ByA
        ibOe7oY3Egg8xPxCoH78ikDbADpJZAVvHyUz9gwcJbjRf4usVxG7wn+SkNzSQiYU
        P/ggc+6UxzKg+jqeP+bvEC3SoXc6NH3ScIfLJwebzo/NZAri3tXRopOZZdSNUvLJ
        +blnetbZW6iZfDi5RJlfmuQwsUZTG/jGdX5Hg2pBpt2mNTmyT04PLggpASy4LcOo
        EO9iUR8H3KjnokY/KW8kyQyZ3mEIVSjoHRnYZx8/Ju0lQcyJCJKlfXvFAMCliT4c
        R9hK5USgTC/Tm/sAuLe/RkYlrYedFp7rolfeCphkzzhchhPgd13DqNOnJXboqXXS
        XgHIWbBUUGqiuoAz27kv5qXH65885aeu0eWh+QQDfn1Afu0kZJuEEFx5TgAPfBXg
        fX2JqOO2xUZFqb6SDwNSQYmwViZ5POQgnESbx34il/pktLq40nS8j9YC7B7Ubtg=
        =DWth
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
