apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: mariadb
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:y/K2hQX+XpwG3bdZ3BaGWZum1jWfYoR9+WiNQpd36FWGXqEXDnbQO0jP6xfBWzXjOo8IHzwQiWpPsEvyozSrbA==,iv:bG/vXhEKsWrZiZgBnHhAGjzbIsVit0EXEjXNuOIzdJA=,tag:+mk9zS0lD/iPQp2VC0qwWg==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RktqV2l1cXptOVA0Nlhm
        OWhmVVJRS3dlNGZReUFmdnEzaDd4YnNCV3dzCk1ZTTdtTzU0R2kwNDBoVjlCd2Na
        NzkvWjNtYjlVRkhleDFlMTB4VFh2NGcKLS0tIDF4UWRwaHdrdzliVTkwRXZoZ1ds
        OHI5NWJXWW5mREgxSjR4M1l5V1lHNkkKl2N0Sy9NJQmtrzzl78WgmlJbGtlLmTAG
        qLildW8qWY46MqHeottEjHQkH2lytLmZETsiYaE7ZMUB88A2XX4faA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM1hsNFA2VitqYU54OTUx
        Z0tscEdBbkJEa2dMWm5GdGl2R3I1STVRRFZBCmNSTUlibjFxYytQUXlhWVpKR2pD
        TFQzNGRoaG1ySnFaUkhjWGlnT0VTY2sKLS0tIERDa2VwMmE3WnNIaGNLdFVZais0
        Qm9UTjJ3bHZoUG8xd2pIaklaMDRBUGcKhY7WlEd944YUyjid++w7dwXwOIc7+AjD
        MlZZZVO8HG2ybD9prhWK379+bwAYytdQbGBokKHZHV6EOabRkiMskA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-24T15:56:46Z"
  mac: ENC[AES256_GCM,data:029fuHuS4yH5Cryoj3ScbS80g62TuuKpod7RTUVdK6Bpq3QMYbuM012bRZ1c5xrwumuNnLIf/0uNJBH9VKIKzFzV9aIZ2hJiMwmvAf6zAnXw3pt8vbd0mhr5dDGlw0f3+3Z49liHqKOkwSRBXXlprK8SQdkcK1HnQqrVDlK1+es=,iv:eD0LnGHlYWYedqXOvTxzJLMMZdA6LfBidtDYOKVcS/I=,tag:NWfOX7pShnGczWz10hd1Hw==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//eJpWPWNKAWPUUCwtNTtU84xaxELMAtCIT+qseMIXmrDe
        DoXyKtgQWPWQfl+36HRyVRhmL6qrhuZDH+cxCDoJoPxsyztqdiEvmKqpJRgNQIN3
        rX1J9OGdL1xaxsZSuo9qoDgPFS60EmBxJzjib7opDFYEIw7XmenmU7tNflft3woY
        CALEUVeeNSsXd62QQ9C7y3M//3jGQtLFBPACJdgixxgCgHB+biTqlM4jGSRlQz1T
        lbLPLVrBMCtrJxvxnWH+A50ZzcFHlYesvGB72FS3TejiCVRi8l2q+NKFTyqoCBPr
        4Sxf2k+JCS5j49LeeYU7+rPzbtyBTeIPvznXRmWNM4k1EZKo11H/EasshHOwOvXA
        J72sFCdpVLhqJATo5tVvxVv0Qx8BZUVT6NGFu3r12Yerh+UFPLTC0ok5kWRGRxw8
        dWyxFGfrvBLrX0dPPGr+IjKHzZA7ikg7Z1O5o/4EgvLMXGCyU2VtY3fsLdntOr2o
        bijr2Budy8ZbQQojyg2CmJBzyVEAdtk3+0MdyPFkrTAMIBwv83f9yH5tXdPTCmTM
        L+9s5HFi4kNSgzlbjzFDYrHnZxWBARi/JqlxYWPUCmJGKM6oZ+YajD1qw/n1napz
        9QcV3AN0AMHYeIsfsyDTrFLHS1zz5qgJlFOA+7GObcd8AQ7Qf10ocjPCnYclEVbS
        XgGWh8UgyYY57W/M/0UcIf2aq35v7p4FP6HRszEgm02VoJ1pIjFuTTB/diouTdMA
        q3xu3ArcSMBkXCbX0Lnhr6Rb9dvphnsypOwY9xEIh7gzVaKRf92n146g1C0p1ZQ=
        =Kn/I
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAApslWGpksgSIrb+PIXnm/hp2S4LAMhA/QPa0TLy3P3ss0
        ZJc4KLW6D899qAtdWoFBH+zbkj3K+vHkOfoGPHN/n0ith56uBch/jz18OYskLhTD
        RgfBx6sXDm28YigsKv1AiXD73DNKJfx/CTkCWCi0kOCkwrZI7yWvDSrOS4rD+2O6
        H+fhOKzHPbMeKPNjwysabuOMvwcp29u23ytKbHTqJe8OdghISaRwqj+9kSaTvpEz
        48J5wKHZyIqvEKuXRsHbgA221VSXKNBC94M2X55rSIRFN5zzkaftk4fHx9PQyJVL
        /Lcj8Eey/9U+PtPGpU2Ge9x7XEfWUES0btuRkkOGMqK48bIqs+81p9vvLBfeaPJm
        VoiPPBkLU8GBQb0TcA3PndStQu47tJsrZomE7vG3QcghknDZZYxlrjQJ0DlE0fGe
        PgB1GxmzTHyVwWVysdlDmHpxhgvUj1p1DhhuvABnlVRJS9/pCTCdvBnhefv9HjQ0
        eq0/d6qFCkm3trzYQF4Ceg/WmTpQCwltngci7mA8f1y5MTPjGArfQWjJ5MQY9HK0
        b/z6KQNY1yVJKKYy3GLITMwi7dNJLfE2i0IL3ABQZTQNdZXzbg1MUfVQxW+uRtMF
        rSt975PtJgj5dVmg08a32VoapCzyh48Ty8gF1hi7R6o3XJj+IK+5Z9l18fYnO/TS
        XgH+nFHpaxApux1PViMiPSG2/IZzMiBN5Bb/tHCzWmVNXCP7WyCEVPm03HDwd71x
        iHINZVvMPk5Aj1ZFRQW+b24g+ODBKNA+lUgnG78z5kK3gdnn+lbDCWba/waBzPc=
        =L6dn
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secrets
  namespace: mariadb
type: Opaque
stringData:
  access-key-id: ENC[AES256_GCM,data:zOi8t/0/raKrw5pJ5rX3G/u/guk0/c9s9lhTAL4gXl8=,iv:0ejB71XW3XEQTmojpNwYtjQ39fWzBhk6NgXZ9qJl2Fo=,tag:T/UQ0yX6syrQ3kx8xn/1VQ==,type:str]
  secret-access-key: ENC[AES256_GCM,data:Fx0xUmaDN/7Xvd2FoefjPm3agFI4izhEEYCN9ooM9sHWxP/fZeSA9rJlBJMtcCHt5/flhQCy7ii3P9lKoSSwQQ==,iv:IvCX7tUcVhJ6DcF6HJC+0Fob6ncHJEuH2KKn8GECeRs=,tag:M+CXfHb2xPKkYjC0AqFr7Q==,type:str]
  cf-token: ENC[AES256_GCM,data:5BfTrGunLRHS4YohvE6t2fDVpbqzx0/eQj6reZLkj7tYIEinM6QQ7Q==,iv:9vyIvheKFnDXXLtGBURJG/s3svZFa7VHSCWf4fdpzsk=,tag:zzILL5rnqcanyQ8OfO4g6Q==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RktqV2l1cXptOVA0Nlhm
        OWhmVVJRS3dlNGZReUFmdnEzaDd4YnNCV3dzCk1ZTTdtTzU0R2kwNDBoVjlCd2Na
        NzkvWjNtYjlVRkhleDFlMTB4VFh2NGcKLS0tIDF4UWRwaHdrdzliVTkwRXZoZ1ds
        OHI5NWJXWW5mREgxSjR4M1l5V1lHNkkKl2N0Sy9NJQmtrzzl78WgmlJbGtlLmTAG
        qLildW8qWY46MqHeottEjHQkH2lytLmZETsiYaE7ZMUB88A2XX4faA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM1hsNFA2VitqYU54OTUx
        Z0tscEdBbkJEa2dMWm5GdGl2R3I1STVRRFZBCmNSTUlibjFxYytQUXlhWVpKR2pD
        TFQzNGRoaG1ySnFaUkhjWGlnT0VTY2sKLS0tIERDa2VwMmE3WnNIaGNLdFVZais0
        Qm9UTjJ3bHZoUG8xd2pIaklaMDRBUGcKhY7WlEd944YUyjid++w7dwXwOIc7+AjD
        MlZZZVO8HG2ybD9prhWK379+bwAYytdQbGBokKHZHV6EOabRkiMskA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-24T15:56:46Z"
  mac: ENC[AES256_GCM,data:029fuHuS4yH5Cryoj3ScbS80g62TuuKpod7RTUVdK6Bpq3QMYbuM012bRZ1c5xrwumuNnLIf/0uNJBH9VKIKzFzV9aIZ2hJiMwmvAf6zAnXw3pt8vbd0mhr5dDGlw0f3+3Z49liHqKOkwSRBXXlprK8SQdkcK1HnQqrVDlK1+es=,iv:eD0LnGHlYWYedqXOvTxzJLMMZdA6LfBidtDYOKVcS/I=,tag:NWfOX7pShnGczWz10hd1Hw==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//eJpWPWNKAWPUUCwtNTtU84xaxELMAtCIT+qseMIXmrDe
        DoXyKtgQWPWQfl+36HRyVRhmL6qrhuZDH+cxCDoJoPxsyztqdiEvmKqpJRgNQIN3
        rX1J9OGdL1xaxsZSuo9qoDgPFS60EmBxJzjib7opDFYEIw7XmenmU7tNflft3woY
        CALEUVeeNSsXd62QQ9C7y3M//3jGQtLFBPACJdgixxgCgHB+biTqlM4jGSRlQz1T
        lbLPLVrBMCtrJxvxnWH+A50ZzcFHlYesvGB72FS3TejiCVRi8l2q+NKFTyqoCBPr
        4Sxf2k+JCS5j49LeeYU7+rPzbtyBTeIPvznXRmWNM4k1EZKo11H/EasshHOwOvXA
        J72sFCdpVLhqJATo5tVvxVv0Qx8BZUVT6NGFu3r12Yerh+UFPLTC0ok5kWRGRxw8
        dWyxFGfrvBLrX0dPPGr+IjKHzZA7ikg7Z1O5o/4EgvLMXGCyU2VtY3fsLdntOr2o
        bijr2Budy8ZbQQojyg2CmJBzyVEAdtk3+0MdyPFkrTAMIBwv83f9yH5tXdPTCmTM
        L+9s5HFi4kNSgzlbjzFDYrHnZxWBARi/JqlxYWPUCmJGKM6oZ+YajD1qw/n1napz
        9QcV3AN0AMHYeIsfsyDTrFLHS1zz5qgJlFOA+7GObcd8AQ7Qf10ocjPCnYclEVbS
        XgGWh8UgyYY57W/M/0UcIf2aq35v7p4FP6HRszEgm02VoJ1pIjFuTTB/diouTdMA
        q3xu3ArcSMBkXCbX0Lnhr6Rb9dvphnsypOwY9xEIh7gzVaKRf92n146g1C0p1ZQ=
        =Kn/I
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAApslWGpksgSIrb+PIXnm/hp2S4LAMhA/QPa0TLy3P3ss0
        ZJc4KLW6D899qAtdWoFBH+zbkj3K+vHkOfoGPHN/n0ith56uBch/jz18OYskLhTD
        RgfBx6sXDm28YigsKv1AiXD73DNKJfx/CTkCWCi0kOCkwrZI7yWvDSrOS4rD+2O6
        H+fhOKzHPbMeKPNjwysabuOMvwcp29u23ytKbHTqJe8OdghISaRwqj+9kSaTvpEz
        48J5wKHZyIqvEKuXRsHbgA221VSXKNBC94M2X55rSIRFN5zzkaftk4fHx9PQyJVL
        /Lcj8Eey/9U+PtPGpU2Ge9x7XEfWUES0btuRkkOGMqK48bIqs+81p9vvLBfeaPJm
        VoiPPBkLU8GBQb0TcA3PndStQu47tJsrZomE7vG3QcghknDZZYxlrjQJ0DlE0fGe
        PgB1GxmzTHyVwWVysdlDmHpxhgvUj1p1DhhuvABnlVRJS9/pCTCdvBnhefv9HjQ0
        eq0/d6qFCkm3trzYQF4Ceg/WmTpQCwltngci7mA8f1y5MTPjGArfQWjJ5MQY9HK0
        b/z6KQNY1yVJKKYy3GLITMwi7dNJLfE2i0IL3ABQZTQNdZXzbg1MUfVQxW+uRtMF
        rSt975PtJgj5dVmg08a32VoapCzyh48Ty8gF1hi7R6o3XJj+IK+5Z9l18fYnO/TS
        XgH+nFHpaxApux1PViMiPSG2/IZzMiBN5Bb/tHCzWmVNXCP7WyCEVPm03HDwd71x
        iHINZVvMPk5Aj1ZFRQW+b24g+ODBKNA+lUgnG78z5kK3gdnn+lbDCWba/waBzPc=
        =L6dn
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
