apiVersion: v1
kind: Secret
metadata:
  name: mautic-secrets
  namespace: mautic
type: Opaque
stringData:
  MAUTIC_DB_PASSWORD: ENC[AES256_GCM,data:/Dtz9qp2MBtLxNqhqsm7Exe7dA2m6jO1IdKwkDid0d302Uiw/VbF3Vik3ui20ZHYL6LCWIL3kSYON3zQbaefmA==,iv:pxVJqM67K2DfWIu6tFHICIL1NL2E16cmWq6mQls2jJw=,tag:VYch6xo93W0oQeOCxxqymw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWVRIWXh5UjN1S1VzWHZJ
        d3E3N0xLTm56WUpqY1VlWFUxN0lDN05NWFJVCnNXRStoNGJsQTVzV0NpMVJLQ05Y
        VWgyb1FNWE5qaEFDRE5JTy96YWpBbWcKLS0tIDI0UmFsYjgzSkVnamJnR01QSU4v
        b0gxWC83cE9xWDBKM2s1UFJNbytYclkK9etqXgdoKwQSC/l6R9aEVqNntisZSKTr
        D1enVpg/QX4yzcNit5BdizveHiDvCKSYylAV5h4gDfIrsGMxn/XMgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbE5xbGxuM1p6eXV1V0E0
        em1RaS9kU015N095b0Jsc1E1aW9yQjNwdVhFCkkveGZ5MTFoSWx0NGppVEtLNXJU
        TW1jcDFkN0RjZVdDQUJNMG1EYm1DMmcKLS0tIG1UbjJTT3MwOGlKQ2VibXZ4OEs4
        REpxT3R5bWxENG51WFRlRlcxeG9hUlUKMvUBt0UDIYFrkQruVpP2VGx0GpC6jTVK
        /7YXGdjS2FCwHn/74t7dXvDaE/0RYEq5ag2GueTX8Dnx8PumSsBX4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-08T18:54:22Z"
  mac: ENC[AES256_GCM,data:vp+xJ6fqX8bxW6KJEyBtaAUv8AUUH42dOnkcx34rJeMHMP2XgbeltkNFasdupf2u2ZXCllDjEQlqAhFPpWq7LowNAEmvQaTMQxOwdn0RY+VoeiHwT0z9+oKcXDRoHQueYu/3a+sIIq7Mw1FwOJ4AKazDYHMzw2lvvy932VfHrsU=,iv:o96NFEj07oUuZu3l1sOacVwwzRi0jqiLalPOavLG3lY=,tag:F9mS5tLQRAxXCYZmCN58Qg==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:45Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//cnCUnBg1xQ0QMPNfCFzKfibrMJ/vXI4cDugLlHIQ+Mnu
        bPARsLgL+yYJK7L21P5QwknNh9dkFCbwPfSsDwranHeNcsr2MsCTUlsIGany6odm
        ebQlWgiYYQnFg/ocp29SnD9eWZPVQkwAgGWXuoNCwhsHGoQJcWxMBTed+oNv0tjB
        yjdFUdVVqKjStOY+ZhhlIu7+rU+Zbd9esbd6zo5Q8JH+sM3kV7Ic8cyaN8FDsOOg
        wckLyBqBTkaL4SoDbv+LqASaHwhEeEGczIm135Ssb6bh78iKf3QmMvkF+IFXEHO4
        7sxkrblzsIpBbS/VkrAoJZgfSn5oytZehBPycRhlL/KCJjXTp1pc33p8mf7ohDhQ
        Y9lz4glIUnxvicFMfjVHTWuCXKfm3KsyPaUPNnJ3z8Xtc7LQU+J+Ufs3TIm9aa6v
        NSzffI3JUYk5dCCY3qMu60PoDf6FEkKT0aYWRDdGyWx0LkoQhuWzVqEkzFW6i0Kf
        d9w3DDmv+bPIxdqOMqC8qQo/E8+pBnMjt7Vu4Qb6HdHEUmOdtHpv1msVW560eqSV
        5Nr69W1D6wEr+mifwyJqJJJ2eUolYVY+svXpT4mChh+PTpNawqjzG660K9VEcfGZ
        WWvwar3XRweLRbL6XAXkvr5cUbEHtl4hZ84IfS/jPpvElBrrYOwRXagPnZ5S9WjS
        XgGzYidGOMpkuVkU1v3mhHnf25AZPwGQ7xYVTNdE42upokxGL4fB8Um3aastajNI
        55mPDJ4Wu9c75twPw+gd1MmEaJ+/UbWqXtR++KPIFi3BpLVxQJdvXh/KVywiyPw=
        =w5ls
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:45Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAsi13i//WcHaaztDnJbDyFwVxzE8SdUkMqwGmuHedHdXO
        KaXKKRvUgz4WcqrCuu/vHEeKz4As6z5iim1KIRpxCfJqHRoF/ulbeT8VL3/tMLhe
        AsTzUoxClMh0oo3A3vRc+5nCIA72I/YbXK/YpdFWxX+1nfiwcApc54v8iGtcwaHj
        M8Y21Ru4+K7dup6pLcQoqG5IX87O+d4M4221q5WeuKsogn3gheqUv9oHwzBA64ei
        oToMugnGriFKf2qa3Anc4tut6DjsgWJopLTwrSXuAfPzD4nMEL01i4mq3WCWxWAH
        /fQg/1awPPNVUL8u3KmYMelBeN/SnLIFirh9inuNQiMRlZn212YAqjL96WX6KMqW
        rUQTvIEd2wA+WdRQU7HI+bsMiGHbhgNHmjKRJf6APrI5ZNMcRhSUdp89dGT51/yp
        ohIZ0dPrv8ccEAuL2bhTzGyRm0P73IKjkdw+se8NMifd8UYSNTs/cC1VURhq2YD/
        uAdCh5UbuhSaDC3pmCRXnO+T9HXlXLnaplKFmHHRCbEEAwlNBAcdDjIO1FsYNogN
        TGrF54gDlBXrGk1ga3WBJ/lY4CvJXetGPk+dAMxchESn5b/qpebStm5pWF31533p
        T8O5K+Ko5SDwY6DAh9LKulyFKkfiF09O68TAjl+vuOdA89tfWbiII3Q2yQyx3mbS
        XgGKd1OtGujFJCulludy3Mtm+n9t9OUtj3z5BiUgN3aS/g/2JM2vcVB/u1xbN6dQ
        ZvccnBCQUiarIVvLg9wBraHcD3O1WRPQHiOnnfbVi6Bi35tYHplapIvWlgk3Gck=
        =YXWd
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: mautic-secrets
  namespace: mariadb-operator
type: Opaque
stringData:
  MAUTIC_DB_PASSWORD: ENC[AES256_GCM,data:/Dtz9qp2MBtLxNqhqsm7Exe7dA2m6jO1IdKwkDid0d302Uiw/VbF3Vik3ui20ZHYL6LCWIL3kSYON3zQbaefmA==,iv:pxVJqM67K2DfWIu6tFHICIL1NL2E16cmWq6mQls2jJw=,tag:VYch6xo93W0oQeOCxxqymw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWVRIWXh5UjN1S1VzWHZJ
        d3E3N0xLTm56WUpqY1VlWFUxN0lDN05NWFJVCnNXRStoNGJsQTVzV0NpMVJLQ05Y
        VWgyb1FNWE5qaEFDRE5JTy96YWpBbWcKLS0tIDI0UmFsYjgzSkVnamJnR01QSU4v
        b0gxWC83cE9xWDBKM2s1UFJNbytYclkK9etqXgdoKwQSC/l6R9aEVqNntisZSKTr
        D1enVpg/QX4yzcNit5BdizveHiDvCKSYylAV5h4gDfIrsGMxn/XMgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbE5xbGxuM1p6eXV1V0E0
        em1RaS9kU015N095b0Jsc1E1aW9yQjNwdVhFCkkveGZ5MTFoSWx0NGppVEtLNXJU
        TW1jcDFkN0RjZVdDQUJNMG1EYm1DMmcKLS0tIG1UbjJTT3MwOGlKQ2VibXZ4OEs4
        REpxT3R5bWxENG51WFRlRlcxeG9hUlUKMvUBt0UDIYFrkQruVpP2VGx0GpC6jTVK
        /7YXGdjS2FCwHn/74t7dXvDaE/0RYEq5ag2GueTX8Dnx8PumSsBX4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-04-08T18:54:22Z"
  mac: ENC[AES256_GCM,data:vp+xJ6fqX8bxW6KJEyBtaAUv8AUUH42dOnkcx34rJeMHMP2XgbeltkNFasdupf2u2ZXCllDjEQlqAhFPpWq7LowNAEmvQaTMQxOwdn0RY+VoeiHwT0z9+oKcXDRoHQueYu/3a+sIIq7Mw1FwOJ4AKazDYHMzw2lvvy932VfHrsU=,iv:o96NFEj07oUuZu3l1sOacVwwzRi0jqiLalPOavLG3lY=,tag:F9mS5tLQRAxXCYZmCN58Qg==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:45Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//cnCUnBg1xQ0QMPNfCFzKfibrMJ/vXI4cDugLlHIQ+Mnu
        bPARsLgL+yYJK7L21P5QwknNh9dkFCbwPfSsDwranHeNcsr2MsCTUlsIGany6odm
        ebQlWgiYYQnFg/ocp29SnD9eWZPVQkwAgGWXuoNCwhsHGoQJcWxMBTed+oNv0tjB
        yjdFUdVVqKjStOY+ZhhlIu7+rU+Zbd9esbd6zo5Q8JH+sM3kV7Ic8cyaN8FDsOOg
        wckLyBqBTkaL4SoDbv+LqASaHwhEeEGczIm135Ssb6bh78iKf3QmMvkF+IFXEHO4
        7sxkrblzsIpBbS/VkrAoJZgfSn5oytZehBPycRhlL/KCJjXTp1pc33p8mf7ohDhQ
        Y9lz4glIUnxvicFMfjVHTWuCXKfm3KsyPaUPNnJ3z8Xtc7LQU+J+Ufs3TIm9aa6v
        NSzffI3JUYk5dCCY3qMu60PoDf6FEkKT0aYWRDdGyWx0LkoQhuWzVqEkzFW6i0Kf
        d9w3DDmv+bPIxdqOMqC8qQo/E8+pBnMjt7Vu4Qb6HdHEUmOdtHpv1msVW560eqSV
        5Nr69W1D6wEr+mifwyJqJJJ2eUolYVY+svXpT4mChh+PTpNawqjzG660K9VEcfGZ
        WWvwar3XRweLRbL6XAXkvr5cUbEHtl4hZ84IfS/jPpvElBrrYOwRXagPnZ5S9WjS
        XgGzYidGOMpkuVkU1v3mhHnf25AZPwGQ7xYVTNdE42upokxGL4fB8Um3aastajNI
        55mPDJ4Wu9c75twPw+gd1MmEaJ+/UbWqXtR++KPIFi3BpLVxQJdvXh/KVywiyPw=
        =w5ls
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:45Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAsi13i//WcHaaztDnJbDyFwVxzE8SdUkMqwGmuHedHdXO
        KaXKKRvUgz4WcqrCuu/vHEeKz4As6z5iim1KIRpxCfJqHRoF/ulbeT8VL3/tMLhe
        AsTzUoxClMh0oo3A3vRc+5nCIA72I/YbXK/YpdFWxX+1nfiwcApc54v8iGtcwaHj
        M8Y21Ru4+K7dup6pLcQoqG5IX87O+d4M4221q5WeuKsogn3gheqUv9oHwzBA64ei
        oToMugnGriFKf2qa3Anc4tut6DjsgWJopLTwrSXuAfPzD4nMEL01i4mq3WCWxWAH
        /fQg/1awPPNVUL8u3KmYMelBeN/SnLIFirh9inuNQiMRlZn212YAqjL96WX6KMqW
        rUQTvIEd2wA+WdRQU7HI+bsMiGHbhgNHmjKRJf6APrI5ZNMcRhSUdp89dGT51/yp
        ohIZ0dPrv8ccEAuL2bhTzGyRm0P73IKjkdw+se8NMifd8UYSNTs/cC1VURhq2YD/
        uAdCh5UbuhSaDC3pmCRXnO+T9HXlXLnaplKFmHHRCbEEAwlNBAcdDjIO1FsYNogN
        TGrF54gDlBXrGk1ga3WBJ/lY4CvJXetGPk+dAMxchESn5b/qpebStm5pWF31533p
        T8O5K+Ko5SDwY6DAh9LKulyFKkfiF09O68TAjl+vuOdA89tfWbiII3Q2yQyx3mbS
        XgGKd1OtGujFJCulludy3Mtm+n9t9OUtj3z5BiUgN3aS/g/2JM2vcVB/u1xbN6dQ
        ZvccnBCQUiarIVvLg9wBraHcD3O1WRPQHiOnnfbVi6Bi35tYHplapIvWlgk3Gck=
        =YXWd
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.10.2
