apiVersion: v1
kind: Secret
metadata:
  name: mautic-secrets
  namespace: mautic
type: Opaque
stringData:
  MAUTIC_DB_PASSWORD: ENC[AES256_GCM,data:/Dtz9qp2MBtLxNqhqsm7Exe7dA2m6jO1IdKwkDid0d302Uiw/VbF3Vik3ui20ZHYL6LCWIL3kSYON3zQbaefmA==,iv:pxVJqM67K2DfWIu6tFHICIL1NL2E16cmWq6mQls2jJw=,tag:VYch6xo93W0oQeOCxxqymw==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUzlXMmhuZ2dxVi8ycVNu
        V1lLZWNEZXBkZmpvRFduT21vYjJVTUNpVWdrCkVKbzVJSU9pZU96aHc4RnpVRW95
        UHppR29hMmlBVXZMS3FrbzJTSVBLMlEKLS0tIG9GWWlDMy95a1RXS0YyVThrSFVR
        a09FWEZiU1Bnck1zSkx0R3ZVRitUUmcKjI1nkvsE9o6nek9gbvjK31FF/knp7Qmi
        ooQslyzq2HrKI8Sa2mVCWfiAkjh9YOUHyZlcZtlQClAg7sbfdmLINA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2hZRjBDUjVHS2UrWnQr
        c1hxWUxUbVRjd1hqQ25yVnNOaXEzd3ViYVNrCkZEQmViVnhROWV4OWxtRWxmVlMz
        M29EN2hzd1daeFVTMVVoNU1lSzdQZm8KLS0tIHJLZ2JwTEh1YW9VeW16dUc1N2Zh
        QUU2ZDlaeEtqOHkva1NVb3lpYUIzcXMKoKY0ILfp4m7g+wH4WZFVwwqD6VDVvdaJ
        J4XnmR9x0ySgDDVXb4ZZYOVHuQDQhXwa9UsiGLOqgwrML3+qLNlvjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T18:54:22Z"
  mac: ENC[AES256_GCM,data:vp+xJ6fqX8bxW6KJEyBtaAUv8AUUH42dOnkcx34rJeMHMP2XgbeltkNFasdupf2u2ZXCllDjEQlqAhFPpWq7LowNAEmvQaTMQxOwdn0RY+VoeiHwT0z9+oKcXDRoHQueYu/3a+sIIq7Mw1FwOJ4AKazDYHMzw2lvvy932VfHrsU=,iv:o96NFEj07oUuZu3l1sOacVwwzRi0jqiLalPOavLG3lY=,tag:F9mS5tLQRAxXCYZmCN58Qg==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//YzdEs/H00UXYYnZAzTZvv20nIYCuj/e9Xo8ljhZUc6Ln
        o1kyqjNGbuyPj8lZEyIClQ3TXFwlcvB6rKStLgYaERWk576S0t88XDwIMsqVk7Jg
        5arzBp4NAW6ykRpRlh5JksfeNxnyr2O040z/R6Zl6mi8LE3uUdJ1VJNMxxER/FDy
        i2rqM9g4cz3tU4BYJ75VpwVvfYniDPCg+DyWUO+jn2+IN1Ir3DycNAyqkhxjWwDl
        4MAOuOLwwWXn+ooab+ltM9Fo6FbKmaJCsjH/eNkCT1Nm7ze10uy5xUidvJVSmRvw
        tf9YNIU3ZnPY7zUeuBOlQNJhovT4OxMxCYgBt1CSt9rTIb/H+qaoJeS048abYgQM
        PvPRGy2qKFhFL7yi8213+im/8cFau+kgIdRIfIgO+yivLvuy7se+iPSSZTVYvESL
        KapOqCjT7YQhxsVUbvdHOUivFoO4UUbP6OqsAOLW/2a0jTn/4GYIXGU6Roe0juLO
        vAfxnoZoUB+LmSXs10CnoMTrJuPTxU5fTJA8gr7c+ZNza5p9vgMLdJuHKfrpiHxe
        q4+x5L/+90J3SdE/BDjXBUJwhg2uz0niClQ2foKNgEQ6eedIH/McrZY998SRqns0
        8rXND9K3c6Bw0b18en/XULbErJjKgVFhxrgNtOJYQww984sHDFqdEUJZCvyQnDrS
        XgGdChIqPDxRZC0lsNdQ2/fsMlxQZqFPvpsGZdzI6LbUeaOXOBS9WsilEKDf3QNz
        P1bdvFPGau6iVhZZNr/0jWxn5/hdzSkl7tV4cZ0qvyx6IE8y00L3EBXS0ugZKFI=
        =fpvV
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAkT5oNtL351xf+yHY/i0pcKElCkGlL7Dst4cuRf1VTBFb
        rsE06B0jtE23cl893jUkb8xr/6kdS46bHqcGRj/nxnobhcPP+CTv+AqzVav2Nn4Y
        6SBlME2rYMYYmjNOzUW/DwKorLXEJp6VioopTXIRIqjZWCMQ4+dAhnjfp5bDFzrs
        Q1x74rfyHsrq02XvFl/jg999wbSMvOPpfHMHdrr5IMkxB5cGiojGDmHjLspax2HM
        ns0sEr0GzROLEE/roJYLuD+3bErCH2J5SWoIkV++2U7MfPEdlU7cteZY8fao1frW
        4kwBsPYtZfsS6W0jyWPadrWTHd3ydLjfeyc92upgfgKQOIgwNOsWk73s/94pOH+k
        6k5wfrcbzTm51zyB/pGiAGDLkHexi5exyNyTBRJTYtG7GHudTww1RHUKvZMmCKVW
        cvNbpgOzeF2TU5Pxbqyli3DRiB4c5yKkLPp9Gx3gUbeLJrGh88dtfnFuMk6PvULl
        YQEfU4V24zBm/IFNm9v43hLIHfDV/7COWqaPnsXDyR9KTIjQ4LC/6qhm2c0wv/4H
        VfuLVmEYiglaFh7eyHSXQOR21Blpe2R/hY6K+GW3AyoOqVp7BVBkcooGsbNS4vYu
        o8WqesZYBfqeB30ox3tHv/JcsLFFpidLPFsrqLL3HufXHO6wT6CbM66pqEDX9drS
        XgHgDStfSmeTwqppAGdBgc/+OKlr1T1dO92uIgJ2Y/TMtDhmS15Fywoiv4GSDjea
        qrNm2kBxhHad82vBpES4paROVGgknZYN42ymutG9k+h4PcgD21i5FPAJDvEjaE0=
        =+qvr
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: mautic-secrets
  namespace: mariadb-operator
type: Opaque
stringData:
  MAUTIC_DB_PASSWORD: ENC[AES256_GCM,data:/Dtz9qp2MBtLxNqhqsm7Exe7dA2m6jO1IdKwkDid0d302Uiw/VbF3Vik3ui20ZHYL6LCWIL3kSYON3zQbaefmA==,iv:pxVJqM67K2DfWIu6tFHICIL1NL2E16cmWq6mQls2jJw=,tag:VYch6xo93W0oQeOCxxqymw==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUzlXMmhuZ2dxVi8ycVNu
        V1lLZWNEZXBkZmpvRFduT21vYjJVTUNpVWdrCkVKbzVJSU9pZU96aHc4RnpVRW95
        UHppR29hMmlBVXZMS3FrbzJTSVBLMlEKLS0tIG9GWWlDMy95a1RXS0YyVThrSFVR
        a09FWEZiU1Bnck1zSkx0R3ZVRitUUmcKjI1nkvsE9o6nek9gbvjK31FF/knp7Qmi
        ooQslyzq2HrKI8Sa2mVCWfiAkjh9YOUHyZlcZtlQClAg7sbfdmLINA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2hZRjBDUjVHS2UrWnQr
        c1hxWUxUbVRjd1hqQ25yVnNOaXEzd3ViYVNrCkZEQmViVnhROWV4OWxtRWxmVlMz
        M29EN2hzd1daeFVTMVVoNU1lSzdQZm8KLS0tIHJLZ2JwTEh1YW9VeW16dUc1N2Zh
        QUU2ZDlaeEtqOHkva1NVb3lpYUIzcXMKoKY0ILfp4m7g+wH4WZFVwwqD6VDVvdaJ
        J4XnmR9x0ySgDDVXb4ZZYOVHuQDQhXwa9UsiGLOqgwrML3+qLNlvjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T18:54:22Z"
  mac: ENC[AES256_GCM,data:vp+xJ6fqX8bxW6KJEyBtaAUv8AUUH42dOnkcx34rJeMHMP2XgbeltkNFasdupf2u2ZXCllDjEQlqAhFPpWq7LowNAEmvQaTMQxOwdn0RY+VoeiHwT0z9+oKcXDRoHQueYu/3a+sIIq7Mw1FwOJ4AKazDYHMzw2lvvy932VfHrsU=,iv:o96NFEj07oUuZu3l1sOacVwwzRi0jqiLalPOavLG3lY=,tag:F9mS5tLQRAxXCYZmCN58Qg==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//YzdEs/H00UXYYnZAzTZvv20nIYCuj/e9Xo8ljhZUc6Ln
        o1kyqjNGbuyPj8lZEyIClQ3TXFwlcvB6rKStLgYaERWk576S0t88XDwIMsqVk7Jg
        5arzBp4NAW6ykRpRlh5JksfeNxnyr2O040z/R6Zl6mi8LE3uUdJ1VJNMxxER/FDy
        i2rqM9g4cz3tU4BYJ75VpwVvfYniDPCg+DyWUO+jn2+IN1Ir3DycNAyqkhxjWwDl
        4MAOuOLwwWXn+ooab+ltM9Fo6FbKmaJCsjH/eNkCT1Nm7ze10uy5xUidvJVSmRvw
        tf9YNIU3ZnPY7zUeuBOlQNJhovT4OxMxCYgBt1CSt9rTIb/H+qaoJeS048abYgQM
        PvPRGy2qKFhFL7yi8213+im/8cFau+kgIdRIfIgO+yivLvuy7se+iPSSZTVYvESL
        KapOqCjT7YQhxsVUbvdHOUivFoO4UUbP6OqsAOLW/2a0jTn/4GYIXGU6Roe0juLO
        vAfxnoZoUB+LmSXs10CnoMTrJuPTxU5fTJA8gr7c+ZNza5p9vgMLdJuHKfrpiHxe
        q4+x5L/+90J3SdE/BDjXBUJwhg2uz0niClQ2foKNgEQ6eedIH/McrZY998SRqns0
        8rXND9K3c6Bw0b18en/XULbErJjKgVFhxrgNtOJYQww984sHDFqdEUJZCvyQnDrS
        XgGdChIqPDxRZC0lsNdQ2/fsMlxQZqFPvpsGZdzI6LbUeaOXOBS9WsilEKDf3QNz
        P1bdvFPGau6iVhZZNr/0jWxn5/hdzSkl7tV4cZ0qvyx6IE8y00L3EBXS0ugZKFI=
        =fpvV
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAkT5oNtL351xf+yHY/i0pcKElCkGlL7Dst4cuRf1VTBFb
        rsE06B0jtE23cl893jUkb8xr/6kdS46bHqcGRj/nxnobhcPP+CTv+AqzVav2Nn4Y
        6SBlME2rYMYYmjNOzUW/DwKorLXEJp6VioopTXIRIqjZWCMQ4+dAhnjfp5bDFzrs
        Q1x74rfyHsrq02XvFl/jg999wbSMvOPpfHMHdrr5IMkxB5cGiojGDmHjLspax2HM
        ns0sEr0GzROLEE/roJYLuD+3bErCH2J5SWoIkV++2U7MfPEdlU7cteZY8fao1frW
        4kwBsPYtZfsS6W0jyWPadrWTHd3ydLjfeyc92upgfgKQOIgwNOsWk73s/94pOH+k
        6k5wfrcbzTm51zyB/pGiAGDLkHexi5exyNyTBRJTYtG7GHudTww1RHUKvZMmCKVW
        cvNbpgOzeF2TU5Pxbqyli3DRiB4c5yKkLPp9Gx3gUbeLJrGh88dtfnFuMk6PvULl
        YQEfU4V24zBm/IFNm9v43hLIHfDV/7COWqaPnsXDyR9KTIjQ4LC/6qhm2c0wv/4H
        VfuLVmEYiglaFh7eyHSXQOR21Blpe2R/hY6K+GW3AyoOqVp7BVBkcooGsbNS4vYu
        o8WqesZYBfqeB30ox3tHv/JcsLFFpidLPFsrqLL3HufXHO6wT6CbM66pqEDX9drS
        XgHgDStfSmeTwqppAGdBgc/+OKlr1T1dO92uIgJ2Y/TMtDhmS15Fywoiv4GSDjea
        qrNm2kBxhHad82vBpES4paROVGgknZYN42ymutG9k+h4PcgD21i5FPAJDvEjaE0=
        =+qvr
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
