apiVersion: v1
kind: Secret
metadata:
  name: portal-secrets
  namespace: portal
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:itJsdjkpR0TwKscyDBpB6/RspKzJINWZ4h1UqebOcR65bVl1bKvq59HE1fK4kQHqpuIf0ZRVRQPUn+ytBQOSNQ==,iv:97zDB/2LN4Q+7OUXPxz2V6HQeWEXRwdjXq1uOzF1pBo=,tag:M/D2tDJknMUKiqTF4s09aA==,type:str]
  RELEASE_COOKIE: ENC[AES256_GCM,data:xEB7xieKYZoFQozla6bF676+biECKtQVvJHdizZdhMeSazUod10lm47RaK7zLyoVw4LQD3Rnfjv6rZshw3Jmjw==,iv:JvdN3VKb5XjOSFhKJ31leBRuKfiqjnQcBq+cOHD9Bxk=,tag:5fX4Weo56kwvG7KPTLIUhQ==,type:str]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:0/wmzxwGxHtP4NwS9zDqrCKuKq7a9ObamyaBL/7ajTeDsjnxjDLpJR5gIlDoAEo3gaw6E8T29SKx3BP/n8hf+Q==,iv:js3Foh5M6S3lxras4yVec3l6YDs2J8LH0XYUMikvj2Y=,tag:VvPa9NZ90V3JQgC+ZqYJ5A==,type:str]
  R2_BUCKET_KEY_ID: ENC[AES256_GCM,data:NrUtkKwBfezrfqqsKnOb5EuScjIiNPCpt+4MCgd1njI=,iv:xHre8XrXf9FFKCBAOu43FymYgJ1kjzlbL6gAnRYFZPw=,tag:bGzcS/n1FF/wVGC+RoDbBQ==,type:str]
  R2_BUCKET_ACCESS_KEY: ENC[AES256_GCM,data:yK5Bi+OjHyglMZcUEV0jfWdyTIBResG2h2YLbBYSUMQn2KP5qA79KTwnaddbjIp3X2Yxh1CtDmDHPqF2wjCKGQ==,iv:pA8szEf4aGnfGtkNyuqDvxE1e0WsFxjzDhSv3Lytli4=,tag:7zcA9oGVwn8GPDnA7SZxbQ==,type:str]
  #ENC[AES256_GCM,data:3ZyPMK4XjmqMQzIIAO3Jom7fzTZimApSDaT+1dWyYk/afYzMsz5ogc/mNmduWBHlpYAyS6QjEQ5Xfg==,iv:8JrGZ+yVtx78p1kSVVuC+Q8xIUB3cQbTN7xt0dNhsW8=,tag:ixSHlhSCh9klNPj0Ex0gqA==,type:comment]
  ADMIN_USERNAME: ENC[AES256_GCM,data:nFWy20hxB68K5w==,iv:4dSzKbIavW3gF0LwzCHZ8l6HsTAoagokJhUwLnxfyO4=,tag:jZD7ZbfzAo5C5sjnGXYSLw==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:Hdmwt8GAsDlKOcwen3oO5g==,iv:ZBjbzUwLyttgqqQXdpshIK0dpumjoQFm4KfGifIuArg=,tag:3KStO/M5AuJTg//q7I+tzQ==,type:str]
  DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:eslYWjXYKIps+AFjNwwAlh6Vb7las2E/bq2BQSQQ6/o=,iv:90CSFqKXl0U3OWI0r4J1/JWHuGgZd4G6P7BZmXj4Fx4=,tag:ubiZnvYnofdrDMt30FyGCw==,type:str]
  GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:/2lymWkx187VtNJq+7fYMWMbFR10tBKUios3IM90zTZb/tY=,iv:jgOSiSp/XmvcrB1eZxicvGlRpX//lL17saZNZorJ27g=,tag:QAKfxxkyzgro2PhVSUIdhA==,type:str]
  MAUTIC_USERNAME: ENC[AES256_GCM,data:99a1PJm5H15Ucno=,iv:eqj0Y9MFPSpI2EJBddTZzpkCrn8mWqUPIDFriM/3brw=,tag:mBG3xhQyCYfrFx6RIgtMKA==,type:str]
  MAUTIC_PASSWORD: ENC[AES256_GCM,data:ay4GtT/ADaTK6f8MzyXLlA==,iv:Cs+NVbcRB+W4K5kr4HKWoecHepMT7eSBVUIKSFnEZ1g=,tag:j2PfaSIlGBBu77HjVmQKQw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSU4yMy9pUGQwOEpYUEVu
        bFhRdGI0ME5xQ2FMc3kyRzhHUDM3dmFnMEZZCkhzemNlelhXdlF3MlZJVCt3M0pz
        dm80aktRazYvSVRwSkxoaEkwQklQZ0EKLS0tIDlpcXFFdUkvR1VWN00zL3g4QXJY
        WFpuS1VPL2FZc3pyL3QycWU2N21qd28K0bjMYSakn3DtMnceg3pvApvL2OWN1Kag
        KRlGlW2wZk0gOjDEufbD0/IRxN+Du/BRv+Vz4OY4xJ1T6MuyCRTc0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY0R5M1dUQjlKbUtxdER5
        bzZSSTExd2JxeEQxVWZ6bUV4WGsyczlqdmdrCkZ4WnBxcWZGaVBnZXVKWjJyYVRp
        UDd3dnJIZ1F2Y2Eyc0tTTEFvaGNMQmcKLS0tIHoxdWtTZFlveXVXa2Zvb0VqeWhL
        NTdMUkNyeWVBdFB4RVczOEQvOUo5M3MKzEdWgd8bEUuyvvGKJtpV/pYozd5q2KO9
        N9J22fwc5n/gKhvQi0Z8mqcp4UfK3l0E4fDCL7lijRTlgq/Wpa+qkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T00:02:25Z"
  mac: ENC[AES256_GCM,data:LH34GuOXb2VCoIuHRPyBvqjLCX7RIU6GMjg37XPyRPZKX+Fh5YysyM3roJDXuMuDHeOEkaH8F95l9TWVdQqp4AA7ADASY1Z40y8IjU8vT5KzCcQreVbbp/JhSl4fzBtcCZ1JDWIR5jILAv4hQFfpSbRatP4ylfoBr0FmDMdVr3c=,iv:wAXIKol901an2LDmjzIwHhN4G8S24sfmqWZyozms5N4=,tag:gXxEDaWBC6hUUW/77OgMrw==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:47Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//YbNmGlaOO6/aUOzRKdgauhNS+Acr1wQoqzNc3d6wLWB2
        vhtSxfvnnH1pe08RxplECdnnAI6LjE2pXkHIoemAc2xAxEg4tnZgy1OUzQMFshiK
        Kt3B4XqmDSV5F1kbTON4ykEtUDK+f9XoSs+DA0l3xjg2ezanUoed6x8kX0LQIGw9
        27HejHfiJCvC+r4kdHfJeOw5IpUOl0BclSUWa7BsRIHdG2HcgIRIv9lNqupyZ8ZU
        ZvNJmq9XMXxLYRje95CUKViYaIbrgP+1R9DSNHdpQNXvJyO7COMXIylmcb0LvdHh
        RrK6+5Wf0LGpw6BB7gzs/2fahHkMVlskUFcE0KAnMZ1+f0ptRo2VT12O3OAmCEK1
        705H9gaE29lJi5an02HWIzsA4HhNdEA7DfXyTH2JEISJ9o6nqfOeqpLAOdJsU47Z
        XWuyGC2AZFVAMn1c/4qz2T+vOr5cC1QmyFtvsPcbVDgAnhG0hvCYCQtcSp+aBqH5
        33lJ7Z0YcNoNHGQZE1Ayf3kZwazxIq9o2NS0jb+k+dNaRMWsl6u4wmRC8DRrfdq5
        c44GnosGDlhynzhH+xjVe9u9M47AZ6iC+sTTMLDO0YSFFBgtrLdsr2zg5UtnNWat
        KADkaBuc/pmEG/mKFkgJRbGGM2yd13GI3n3J6vDTmRFgAdqE/J5o9KkKPghfJVvS
        XAFAFSlWaZZy9bRrp8XRJd4Jdzxpz5L3ujtmtCvmqyhHBJy9TMD33ysHXe7Lcbp9
        zPZB5N00DVdAUPj7XVPIjDs6z+Y/egtfrAPLcmKtml5khpjeTwij3ucduR56
        =MV2i
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:47Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ/+PpVxFRfwrPYbq0jSGxjOtEXRNRWE02NQSUbk5T9uW8cC
        Z/IxEmPPi//CkiSOM5XqDsw+QCJLrYe6McRbVdL1f4bWooxxp8z+vop9WLa6YwQx
        pWGN8I7YO+GYMIU/y8ueshmaDUqocaGEr/lI+W9lzWFGeh0phY7ercMjl+qzl8zs
        PQljiqzb3g5aKHdAT2Rl65w6Q6GAxNdaASl+SNLvMFAte+4zK58XpzMGqFZI9KOM
        f6L+V0evEb0Ia16w5KcdP4rUTmiWJu8QOMut4EQLGx8DUb44oY1ZvHF3yE3g7oB+
        L7NsYDBcYxzCfBgfRPUFHEEgLiKHe2Cu/5mWhooFDvK33nglEVXJ6y20FK+vR5kz
        4BMrnylOd2i+lUACOXisMH5TMErbNA9lgVq9EFOtp9xUhBPeyoJAFdlFEM7LC1o8
        QmhND6CaNIDUAzbLJBG2+5/Jj3Az3QTnnFvQc83d8/mzUb/NbSsiUDHUGzSeSvC8
        CEnFh6j0WhvlW/ujcESSntpjOhpxvUCaUcEcqqJBxuXnXi+CymwEGyiG7QKMwris
        469PfzhTDwWVuV+Fva+s5l8uY3zend/nLxY7lTHazP6EwJ4HKEkhC6XgElEzJHjX
        OdxTBPwhAHcQlMdtFL1kU/3PI7aUwKOKDyhEeZaArjPDRfkNnbwxvmQ20hJoVh3S
        XAEGw7hVZtwd4FoVbo8iyQv91+wrxdrvRHiqZQP+q86mXMN8GqQw/dhJzz0nvAko
        hPHPDnf+p9rCDkOUWswQ9JUdyQNGEGvDAGwWvx+I+FpgQjnsJywpdHvMPh5Z
        =LnH/
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-secrets
  namespace: mariadb-operator
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:itJsdjkpR0TwKscyDBpB6/RspKzJINWZ4h1UqebOcR65bVl1bKvq59HE1fK4kQHqpuIf0ZRVRQPUn+ytBQOSNQ==,iv:97zDB/2LN4Q+7OUXPxz2V6HQeWEXRwdjXq1uOzF1pBo=,tag:M/D2tDJknMUKiqTF4s09aA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSU4yMy9pUGQwOEpYUEVu
        bFhRdGI0ME5xQ2FMc3kyRzhHUDM3dmFnMEZZCkhzemNlelhXdlF3MlZJVCt3M0pz
        dm80aktRazYvSVRwSkxoaEkwQklQZ0EKLS0tIDlpcXFFdUkvR1VWN00zL3g4QXJY
        WFpuS1VPL2FZc3pyL3QycWU2N21qd28K0bjMYSakn3DtMnceg3pvApvL2OWN1Kag
        KRlGlW2wZk0gOjDEufbD0/IRxN+Du/BRv+Vz4OY4xJ1T6MuyCRTc0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY0R5M1dUQjlKbUtxdER5
        bzZSSTExd2JxeEQxVWZ6bUV4WGsyczlqdmdrCkZ4WnBxcWZGaVBnZXVKWjJyYVRp
        UDd3dnJIZ1F2Y2Eyc0tTTEFvaGNMQmcKLS0tIHoxdWtTZFlveXVXa2Zvb0VqeWhL
        NTdMUkNyeWVBdFB4RVczOEQvOUo5M3MKzEdWgd8bEUuyvvGKJtpV/pYozd5q2KO9
        N9J22fwc5n/gKhvQi0Z8mqcp4UfK3l0E4fDCL7lijRTlgq/Wpa+qkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T00:02:25Z"
  mac: ENC[AES256_GCM,data:LH34GuOXb2VCoIuHRPyBvqjLCX7RIU6GMjg37XPyRPZKX+Fh5YysyM3roJDXuMuDHeOEkaH8F95l9TWVdQqp4AA7ADASY1Z40y8IjU8vT5KzCcQreVbbp/JhSl4fzBtcCZ1JDWIR5jILAv4hQFfpSbRatP4ylfoBr0FmDMdVr3c=,iv:wAXIKol901an2LDmjzIwHhN4G8S24sfmqWZyozms5N4=,tag:gXxEDaWBC6hUUW/77OgMrw==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:47Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//YbNmGlaOO6/aUOzRKdgauhNS+Acr1wQoqzNc3d6wLWB2
        vhtSxfvnnH1pe08RxplECdnnAI6LjE2pXkHIoemAc2xAxEg4tnZgy1OUzQMFshiK
        Kt3B4XqmDSV5F1kbTON4ykEtUDK+f9XoSs+DA0l3xjg2ezanUoed6x8kX0LQIGw9
        27HejHfiJCvC+r4kdHfJeOw5IpUOl0BclSUWa7BsRIHdG2HcgIRIv9lNqupyZ8ZU
        ZvNJmq9XMXxLYRje95CUKViYaIbrgP+1R9DSNHdpQNXvJyO7COMXIylmcb0LvdHh
        RrK6+5Wf0LGpw6BB7gzs/2fahHkMVlskUFcE0KAnMZ1+f0ptRo2VT12O3OAmCEK1
        705H9gaE29lJi5an02HWIzsA4HhNdEA7DfXyTH2JEISJ9o6nqfOeqpLAOdJsU47Z
        XWuyGC2AZFVAMn1c/4qz2T+vOr5cC1QmyFtvsPcbVDgAnhG0hvCYCQtcSp+aBqH5
        33lJ7Z0YcNoNHGQZE1Ayf3kZwazxIq9o2NS0jb+k+dNaRMWsl6u4wmRC8DRrfdq5
        c44GnosGDlhynzhH+xjVe9u9M47AZ6iC+sTTMLDO0YSFFBgtrLdsr2zg5UtnNWat
        KADkaBuc/pmEG/mKFkgJRbGGM2yd13GI3n3J6vDTmRFgAdqE/J5o9KkKPghfJVvS
        XAFAFSlWaZZy9bRrp8XRJd4Jdzxpz5L3ujtmtCvmqyhHBJy9TMD33ysHXe7Lcbp9
        zPZB5N00DVdAUPj7XVPIjDs6z+Y/egtfrAPLcmKtml5khpjeTwij3ucduR56
        =MV2i
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:47Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ/+PpVxFRfwrPYbq0jSGxjOtEXRNRWE02NQSUbk5T9uW8cC
        Z/IxEmPPi//CkiSOM5XqDsw+QCJLrYe6McRbVdL1f4bWooxxp8z+vop9WLa6YwQx
        pWGN8I7YO+GYMIU/y8ueshmaDUqocaGEr/lI+W9lzWFGeh0phY7ercMjl+qzl8zs
        PQljiqzb3g5aKHdAT2Rl65w6Q6GAxNdaASl+SNLvMFAte+4zK58XpzMGqFZI9KOM
        f6L+V0evEb0Ia16w5KcdP4rUTmiWJu8QOMut4EQLGx8DUb44oY1ZvHF3yE3g7oB+
        L7NsYDBcYxzCfBgfRPUFHEEgLiKHe2Cu/5mWhooFDvK33nglEVXJ6y20FK+vR5kz
        4BMrnylOd2i+lUACOXisMH5TMErbNA9lgVq9EFOtp9xUhBPeyoJAFdlFEM7LC1o8
        QmhND6CaNIDUAzbLJBG2+5/Jj3Az3QTnnFvQc83d8/mzUb/NbSsiUDHUGzSeSvC8
        CEnFh6j0WhvlW/ujcESSntpjOhpxvUCaUcEcqqJBxuXnXi+CymwEGyiG7QKMwris
        469PfzhTDwWVuV+Fva+s5l8uY3zend/nLxY7lTHazP6EwJ4HKEkhC6XgElEzJHjX
        OdxTBPwhAHcQlMdtFL1kU/3PI7aUwKOKDyhEeZaArjPDRfkNnbwxvmQ20hJoVh3S
        XAEGw7hVZtwd4FoVbo8iyQv91+wrxdrvRHiqZQP+q86mXMN8GqQw/dhJzz0nvAko
        hPHPDnf+p9rCDkOUWswQ9JUdyQNGEGvDAGwWvx+I+FpgQjnsJywpdHvMPh5Z
        =LnH/
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.10.2
