apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:TOapWGP6RL4QaA==,iv:80JaipdqVL0DjE0TsH9qOBbm2eZHA9zhsUOlaErcmZ4=,tag:F83Xx5UJ5sF95dGqVRubxw==,type:str]
  password: ENC[AES256_GCM,data:4T2Zz/FuSLUBenjoAtPQQg==,iv:ZzfArMLwYcjQCBPS9HWLPzuyISJ5gOFculbmgDsMqr0=,tag:Wtp2r9yHGZmDTN2Aq7z10Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNUZnaVJlQ1JBRmx3MURD
        eUFlSHdITkVWQ3VuM2lQUFVMSGViQWs1b0R3CkdlSUhkVTBQVWozTDJPUk1XdWpj
        WWxQRDR5d21ITk5hakM1RlVTdjA2NHcKLS0tIDdodWpBYk93VFpLSTBpLzNXWVBr
        UnRYVjE5TzN2MkE5bjN2akg4U2htR2sKhtEr8e6rmdg2hmoYuH/tqfFzUDHT85QF
        uD97vl6vby2TcSXfSVqNBDIt+PSmfEyfRIcFSXITGXtMwag3PzlX6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdDZaVHErdDBJZkxYRVhS
        Y21QcHNsUjkwUmhMcEdlMW5JYmQ5Skg3ank4ClZSK21QRTdTN0trSkdGSm5tWkY2
        RlNuNUFyTXg2dUtSaHJxaDAvQ0xnS00KLS0tIHJxa2tyQlVhamU1a0tLaUdkNVhi
        TzdlSi9CUFE2RTFkbkdJRmdEcDd5WncKmT05zrcyUVID+GAMOAcurN3v3/O0gnNU
        t4mG26KHcbxhYag6hdQuu54Xp5OcLZabYKJewqV7yrsX74lYnc4QoQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-01-12T00:07:33Z"
  mac: ENC[AES256_GCM,data:z4KUt9kdCiJVpQPUkmdj9i5o9YR/UF2isBWMvU4qkwLCpOLswpRhTk8FC24vhT6BhDs+atC0XQnBRjEX53c88c1Se5zOGNyf3Z1gTkmwFMJaED9dBse4KF/sO58DKbnCdd4M2zmFcKqB3ftZG/PKt4HhGOEY5mJGEqOdnDEkLeE=,iv:/1Kz3bjRy28Crb12kfEjwPdHm03+0LTfGMAiqjzcqSg=,tag:CNWuajXkjsmEfmzD4fyC/Q==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:48Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIARAAnL/MA06WeV6yHt7UVmxSD3n2EEjgrA334M/b+UzVYdsa
        YK+2CKuLU5aWWDPi7lB3N4RWScSD8prUWlf8md27CnxaNwcmDn7nNhGnzM4l3ZhT
        8SSYJLH5W8ZBIpRDLEIu0vRbNQjNKh0+6QttF9Bj9X/UY/K44Gfh3YPuOfss6dI1
        QL2gxJ1JyOOfChfh1sqXrhW0j+v5MDhBu//VLrSTElyliOIXAu/Kn8M1aiLadpuF
        J73UFg5uPlC4NrPk/fKA3YRu4fH/sgrCQ5iL4NB87yppxuy3cMxIeouw2fqrhoOk
        fEwNGVT/HCgH8d1vgPHX5a9FROIbDuNMZZ8jXhNVzu7LbQRfVwkFsp4jgs6MDAnf
        h46RJLULFygVMBuXZgy0nDynXDMYfMd9e23PX17Rkj0+Zf85cr5wXhFOJaRwixtd
        FMxfppr0amHya1YrTPcPXJ80fjFD1HvRd7W4Lw6cT4H2r/1D4eiXSVijZdnTOsmY
        uUc9oXihm/Lw7WMdSITZmzxn+DhsCuWBgKYWa1Bo5QB4VFSg/Ar1Aua7l+5I0WYV
        33jROqteC/u4WT7AeIO1elb2COUXCE6/0eUdek2fJdyXu8+BDxrJB8VXpIlrQ39k
        QPPRfVc0vhfZEUhkTL4SkPOuPoDtuFYs2wJW+e49+pS9mXBzkGUcAWaaiU4EshPS
        XgHHZPDhvNO4yb0aGvkOGfvdlp7Yec8RMXkXJ4WPMkMdwCYlpOMXt/15rC1zcsnj
        /rH+dJccs1CS2DP2TTz7x7knT4YdFTTQeE46fMHsUDL53Q3Vd/AxZg5Kr3/i3kU=
        =bxRT
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:48Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ//e3u3A+X+CgMT/zBUgGehPtnShunoso7d8XSfsDSGvU7i
        6Uthienko2DyhnMBUR2otiwE/7jPHMyXPmbJh5f7dz6+NTEA6PBcOD+CbtXSqD8t
        jzqxlOsWppVB6uH9AZyrNcOrgp2CteYFt8p2G+IbOJq88VPWJxT+VKv8fpC5l4aU
        uINerXsqj3BTIN8kDn3ciCNK8mSME9LEN426PaCcufIaR/QHd2UL7w5jdrVWWUgF
        75pwWoQoOXjBpCo3L6xmqq3YSsubVA+DOh5CRXMOO9RZ/m6/pWNhH54YUycEUKe+
        Vzo7VRXxs3eVGwGAyW9IEhnu5Es6FrN5sR/KciLbQQS93ANx3ra2VKYw0KjHlDvd
        dMBUoUsgo1gxjKOpGFtc2qLdOHzdlkxh8vNghfRIhuggVfZtkdhav3PykP+JfPGM
        uMTK60xtEt7uja8U8J/XdwFxBaKDUMSRQYk3hUJeR2TdRRv3ehmrrKSIaRcKvj87
        mI69SBYy4A7EGOpdw2UUDVItq1U48hS0G6Z2CmG6+njUlOo+eQJp5VC/mRp+zGmW
        UubUSCn6fuzFhFquF0iT1unGllRtc+kf0wE8I6mAVlP5z2IEUH5XZ6zs6tdFo1MW
        2MFNM3i79z9aRE8UGrwEqD5oyt33A7Y466HR24BkHSvxFIGqy8GKM+wzpKdAm1/S
        XgHo7kcVUA+MmvMDzA/KKolG/BH+F2xv2kBKd18fVEZf8nOBgzGZsUZO3DuCDFcN
        eAixlrYq4L3UuaaVCNMsX1rqxZx6S8BrnsXF01dZZSIKqNMCIZ2+4VuRk+mXAsw=
        =cp3N
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.10.2
