apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:TOapWGP6RL4QaA==,iv:80JaipdqVL0DjE0TsH9qOBbm2eZHA9zhsUOlaErcmZ4=,tag:F83Xx5UJ5sF95dGqVRubxw==,type:str]
  password: ENC[AES256_GCM,data:4T2Zz/FuSLUBenjoAtPQQg==,iv:ZzfArMLwYcjQCBPS9HWLPzuyISJ5gOFculbmgDsMqr0=,tag:Wtp2r9yHGZmDTN2Aq7z10Q==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeWpqOHpNK2orS3lja0tp
        ek5NYXFrZGlhZDYvUnVMVXlXTHFCVTc3UkcwCmFqcVRtcEVLL0ZkbjJ5bGZFNXYv
        Mi9vbUNaeTZrSloyNXpzOWk2dmMySHcKLS0tIHBZTnRoVGEzYlJIaUNiK3NGOWlJ
        bStVcTM3N3VnNUZtdXhVWjUyOEt2cFUKcIvqldDJN8GVLqyWxFMwlg+aTfT96sW9
        +328gJUVIOd0L6yxsyBP/RIvx7BHRMUgTfDydEobwbobmaOS+L0kbg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMDhMQkhQUDNYQXJIQ2lU
        eGlmUWF3VzFJWE8xTzlNODExSmZwVm9JWlVZCmtraVUzbXo1bEgzckhNclBxeXNw
        cVJJQkthcGVSdjBVWVpRN00xbXlzZlkKLS0tIHdUS00wSkhRVS93RmRNcEt4WjZI
        R0RicXZkdUduQWZTTVVRVU90UlFSSFEKJMDOsFaHw6c3TF7Yl2I7Ez+ZrHJJy4PK
        OgH9a9pQOpyqnFamEX9XcvDjrb/i/7DRMiSYumApNFEkChYqRIiMrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T00:07:33Z"
  mac: ENC[AES256_GCM,data:z4KUt9kdCiJVpQPUkmdj9i5o9YR/UF2isBWMvU4qkwLCpOLswpRhTk8FC24vhT6BhDs+atC0XQnBRjEX53c88c1Se5zOGNyf3Z1gTkmwFMJaED9dBse4KF/sO58DKbnCdd4M2zmFcKqB3ftZG/PKt4HhGOEY5mJGEqOdnDEkLeE=,iv:/1Kz3bjRy28Crb12kfEjwPdHm03+0LTfGMAiqjzcqSg=,tag:CNWuajXkjsmEfmzD4fyC/Q==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:48Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//W94hFxAvQeTrWxQph1yBYO6U/FlnH+HAH4HBZk0CaUTq
        58UqoM454iqxxg+L1OKLC2Yyxs1oSQBBDlKiysvO47+tvcwpiwywS9clw8UIUF4k
        qdOzGxJz3g1EB7tQD0CVN7evY3JzCkmjoT6qHhdibOSV8lUlRl9ZjREXLGQK9XHY
        SNG1USe+IuuZs+zZU60e8MiGbJth/xc5mqRyAeW9+HJ0DRN3K54/JzaCkIH2XjKB
        wXg979ERLO+Qvq+bRuizras8SXyghuoT+Vajo1qFH8wIhwC+oT3wOB8T7ELRdGsJ
        SW7GHxbpfCPzLno+x+ofK9A74YSvxEXdObDqlVu64Ub6JwTzbWG/PdazT4+BNr3y
        94iYQx6bgvRUhL0FhTrd6wiV3UZgcNWA8ayLm26jof0RdtBwFN0NayzZ75Tq78XY
        Rnxc/QNEzScomjjGFtAamG9cG3prFBAIr87/Yl3RlUyFftyI1JpYlnhMPiFkrria
        eaAm9u7zueHFcjoej1cjcZdVIsdvIQMKs1UwCwz4sCi6+oOUvM8k/Lpoz/4BqH+o
        e0V7vIb/PQFtD6Je7ZheIbeCIMdTisvVZWdVaFNgzmyhMbVZrrrKajIpgHy1uzqo
        BWdsLdJsUYlVwew/0A4f2PJqUvRJuyO0Phpi/g71a4hbAnkRb0Mb7IzjPv6a9WLS
        XgGYMbzrgwJxATporb1QKeAZOsAtj+y16xlaeo3szBMRh7BfJ2LsXJK9JezbELQE
        Kai9Ua974pjyCS+kXrI+4rKnlz9fzZQu9ItdrXK3sPYfrKY5d5mOKPq1rehWTpk=
        =77nu
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:48Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ//e97756SjREEC9JdImsnmB4DoQLenQOcFRXDvnrS+k/Uu
        hhrO9gUZJ6osTN/VeVkOuT3/dosA1nCQK59ZvLc8LFj0GHUMZO4W741zMSag8935
        aGI9LkwxPibfy/DCTUbiKJ1QoMOpMf88fRpY5QgzotogxxRvNS2AFaIQGp2KXCFb
        OOf/L1VSSmPCU/MLcZFO7ulen1VKeRYaKLgogjYpgyDqyuh0kbTe9QYi2H2PerrH
        pFiA1BJxqi3DTaGpBFtWp8tLapVEL5ALkAHJJgqO6M/jJnLIBV67EflHfamvdBjE
        Rx4mtA0n263ovPeKXbiV0oQnGbSEQGVnc9qkFpw4dymsL2+aqZD+xnssVFoWisEA
        7/uMN3kLb241vpZAUGWSDmqJWKBDfYpPTAjnApVp+h4J1wqcCk3bptp3iDgJefpu
        1aXkhj+gtyA0AuvewHpRKiopj9rexI3eH0uq9xS4usKr5RMOcDcOnJy5WX1wNl56
        MjLW2pgrYfZ1l/y2SoAImS1Ojt39FAwPdhQ8CyjYdzB9/ibRpwuo8MVIqk8Bs/i8
        HoFPiy23no/Cya7AN+Utf7UDO3fZtuWabhaPKHnT7SGlDSvBwkVIRlOSG0AFakVw
        PDtmGNeVKvQOHzFNcmeyGWMFXcZ05ALt8Wnj3zAtA27/8XYUyAjHc419W5W1gdrS
        XgF0U1/SwAR82deYrJZJQ4kpKvKqNAlF3ynQxPE0nVk32xtSWtxWvZjvlB0STHiA
        5H4uCRSVuu/dvunikJBcwxpCnXbsSfwp/zsXGgGsu4bng6km83inTTcVH19r6dk=
        =IKsb
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
