apiVersion: v1
kind: Secret
metadata:
  name: shlink-secrets
  namespace: shlink
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:9wZAXGQPjR6wv3J9JMFLkH6u4mRSVqJaE74zNnMGdIr2sWdNkQ/Jm1/OAxB05Vj7ItgAKfl3H6zF6essMKuEag==,iv:5rd2y993fJcECSHkoqYZMsvDcZlxfy/UAs96A592HVA=,tag:ckxaJ/jMkdVD8q6Qbs3Wfg==,type:str]
  GEOLITE_LICENSE_KEY: ENC[AES256_GCM,data:uqSBuJbHOOjnDp9LeJMYrzXdT/EZLmI0Xmx9KUGssQBjtzoK2+CRmg==,iv:2BQbZa4fl2RIGSNd0sKIQ5eNLLhTVZFI83iw/mqSnHw=,tag:zHryw4CfVLpQ8MYDuSI01A==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeHFieDl4WXIwdDdwd1NZ
        aU1Ya095QjVLaEZJWnNxWnd3QXl2S0pUekMwCm1iRHFQQWpNRytqZmlKdUtoMlJn
        K0tYdVJxQWgyeXNzT2V1L3ArMzdxYWcKLS0tIDdTbUQ3REVlR0syT2NRMUZSS25w
        OE05V3J1c2hCK0xvVXhGeGtwV25tYUkK9jRIG2BSpJhxfKxQ9TumyPLaFFlUJueN
        ARx643mp5I1NQ5ZzqnOHwLWiEp2+iFHIR3aiQmausOoj1ZlbCzremQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWlR1RmVvUVF0RTNIS1JQ
        UmtIcGdVYzN5V3ZxWVAwSEFYYThEckNtTFQ4ClVMYjdnZmZucEl1M1J6MFJ3QUw5
        NCtYRWNaKzc3dS91Yzc2eXJwQ2k4VVEKLS0tIE5tMzRJeG96VWtQUndrVXQwd3VR
        MFJqZHhTbi9DVElxRHN5L0FaL21EZ0UKFYvj8K4kiR2u6TGPE1nkJGCrK0aiONp7
        4lbKua4TL9qFoC9/uqs82WYstqG5ehafAt7a7avSsl8X8z9UwxKjRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T17:13:58Z"
  mac: ENC[AES256_GCM,data:LEjeckglApoRTF2UlhMDuVpSTxreX9QSfRhamuXNCi0yZxnCacgXiBTK4D+8IOhYSm2435pYRf3Y/+zYKqS4PSlZaKIK65IPsEAKuO1PSLU3m2QT9MHBqdW/Pn3wUJPxvzqdVhx7uHQttUJ14hng9pownVqJ2xYV3ak1yJ450EY=,iv:XUgxArNYBD6AZRyvfYSsnvcD8HabceXUlgaD0niQ6KE=,tag:xGGyxCKhwpVut3jcYs93jw==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ/+NDBBW0h4AsbJW7QabSaKggqtSrGvSMlf8uEGmKVmUWbq
        svULJxVHlmsZoOCX2FafZpQub8YOP2s49qhoE/hi3LoVpyxqsTly1V43Bln2MDgF
        WkOOwErsDebch919jW7rYUSNZEVq/UxfzkcdKEyyYVYghFfygHSB6rjThWtUxXnR
        fUPB1QmoLpRQv09t5jsbnsFaTTUFqZVd8LjPoUaFYF3wBPXp3n9l0NPWwBTYGq+u
        bw2agiEMpssLSOKy9vkdN0OWJSrEqS+Zss8mm3bTtRgrmil9dYxzqi78Kat+NHEU
        o05LkG9ogMDzWJaW/TBS3z1p6G9JqOHV0Mm4GptNK1NriLbKi/LTydHK3uoty2uq
        omXSjPcedfLyieZVeizcHyafwFeULMBErJoGhRHsbf7IS81O2YYE5ddMf3z/u4dg
        N39s7HLRD/R1JRCljCelL1RCny1YXfH8B7ccaOt8gNCC7RD4TXmzEQuxP9ynLWHG
        7eYBxK8NKUhC3ni/25bH7SfDdt07anQ2K7MQs8wqMyLzz5tViKyTOoueIxBWvmag
        lwhVBOaIDSNKEXDIYI81HEiO0eIcoeYFs21dTf5cWOB1zL7IRm0tcNXlGQ4wqq27
        /x0LHSTF3BNaHa2Sh0VqfBb7sDMzH8JgXA4fK6YD/yh29yqUSaGruexqz/ApugPS
        XgFIZlzBi5TVVG2lSk9TaxPFRbSqjgYfnPvpIcUycsmHxaXste+CxV3WdlKW1p9U
        CmORYAURDRaezGpnxIXxX3DHzlZMlpIOoEw4U9m5OVBlJo00c7R6r0VgzwEAOZs=
        =4IBv
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAxxOlBLC/BUuGpC1amXCDLqZwTjMEH9fTUsbO7QJ102HZ
        82t0RYq7GHGfXLCWHObpDzyr/3RU1XR/V5OGoAj+5+XeWbaSjBctuMhEBE17N99d
        u+BwUOeTk1vN0CIvKV8o4UVGSyXAZQypkPvKy8sT2ODgro8tly2m4DEA9ns04Zdl
        JT1z+52McMdurHqTi2AzeRfdGo2gS13VqA2M7i0EKzYhCIpOfjp93sOPym/0+tIP
        ob17IaggWM9TBSZOCBMRcfwnBaTOmuetRj79ua3yIp+sH35fFednFrVorlxX8Vrs
        68KmjH6fF8fdu9whFj2g2+gW9emSHGEI2F+pd9Zxcs6pVcEFyhqIoCZrQbBwMwA5
        MAQwYwXadGphuQ89pgz9Lz1LnjS8Wv1ltcUglSgrrWO6kTlDeWAHw1c0Be/mNAcC
        FAe8UbFtYsFHIGIx2fGekU9VGSSBqymRMrfF23OebKWb2UtlSgdhAFIpeCK+24C2
        TaxKO+vOaaTSfXQUWRtIWVJu66YrALbE9iWUIrmYOFzEuphOwAw90Pom4BVxLllZ
        vcKg060yY3jP+sx2B32WGOXvpLoY/oPCmVdF4LR8oMy36R4HoyLdBO5+tjewXAAS
        zVFEZE/Tk9X9bKGpq4faeinOXL0r2wkQ7aHRnbugoe4tnRLydFIIg7AsoOza+3bS
        XgFc8nD4WtJcibU/YInkoJD22mgtiq3jc3iTPnahp5lZJlQB/T5/kMfnBIzkK6Gu
        a2QqDsG0AfV3xo9FitejnAhDhhNpUOnN3u0k4oL0vX75ilOkstMOL97JkA/Sbys=
        =mUpW
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
  name: shlink-secrets
  namespace: mariadb-operator
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:E0T6VLV4u65Ue0BkRKzCjoeqbLqZ9SBYbRqwzFXN2M4y1XpHpS15FTw4hI4S8EvBL3cxJGIFBipxKV8ht8Mlyw==,iv:hUpXryhCnVw3ctcyF4BIMAMyeHmAgCWCqejOeKqoG3A=,tag:hzGNPkdRR89fjGRG9m/7WA==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeHFieDl4WXIwdDdwd1NZ
        aU1Ya095QjVLaEZJWnNxWnd3QXl2S0pUekMwCm1iRHFQQWpNRytqZmlKdUtoMlJn
        K0tYdVJxQWgyeXNzT2V1L3ArMzdxYWcKLS0tIDdTbUQ3REVlR0syT2NRMUZSS25w
        OE05V3J1c2hCK0xvVXhGeGtwV25tYUkK9jRIG2BSpJhxfKxQ9TumyPLaFFlUJueN
        ARx643mp5I1NQ5ZzqnOHwLWiEp2+iFHIR3aiQmausOoj1ZlbCzremQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWlR1RmVvUVF0RTNIS1JQ
        UmtIcGdVYzN5V3ZxWVAwSEFYYThEckNtTFQ4ClVMYjdnZmZucEl1M1J6MFJ3QUw5
        NCtYRWNaKzc3dS91Yzc2eXJwQ2k4VVEKLS0tIE5tMzRJeG96VWtQUndrVXQwd3VR
        MFJqZHhTbi9DVElxRHN5L0FaL21EZ0UKFYvj8K4kiR2u6TGPE1nkJGCrK0aiONp7
        4lbKua4TL9qFoC9/uqs82WYstqG5ehafAt7a7avSsl8X8z9UwxKjRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T17:13:58Z"
  mac: ENC[AES256_GCM,data:LEjeckglApoRTF2UlhMDuVpSTxreX9QSfRhamuXNCi0yZxnCacgXiBTK4D+8IOhYSm2435pYRf3Y/+zYKqS4PSlZaKIK65IPsEAKuO1PSLU3m2QT9MHBqdW/Pn3wUJPxvzqdVhx7uHQttUJ14hng9pownVqJ2xYV3ak1yJ450EY=,iv:XUgxArNYBD6AZRyvfYSsnvcD8HabceXUlgaD0niQ6KE=,tag:xGGyxCKhwpVut3jcYs93jw==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ/+NDBBW0h4AsbJW7QabSaKggqtSrGvSMlf8uEGmKVmUWbq
        svULJxVHlmsZoOCX2FafZpQub8YOP2s49qhoE/hi3LoVpyxqsTly1V43Bln2MDgF
        WkOOwErsDebch919jW7rYUSNZEVq/UxfzkcdKEyyYVYghFfygHSB6rjThWtUxXnR
        fUPB1QmoLpRQv09t5jsbnsFaTTUFqZVd8LjPoUaFYF3wBPXp3n9l0NPWwBTYGq+u
        bw2agiEMpssLSOKy9vkdN0OWJSrEqS+Zss8mm3bTtRgrmil9dYxzqi78Kat+NHEU
        o05LkG9ogMDzWJaW/TBS3z1p6G9JqOHV0Mm4GptNK1NriLbKi/LTydHK3uoty2uq
        omXSjPcedfLyieZVeizcHyafwFeULMBErJoGhRHsbf7IS81O2YYE5ddMf3z/u4dg
        N39s7HLRD/R1JRCljCelL1RCny1YXfH8B7ccaOt8gNCC7RD4TXmzEQuxP9ynLWHG
        7eYBxK8NKUhC3ni/25bH7SfDdt07anQ2K7MQs8wqMyLzz5tViKyTOoueIxBWvmag
        lwhVBOaIDSNKEXDIYI81HEiO0eIcoeYFs21dTf5cWOB1zL7IRm0tcNXlGQ4wqq27
        /x0LHSTF3BNaHa2Sh0VqfBb7sDMzH8JgXA4fK6YD/yh29yqUSaGruexqz/ApugPS
        XgFIZlzBi5TVVG2lSk9TaxPFRbSqjgYfnPvpIcUycsmHxaXste+CxV3WdlKW1p9U
        CmORYAURDRaezGpnxIXxX3DHzlZMlpIOoEw4U9m5OVBlJo00c7R6r0VgzwEAOZs=
        =4IBv
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAxxOlBLC/BUuGpC1amXCDLqZwTjMEH9fTUsbO7QJ102HZ
        82t0RYq7GHGfXLCWHObpDzyr/3RU1XR/V5OGoAj+5+XeWbaSjBctuMhEBE17N99d
        u+BwUOeTk1vN0CIvKV8o4UVGSyXAZQypkPvKy8sT2ODgro8tly2m4DEA9ns04Zdl
        JT1z+52McMdurHqTi2AzeRfdGo2gS13VqA2M7i0EKzYhCIpOfjp93sOPym/0+tIP
        ob17IaggWM9TBSZOCBMRcfwnBaTOmuetRj79ua3yIp+sH35fFednFrVorlxX8Vrs
        68KmjH6fF8fdu9whFj2g2+gW9emSHGEI2F+pd9Zxcs6pVcEFyhqIoCZrQbBwMwA5
        MAQwYwXadGphuQ89pgz9Lz1LnjS8Wv1ltcUglSgrrWO6kTlDeWAHw1c0Be/mNAcC
        FAe8UbFtYsFHIGIx2fGekU9VGSSBqymRMrfF23OebKWb2UtlSgdhAFIpeCK+24C2
        TaxKO+vOaaTSfXQUWRtIWVJu66YrALbE9iWUIrmYOFzEuphOwAw90Pom4BVxLllZ
        vcKg060yY3jP+sx2B32WGOXvpLoY/oPCmVdF4LR8oMy36R4HoyLdBO5+tjewXAAS
        zVFEZE/Tk9X9bKGpq4faeinOXL0r2wkQ7aHRnbugoe4tnRLydFIIg7AsoOza+3bS
        XgFc8nD4WtJcibU/YInkoJD22mgtiq3jc3iTPnahp5lZJlQB/T5/kMfnBIzkK6Gu
        a2QqDsG0AfV3xo9FitejnAhDhhNpUOnN3u0k4oL0vX75ilOkstMOL97JkA/Sbys=
        =mUpW
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
