apiVersion: v1
kind: Secret
metadata:
  name: shlink-secrets
  namespace: shlink
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:9wZAXGQPjR6wv3J9JMFLkH6u4mRSVqJaE74zNnMGdIr2sWdNkQ/Jm1/OAxB05Vj7ItgAKfl3H6zF6essMKuEag==,iv:5rd2y993fJcECSHkoqYZMsvDcZlxfy/UAs96A592HVA=,tag:ckxaJ/jMkdVD8q6Qbs3Wfg==,type:str]
  GEOLITE_LICENSE_KEY: ENC[AES256_GCM,data:uqSBuJbHOOjnDp9LeJMYrzXdT/EZLmI0Xmx9KUGssQBjtzoK2+CRmg==,iv:2BQbZa4fl2RIGSNd0sKIQ5eNLLhTVZFI83iw/mqSnHw=,tag:zHryw4CfVLpQ8MYDuSI01A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT250VDFSUHkzOENsc2xz
        VVA2NndVbmhuclRjdmhhakdaOE55bTFid25JCnd0RCtJNE42WTgwdGNzYWF4ZEZa
        cHc1bWtPcW43UXJHMHVyZXZMR0laYWMKLS0tIEpYVEdEeHUvT25VSnNtaXJKV2Ew
        RFJINW83dWNWTFNPcG0ycjN4SFllN0UK/HLwyR07uAXfOGlu+yXF+XZvkavsegpi
        bQ7Z5Kn7VgP+pbdT00N7a1OKkvYIKRoTYq4heRNh7ilGGcQvuj/NVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcUM2UHp4aVdHTnBUQXNQ
        WlRsUFlDeHA2VWJZUjJxZ282VTN5bTR5ZVVFCkVBamE3bzRRalJHakF3OUUyUVcx
        M2hwbnlDM2RhcjRuaEg0djljYWYzOE0KLS0tIEFSYm43MVAwbmZzUjh5RnUrK0FP
        dmoyTWVMcGZWSUdoM3ZldEttNTkwaTgK3YT+3FyOLbUs8A4acNkpv3UTbTVAMskg
        BqbEd6EIpxTFXucto3JQh1yF0NiSrfXOoo/DVKhpzSZzoza4BqpNnw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-02-18T17:13:58Z"
  mac: ENC[AES256_GCM,data:LEjeckglApoRTF2UlhMDuVpSTxreX9QSfRhamuXNCi0yZxnCacgXiBTK4D+8IOhYSm2435pYRf3Y/+zYKqS4PSlZaKIK65IPsEAKuO1PSLU3m2QT9MHBqdW/Pn3wUJPxvzqdVhx7uHQttUJ14hng9pownVqJ2xYV3ak1yJ450EY=,iv:XUgxArNYBD6AZRyvfYSsnvcD8HabceXUlgaD0niQ6KE=,tag:xGGyxCKhwpVut3jcYs93jw==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIARAAi3zoaTSyXKRvnlf42F1Bfl2S5CmyQoLIFz/q0Vjqw1r6
        8QKuGFKKpJyZ+i4f43La1RRsxX72MCh6UJfD8MLcmBmgt7dFVFOU+WqG8YhCHHRV
        A7hXp9zya69oZmWz6wRcdDOZPs5eVcChd/v08fW6HiLGgsDbODrCgp5KpHBrJ+Qa
        7PsVvtSi0oyeK+b3AlynXp+S/lfRMckeOXOG7K+I+IjAjA9+LesO054o1tVi45Vt
        n5p/qM1TDrSuJoLZsAbMpxWuzpjuS4EjaKkqV1NUQBoNPmP+hSnFGN8VRQvQMQyd
        OHxIekhG/7uNloFpsep8WAEb/ofpgo6lTKznRd7hYu2bx7avZ35FZaGS0U7ahnwY
        hA4yv41kc31j26lXz7tN0NAvFLrZT7V3dkICcrW3ZYp5wcqb+qV/ShsC+d3qsKAY
        gz6Av5hi4FadwIyXS7eKAJxrxtoxMHNRMBGnAqZq2bo6Z9VeRdFbLhGwieu2sfOF
        GBJvnm2l9t6B7YTUFQ/H/tQk0vR/bwen/QUsgYLhkHCxY68CRQolJjnqR8eKIxX4
        IbcRLvR0CM2gOLwq+1UBpC/Wcd+uhGZx2u8EbJSU72k/dTiVA+/x0fm8s+bGQBuu
        K0mwf/TSk5svKqKsl5wE/gagORFbIL5EH2J0OMVkiNFKWYzBTNVzZBf6Fi2cuKDS
        XgE2kiljLQj6XMCk20xNSSA2afVVWazcylvaaFvPwBxmYY4aYiu6b4MAD9oajZeS
        Ouwt5OOoFy856NHBRSZ5a2SJTOHJJKbMogQhYIfkG49Cp9Sa6oKtTipDPT511n8=
        =Tkb0
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAhIhzfKtafPI6m7ec8N1k4XAt9PcAVC9Y0ni4ohfus1Ll
        5kU65UNPMNm6s8D+XiqxMpLvC156/xRqiMBSacqQaRs+fTxomNCi2S8w1APeaeUp
        mRk5hMtIqQBvlO3X16TeO1r18kEn9IkZneo4w5urdvsCyaOJr2DKLh+V7+OrWiWi
        UTzAtNTXjjdrvY6KgJSXZM2jPNYn4McGwC81FMNvP4oLaUNDM9K/E5BwYtI5bJxL
        u8TCOElate1RrrSZT4Av6S0mSAG8Sfdtjs/eXWtpCN5W1yt3/MvRnyJv/4dxbdWp
        +4psL9CwtEIUWQM3mIvmosH8XlwAXVhN6q8lAMgBajPoyYX4q/yBlbLMFpDSwwk/
        M9IKKhYFZKqNUezlQDarl0cXD5KpVoX37evjvO1Q187yiRPaSRJZmxCFCuRfu6rE
        LO1wvgROfLBHv8sTK022rU/ZF3gXenZ58AcwOK3XSF+U3pKAGlEIFTQ1TL2DFXb9
        Zx8TKlmjpU5wSdgz7VtYL9zZuSSgPDV9r5eWJghuJnPC6eqEdJcN4hgjvAptI8b7
        UqHECsFh+5txznYKZYycNoR12AIOO3ZbWZhDCBKfT5feADJdTgGShYvy8Rb0/wfB
        ZzfPEkHFuWe2K/rVnJMX+qEuKsA6T38a1viRZ2cO4AwdS05iaDK4aIalhVCD50/S
        XgFlR6krHpDYYre/Z0zyuxGGUitvZSUXo2kFI+l6Zo+NBeYnxVpx30arSiEHKDz2
        /iojuX6WPn7ndxSxQohct5ufvrtahOQmmvgqD7fxsL0wPzgr54i/6z7UUhBN/zg=
        =BWw6
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
  name: shlink-secrets
  namespace: mariadb-operator
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:E0T6VLV4u65Ue0BkRKzCjoeqbLqZ9SBYbRqwzFXN2M4y1XpHpS15FTw4hI4S8EvBL3cxJGIFBipxKV8ht8Mlyw==,iv:hUpXryhCnVw3ctcyF4BIMAMyeHmAgCWCqejOeKqoG3A=,tag:hzGNPkdRR89fjGRG9m/7WA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT250VDFSUHkzOENsc2xz
        VVA2NndVbmhuclRjdmhhakdaOE55bTFid25JCnd0RCtJNE42WTgwdGNzYWF4ZEZa
        cHc1bWtPcW43UXJHMHVyZXZMR0laYWMKLS0tIEpYVEdEeHUvT25VSnNtaXJKV2Ew
        RFJINW83dWNWTFNPcG0ycjN4SFllN0UK/HLwyR07uAXfOGlu+yXF+XZvkavsegpi
        bQ7Z5Kn7VgP+pbdT00N7a1OKkvYIKRoTYq4heRNh7ilGGcQvuj/NVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcUM2UHp4aVdHTnBUQXNQ
        WlRsUFlDeHA2VWJZUjJxZ282VTN5bTR5ZVVFCkVBamE3bzRRalJHakF3OUUyUVcx
        M2hwbnlDM2RhcjRuaEg0djljYWYzOE0KLS0tIEFSYm43MVAwbmZzUjh5RnUrK0FP
        dmoyTWVMcGZWSUdoM3ZldEttNTkwaTgK3YT+3FyOLbUs8A4acNkpv3UTbTVAMskg
        BqbEd6EIpxTFXucto3JQh1yF0NiSrfXOoo/DVKhpzSZzoza4BqpNnw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-02-18T17:13:58Z"
  mac: ENC[AES256_GCM,data:LEjeckglApoRTF2UlhMDuVpSTxreX9QSfRhamuXNCi0yZxnCacgXiBTK4D+8IOhYSm2435pYRf3Y/+zYKqS4PSlZaKIK65IPsEAKuO1PSLU3m2QT9MHBqdW/Pn3wUJPxvzqdVhx7uHQttUJ14hng9pownVqJ2xYV3ak1yJ450EY=,iv:XUgxArNYBD6AZRyvfYSsnvcD8HabceXUlgaD0niQ6KE=,tag:xGGyxCKhwpVut3jcYs93jw==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIARAAi3zoaTSyXKRvnlf42F1Bfl2S5CmyQoLIFz/q0Vjqw1r6
        8QKuGFKKpJyZ+i4f43La1RRsxX72MCh6UJfD8MLcmBmgt7dFVFOU+WqG8YhCHHRV
        A7hXp9zya69oZmWz6wRcdDOZPs5eVcChd/v08fW6HiLGgsDbODrCgp5KpHBrJ+Qa
        7PsVvtSi0oyeK+b3AlynXp+S/lfRMckeOXOG7K+I+IjAjA9+LesO054o1tVi45Vt
        n5p/qM1TDrSuJoLZsAbMpxWuzpjuS4EjaKkqV1NUQBoNPmP+hSnFGN8VRQvQMQyd
        OHxIekhG/7uNloFpsep8WAEb/ofpgo6lTKznRd7hYu2bx7avZ35FZaGS0U7ahnwY
        hA4yv41kc31j26lXz7tN0NAvFLrZT7V3dkICcrW3ZYp5wcqb+qV/ShsC+d3qsKAY
        gz6Av5hi4FadwIyXS7eKAJxrxtoxMHNRMBGnAqZq2bo6Z9VeRdFbLhGwieu2sfOF
        GBJvnm2l9t6B7YTUFQ/H/tQk0vR/bwen/QUsgYLhkHCxY68CRQolJjnqR8eKIxX4
        IbcRLvR0CM2gOLwq+1UBpC/Wcd+uhGZx2u8EbJSU72k/dTiVA+/x0fm8s+bGQBuu
        K0mwf/TSk5svKqKsl5wE/gagORFbIL5EH2J0OMVkiNFKWYzBTNVzZBf6Fi2cuKDS
        XgE2kiljLQj6XMCk20xNSSA2afVVWazcylvaaFvPwBxmYY4aYiu6b4MAD9oajZeS
        Ouwt5OOoFy856NHBRSZ5a2SJTOHJJKbMogQhYIfkG49Cp9Sa6oKtTipDPT511n8=
        =Tkb0
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:50Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAhIhzfKtafPI6m7ec8N1k4XAt9PcAVC9Y0ni4ohfus1Ll
        5kU65UNPMNm6s8D+XiqxMpLvC156/xRqiMBSacqQaRs+fTxomNCi2S8w1APeaeUp
        mRk5hMtIqQBvlO3X16TeO1r18kEn9IkZneo4w5urdvsCyaOJr2DKLh+V7+OrWiWi
        UTzAtNTXjjdrvY6KgJSXZM2jPNYn4McGwC81FMNvP4oLaUNDM9K/E5BwYtI5bJxL
        u8TCOElate1RrrSZT4Av6S0mSAG8Sfdtjs/eXWtpCN5W1yt3/MvRnyJv/4dxbdWp
        +4psL9CwtEIUWQM3mIvmosH8XlwAXVhN6q8lAMgBajPoyYX4q/yBlbLMFpDSwwk/
        M9IKKhYFZKqNUezlQDarl0cXD5KpVoX37evjvO1Q187yiRPaSRJZmxCFCuRfu6rE
        LO1wvgROfLBHv8sTK022rU/ZF3gXenZ58AcwOK3XSF+U3pKAGlEIFTQ1TL2DFXb9
        Zx8TKlmjpU5wSdgz7VtYL9zZuSSgPDV9r5eWJghuJnPC6eqEdJcN4hgjvAptI8b7
        UqHECsFh+5txznYKZYycNoR12AIOO3ZbWZhDCBKfT5feADJdTgGShYvy8Rb0/wfB
        ZzfPEkHFuWe2K/rVnJMX+qEuKsA6T38a1viRZ2cO4AwdS05iaDK4aIalhVCD50/S
        XgFlR6krHpDYYre/Z0zyuxGGUitvZSUXo2kFI+l6Zo+NBeYnxVpx30arSiEHKDz2
        /iojuX6WPn7ndxSxQohct5ufvrtahOQmmvgqD7fxsL0wPzgr54i/6z7UUhBN/zg=
        =BWw6
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.9.2
