apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: kube-system
stringData:
  test: ENC[AES256_GCM,data:DWAo6Q==,iv:YWHfLogn3Ghqgo/4LkGfb4qKVoH4HZJWR4SYUTeWYFs=,tag:k1THD+jOoZLaNBg7ConXsQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-02-17T21:32:39Z"
  mac: ENC[AES256_GCM,data:+n0MhMq+Es7x/16Qt5BQr0S2cSa/ONP16s+4maTnmBQe0B/qBWKAu/KRji8HTZywOqqWUBMYo3mqIQWgUAL/1OuQSUAsX+pgmPnIhPOKXQu1aG6VYK40vI8UM9W5yAZ7Iub5ckLa1bcp9N0muUNz+uN03IzNDS13k8VIFyrpbkU=,iv:tFyDxH5h26FyGUmPkpDmK8liEZucctMgbAO8Zn2fKGI=,tag:DSgr1vYNiWHMNTNVVJd59A==,type:str]
  pgp:
    - created_at: "2025-02-17T21:30:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAwAAAAAAAAAAAQ/+Opp/ggqsB/sayi4MSCXXJCxpbIuLmnWrfDalB0dU2FfB
        gn0VDrhegKLB/bdZchZq+gn7nZLyTKBHxduwTcsWQmsL9Cd4a+VZ8NLhDOXnixXU
        9QqdSs6yWfhz1c9JHgl7PR2NFAS7/rxf4ffBSk4WOcRcENgMqajj6A+8h5SoG3Zq
        BOX38ts38ILJpa4M7Tsj2PcILanZeyF1BGeMJG3AnS5SYSeGQwBfskZd36qihsYk
        o4PN1D/glIWKQIw8YEVe6bKiCuYgKAE7OekptGWYYthYin4Pwij11uIFvrPrOw0C
        U1atcxoV/HJnXC33lp/8x6uUSabtP/GSzMoEklz/PJLs05YoPEMegg4ZnRNZQrjo
        tZc9LE0b9keFM+4OUbZVqYSyxrkNZBciTK4bavLI/6Y6Zj0PmhIAu3S0vfsJxw+O
        32F3YhlA834UNN5GlDsunE+W6ExxTcq5b15vIZXrwsNK5cN/N18UumCK3JEZJLGz
        b+aSoHPmeZ+ofcyELQjSDWh30husR/J15ASzf8dEOUeWtD+XZjjurkw2EFGlIkge
        RF3gRtH38Cr9HoXXHrbB+FAmIpc/ZWyHO4rkbmhk23Wrw/CQPrXhcq1npi6YhWAQ
        syfNriIxj0cU/UsMALvfqBFvhbXwP2iANToRABMAIOgpBdZvqFZ7s5OBypgyikPU
        aAEJAhCCSMUAOfk429SKCe6SvRz5MIU85kJAFCBBRW9bpWf4EusQDcm3Ad/qiPtp
        nrENyF9SN6nuRzfVo8IoMKkinfAG8XbXpyrLiH3hRM854Wnk8hp9gIHDjW/tWFCg
        Rzxu+16VXbqt
        =dK8R
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2025-02-17T21:30:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAwAAAAAAAAAAARAAmNdXz5kaoLL4wScBv+W5viZQ28RHSWQhHC0K9lccsHdU
        J92lQj1wYJ/4HyaZqr5ZVg+oWgrOONIlvaLZ2rrG4/noJ6ubl39Nhisd/iKQCt1f
        Fw0RrI0pMdzaIevV+igwNvxkgt7p2FO2hCk2w7o3E31y3wdHFXAeMK17VyY+PFy/
        uxVKiYVdy8y/J1QhOlf5X9dSefiQp53IslRd9jsH7B90UzzwMKSz54huLBJQ14sM
        DzGNGEac6XO5wgsdsTn0X2oU0P8nnJsPRPh4o8lt441fcTIOUFSRuetMc/pkVYhQ
        9XNWUNKy9Klamxfr9arWNQs53/FgZHCHCWt1Gbs2AbgBFs4R7HZ0hsHKPPm9WKLb
        THMmQqy9ydZmtMk7xr37dqyGa/KbOYaZM0mAOdHUiioKLcDDmKTuMMwiFvKCiUan
        1BIjXixxqa4oLyxDB9ZXRSJOsBjcs1EbijxawKLtTVPLLKDE7199KZ/KyWDjUfEc
        /gpADseHM/QfO7cmJkJVPaCo9JINrZ9PSFnPzlb7SRHV9uKJY3qS/D/mDZ5UHCSx
        MCtcEAozs1IIdMN4r3nFB1+LqTpTMQPIRHzNkfHpmlMF6eVwE7gpv071+DRF64Tk
        JcvnG9oTDZq62IehtAC6svcPOIJaxwkXaSVFSrjCDy+jxdASm2MhEClgAqPmWJLS
        XgFryaY1fQthaAGbYPn8qGepgkTR46aIltX/xBgY/bWsU+wp4aGKhNHQyTRS/jzn
        vSd/RL2QR6Z5dYuT2z++Sy91zNvLH1QoPmtKIOXS/sq0SG3XN3zvApeT7W7yYlA=
        =/7yV
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
