apiVersion: v1
kind: Secret
metadata:
  name: traefik-basic-auth
  namespace: kube-system
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:NKE/BcdsEFD7Hg==,iv:yKiMkRnJJqogDvKID2IQNI7TJJni6kKeXR3Xugmx5A4=,tag:EZK4/G2H7ClFC6SUgDZ0/w==,type:str]
  password: ENC[AES256_GCM,data:IzDTdecRHhXAPrXZ7EeRD6VW1iNG0g==,iv:+jkWv98ySd4Skq2/yiFrh4voknFvJj3j9+7jbwmnMsg=,tag:nwylcAFpTBNlSwRWrO19Zw==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUEdzVzJML0RrM042Vkpi
        VU0wUXdkY3hvV3VacUFmM1dMSXBlYkRoUkZrCjU3aERZWHdQSlRzSVJIMlVGOUJ1
        VVNYZnRnbVdLQjlXanlvcVNua1dYZnMKLS0tIEZRZ2RUVFBnaW15VGtGRDBEUGYv
        M2lwMllkQWY2dGc5amc4U2ZpZVZSUTAKpVKletleyqB8cymqnWubqzsGAq1I4lOY
        0IS+2kZ/zJeC/y5Valw+v6hNwyRW7HmR8p6xu3nix5xeXM8cTDI3nQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U1FKOEE3NkloZ0R4NjhV
        SzZCekdtSlFubWdENHdkTDUvM2owNEZmRVVNCm14Vkh5OWZOVEFLbDRuZEtlTnRR
        MDRZMy9QT0ZsRVpZVGNBNHlDcVI1TDAKLS0tIFUwVkZ3ZGNMZzhNT29Hc25TcEZr
        U00weVR4WWU0U1VjSFVRQ04xQ3ZGNkEK1f6cghSKpX2OWBaLnYyC7fIAgrOJAj86
        TuH9mvIygKjnp+Yf4C6g9UTHzYHh9ozcyPIpM2reYQ2EUpRGNkBVyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T18:52:44Z"
  mac: ENC[AES256_GCM,data:6fKi1UEYd9uje6p41Zsk35TSfOY+B5Rt56C6oW63ExA0K6ksvQryXiVB5pUE8gOBTLTibrNz0mqmYlj4uA43O3zdDCTZFX7EHQDAGLkeAMxS9A0dWD3LvDCGEiKwg95wAgy13m4yfKcI/kjquMNEO7knLvoed6YQrXkZ2gNZDtE=,iv:IJV+JcbsJLn2L5PJeqXhN7JxhT+ZKJuALGVK0HYUcoo=,tag:2R09zA6aSdWXV3PiazBWlw==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:51Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ/7BhaX3q1r5DXYvgZ444JpY/X+K0xTaFCfbis1XVx+zNdn
        zdn75yCYm371gfjPJ7FQ6bXdlqrH2G5onnSHCXKfclGynvSShaXMDCH3O2Y/xTBB
        6maElarHlV0s43ywdXnWrvW6xsyrRtkqVSCKVgGBE0fJvWkA+0O12gVvbB+q5Eav
        Ez4DmCvzKddJsDn3G4e8PA7MoIyz+jTquMt7Jk/un+xR3JAu0N+EjyfaW0O76N1Z
        nPWNY4mS6Zwo9kdkup3TU5pbn1inQmhDQ9hBJMLh+XkrC3MnOWl8+3bDvReaVe59
        uDYQO1N3X02h6FID9f5i7qbNNkKffQQVDw1+ekCpBN+vcbiHjpJJ2iCi8btNgiTQ
        i79h/3zQVKrB2KyfzfKhsFyXavjxKJdHUgkX1QdrQm9PMq5FzWX6tzPCmcRhAvMJ
        jYyxwn1j42pO41k7WxCHev/6c0vLWz48+vyDb+jCho0Vno6RGpndsKl2UvVA6XNi
        R98VbAW9rVLoaO5tmPi8abpVbdRk385o7EvK7aGKrSalK8z9NvynxJV4J8omIOZk
        QCiyGVrlEUZjK9MIgfV5O9cKCFfjYI2bHkJsfzlS/zlbdbvmP+DPkjyZmGfRKte0
        T47a+GFpSkmMZb+OD/FxTu+6M2eeVOCbeMw655z/bNdwTn5UUD8AwQgb4zYt6iPS
        XgHrk10DkwUjSJawemxsrroYw/8MVd/M3Lxe172WRm/yeE2LWx4J+48e+nCxmeC/
        port6pF6JztCynu/hR1PFuxBU+B7DWsT0gXYJIlRS2t8h9qIjV3QacVQRVxfGCc=
        =dh1c
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:51Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ//Y3S9dkXSOPHtnWLC+xEYaqpT/Ir7/e4Muxe7kYhv88HL
        2RoqI4O7B7jjo7p9fuGVG6piQewOpEfqHnbXzFLIFiDNL12SQvqr+E5Gf4TkzKJ+
        /VVVwwSlMj8j6mHzBafKLn/Uzq2UgiMuF6wL7+Lwlt70u4NA/qGlWCMXuC/HllIF
        7Na7zFdUDIEvR4qve/vj2wte69anb57VN90q/3CvSybcgDcABeT8Vu+pZ32SCLD8
        UKw5G6QRNDZAKRX/RJ5S1B0eIhP+0tmpoFrzMAkFROegnRCU5LkNoAHe7C5QxAQP
        /kwY514VLV+y1wnhJtZa4Y9OOZbdqKo+1LXUzlLNA8krFYsHcYVftiFV9UPYPVNg
        q9TZI/srzTV8Pq/vedzzpZfNdz9K8bM/2a9pV8535m8IUxIX9o9e7jtY/XuL9o6x
        N8+dxR0SqDX8Rk5UDUeIcezVI77FBrFT+Hep6x+DyMXsOSDj7/eUqwqpN/aS62aL
        gl0zNc4M+rJ5gOSl1eUhIqjmFvaa42ry3RSKAmyzoE4QBQCEQFqWYOzcUWPYTSRg
        1xzKsU+VNt0PyQokvvgwGBk0Ide7+isleCmhaVnD4FX0pHXbcRuKJ/i83MLlakU+
        eeNVnP2f72dlJ8bZBlm39oBXrMo7UwpyhDsk4TxDs/GqYBapTkj/3UBTxj1iqGfS
        XgF9u5iRrTebkcCu58CySi1ceI0EGWPgOYIZoWMrdKB11rNn3NfsDG2AV774aSys
        XGa927HL4qEg39Wpanhx3URFbX+dsp1XAS8cBm7mrY7yxOoiszvRz94M/VWaMB0=
        =Kxv0
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
