apiVersion: v1
kind: Secret
metadata:
  name: traefik-basic-auth
  namespace: kube-system
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:NKE/BcdsEFD7Hg==,iv:yKiMkRnJJqogDvKID2IQNI7TJJni6kKeXR3Xugmx5A4=,tag:EZK4/G2H7ClFC6SUgDZ0/w==,type:str]
  password: ENC[AES256_GCM,data:IzDTdecRHhXAPrXZ7EeRD6VW1iNG0g==,iv:+jkWv98ySd4Skq2/yiFrh4voknFvJj3j9+7jbwmnMsg=,tag:nwylcAFpTBNlSwRWrO19Zw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU0I2WlVUajEvT0Z3SWVG
        UGIyME9xcEJvaTFiMHBFaDI1T0ZwQlBzeUJnClgyekpGM1g3MUM1MlJ3QXFTK0xO
        S2p3ZFUxK1UzM2JqK3pJMXRFM3ZYZW8KLS0tIFhSL1haSng4OENQbjFoa0ZDdlJB
        OEwzOVFoc1RaQ2ZDTXdrcWQ0TlIxZjAKkVL/Xfr/jKoRqqetoXVxakLk/gT6H2pc
        MT45dvTT8qibqbyylczR90jOefDoj2cb5Wab/EDrR9MgW8FjawXn9g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbWttSTh0SW1kVkVZNmV5
        VmFFWFF3c2JaNDFIQVFucnVhNCtaWWJhbWtnCld4eGtST0pVVnRzdGpNSTRqbkxp
        RlBscG1kcWJqL2VuL2dhNjY4S1dpSTAKLS0tIGdiVEVNNTc2NnQ4UlVGMi9QbU9o
        dlR2REhmTS9jbXdDTEtIUFRGZGJaQ3MKLoissk68RUDf3MTCljrl7TPGiZ65WE/V
        +4XeRN8MEPhAmxhlakyzi6/BmVWkqLP9t+kv4dMmRtTUJiKhRfYdHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-02-02T18:52:44Z"
  mac: ENC[AES256_GCM,data:6fKi1UEYd9uje6p41Zsk35TSfOY+B5Rt56C6oW63ExA0K6ksvQryXiVB5pUE8gOBTLTibrNz0mqmYlj4uA43O3zdDCTZFX7EHQDAGLkeAMxS9A0dWD3LvDCGEiKwg95wAgy13m4yfKcI/kjquMNEO7knLvoed6YQrXkZ2gNZDtE=,iv:IJV+JcbsJLn2L5PJeqXhN7JxhT+ZKJuALGVK0HYUcoo=,tag:2R09zA6aSdWXV3PiazBWlw==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:51Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//ZXZeNIZBtRlYFXRVfN64m4xOuv7OofCtSnRZ0CXlYtyv
        a2Jg0kvnBLVgD7WUOh5uoD0JFmA1KteySKf2jclZYSDs3gtafg64VPj58G1Np6Wb
        JeLkAhHpx5cIkspa5ySOhSGu0ezC6U3S9CfFhTrTc9HeM6cN+OMvpy/hjxT79kWW
        xDT7VvFv8FoDGJc3A4bVG0f8WyxFZL2f8QmbMPfaIAArvRTAnOIwKH1B2gt8ZHr0
        2IODuoNLAzGrJ5hBlihpC6Mvy9mdjPe1w6Lmt8Qwe77VisjRwVImpDm026aEJpFj
        9z9GxGCJ9Omc4o3JFSYlDz4n/8SCBAyeHFSMuSFGK5x03NN8RWvJVMjB6xS64hQI
        3epmxCKuo8vgJ7RqEyagUhwsJkFHreGlW1tTmLt5hGPWdHZayGL2e9YnNH04oB6e
        kKZ9o8YtBLdiOmC9yQwJvj+/aDbS9NfHKlwdVzg6JS7T6TxG/CUrftLmyO8VuCQo
        Yv3vsxHT4cMXH4TI+CMpwbHhpyhWTCuAo6Hux5TF8RhIS25B8MKOD0UP/gZ7rFG5
        MR8Bd7AjGn+DqikJmXa/XL5IP2ibPAmJezYu+36jYXAY1cS/ApEnwcrvz9DDzfiU
        TOpvHe+JNmDgY8GN9hgdCYzOIRPfeZnlTU6hIb+ynakQPUX80FWg7b/bs2CwLufS
        XgFA7jzp9Kgvu8agQrBwWKK+QPjBkrtqkqdMvPinGZSRG/Vcu6hlld9N/3hcwlmJ
        QG2eaLB3yW4C3XmTUgoLA/l9EYqWyoelnxH38bWiK2/pbAv9aYPWXE6VnjGmVmM=
        =AD8p
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:51Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHAQ//SXaqRUycsNZXdGI5FYEgMk1cxp5ALrnuVjqPP63IqYi6
        vJ069ukL1bGIql40CH+IsHggsyoRaLBY96qbeyu+ixTJsvXrdoTNm7NYqeorG365
        COxvjmjULgtu0vSeNjPj6FW9GfhneAyYff7DHrNl8dAoBfplZKq+cKQrsESx43yr
        5hOGu/9sc/I87d4bSgkKMNB1ziW+5RUtk2zbVBinXdtFCHxyzk56Mvak2bESU+Gl
        Thze2/G0t2HWmuHF+lId/UVCTGLm5IJjg6hi+1UPhLCwtJjuypK+dOLkce4zfJFR
        0bkt/vc8Xhki7Q1S6Hf5PEdJBoRCjH8kLaWOg/4ByevLVcjlQuTywBnf7TcRQsCn
        v9JyEPSpo2exzEvhaJB26V8Lkl24kVcHEAsiD6Z+4VLX19TfkM1IbIhdNlVXZP+H
        //vktOEkwR28rIw5sukApWo+AZaZPwpJq5Mr1uiYvrNQ06hpt1pCml6RwD+HDdvC
        2coKy7w59Gq+xTT0SneDg6IGJydUv0yB53H6BcQOXePD1Q3wHDc3At2kq+tm9Zfk
        s/mvYkGtiQisw2j2EDQWDZFD6ReFaLTBIEiEk8sZNFbTMKWcvI8cVLOtFoUwbEy0
        AZKS+3PcnAl/3zuLAT8YGvfIZ2MpBzJsYu0LIhDIsNnDxVzwcqs5lEtnv8VFB1rS
        XgE4wMWLfBN0AF6k1xqEQOEGB99WeoNe85aEzCU25cIDwvQ7ipkyp8I0+GgqkyLM
        F6QwIXwARKK99Rocxbf+lWrWRh5C+WVE3eXeMtyg2w5mH2Oy1dZdojLANUMuzxQ=
        =Q/1C
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.9.2
