apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:qlLII+/P61jjICmcra6ksvb/gorq9SB0q9c+EfbTWV/88FOoYKTpS3isS8BM7c48si68KZ1B8wUFKD5+Qn8CaQ==,iv:kwIn7Tk2l7VGcoxTcrarPjX+h8BA4bpBouXOyYKtjEY=,tag:meFeGF//VbqkNNFhhXmMtQ==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:HyrjfXl1WyiwTTbCYdJTqf41PbP80ngVo3Xs/3Vtk8hQx3DpnPZ3TlSJ/Hm9ZB1c0tcHMZaK0WuZCVbwf2uv+A==,iv:DXK4fJTqbH2zRJa1IeXnYq57vXHxJEOrrouZrhUQN3o=,tag:Ku5YAbP0Uy4mUkywU3u3Zg==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweXk3MmJHYnNJNUNXZ2Iz
        dXAyNG0vT3pQcytXczk1c3RjdDN3c0FMRlZrCnA1ek5LVEVsM0NMM3pQaThKUms0
        Zk1FVUdaa3lUMWVXZXppQlVkYVRMUmsKLS0tIGxwQmJIMXpYS1hUamtvT2FIc2ZD
        Wk40UFUyN0dGbWE2dHc3Yk9yUjR4MEkKBbd1JIDFY5PTHtCS3+NrFsm6aGVj5ykG
        VBkOvnoMS5/TjHMSWIjalbJubgy0goJZy4UT1A/IMwkukgndHJ0GPw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmemtDRFl1aUMzOGttb1Iv
        VGZMK0IyQXNKanovN0g2UWR0RkFQYnQxWUZFCm5GRWFsTTE5alJncTVCOFo1QUtl
        d2xJMFovMy9wSm9DTzBpQWJSbnN5OFUKLS0tIEh1Vk5kbFRnSVNuZm12SU12Y1BZ
        L0M5ZmxndEJvRnQwMGhVSXlkdTJkY0UKCJ5BaL8JGnywGItYXqJP8KTphXXI6eGL
        XMjfWVEYGPUsDiySikRp4NWSVPX/SG9Xp2sXPmBAxKewrWuAUj87Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T21:41:16Z"
  mac: ENC[AES256_GCM,data:42shUBqEz9F03MOSOQy0DtIsAFdPXGFF8YKGp9pfhHO5ipUL/OdR5uUrHPB00ma+u6p9Qt01to8yaG27kNWWc2+wVoqOGMAzMtGfqsUEft5AAf/YsYWzlcrAJbg/Z85guzIM2e0L1bgK3Dp9GrH0ZrrKq+/mgndxxShNJdxOJNU=,iv:qSpw2UZCjEg0uStOPfd77YhwmIJc3xEEukIxPACEvOs=,tag:SyLfzb9WnFOIAP4Mbezz2w==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//Uj/4W/8WhgFaXLCzRMkBd4Dr6IVhCHl1ArC/50y8UElV
        +0LjcRLEZDbG7AMZWWms3giREsf9BG7FRRLp06yEjnkW87WteYxlab8PCBo4x+3x
        d3MML/aHwqsYSMCQpSSa8/5EDPS7kCgqYbQJ/XhMQVKGCJ+KRKf3TTVthj0fWsR1
        rzUIvGpDR8ranwQgpXPsd8kobqeCdwzPI7SrcDqczpL49AaIjKDZOsZyKJm38fvx
        tFFPXX1dy+6vyHVPvfdxV/kAS14hw7ROD4moLZ7SiDdSV0BliAuUkVkxHuakBSyE
        AHyjlmkHkgfK2liGWYOxqhieNdvBl2/7tKo29Aue0QGHRpi7LpdTkjoquQ5YMsA0
        AsV4TpfnjoFSAtF5DyllnhoY8v2m1H7sIlD0CqaGR9WeDQEJMAt2S6o6WwtFgTX7
        m5jo8564q8BlJDlKuAMO8nNwWDfMegBEosVL7DZTjWgucZn1hwh9g807cOojWjHP
        MIJ7PKRvLyQ883MdJ7ueuli08XRVigqqRfWFfN9f9wK0OA0laD4asXjEnwlc5ufS
        D3HzMEjp7LUM88ni+31vKEI4P+1ShrWunJjN0ovTza6n97VDmotCmjEvJ0UdagiZ
        JHrnUy25oCCEYhiL2I2zSyIbtTARKX54Iu+rWaAHPZFoSkoszj3gRhgaYNNa5UnS
        XgHx6zYAB5MhwwmOFdL0BeI80BZPOFUMcbAx5TOUzR8r4uBvxUwuBlHImJp2PVQm
        tl4mDCk3dagOlhaj3qrgI0xBXKa2uvOPDWl4BKA9GzbFHCq3dLJInVke9vnc7+A=
        =wwLs
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAy1kH7si6NcFT2rTiWKskB+mgSlT/1udEq0FiEUNxCwm2
        iRz2QULLrHkIdCgTaBIuaiMhyceRwLBKIkNlQjls/4qq96zmXkGoTfnDUHVB219a
        aV5Qmk8BxkGlbTTTpFRXJpRrAjzEByWOLU/2DB1dloToSlJTEhVvSIEhVw1sgsE+
        QdGI/7M5h3VCNPPGVz7bLLxzdfjexjj9e9yI4fhBDYkkTlvf4SssLU8zo7JmFSXj
        IqBMTcSJUEPSwn8xOcKlqRjb0jjb5NjlQdgYvKOhFlxtQvApNZ5TIPCZ4AvVLdch
        LcnQ29F6iDWZCItDClbhmcfetDvEWuGvKMNt0Ch6569x6e31XzeQDsbKQr0Exv2x
        k8O9TTVHh0FNwMY/Q/tRZA8u4Wj1uqbv/trL566pByf0P52pPIguR9ow9zKuI5Td
        Rk/YJSAa0SeJoaxUagLZQXSgYAQdnYHLPK1qaOSmjUN1RO4OZBp0BXxJ4IDFyRiu
        BiihRnNmnBOPAIhlWvW4mFH8BGpZME/pdYU/7tQab2gaO7Fghz322fQSjUSPtKTu
        h0LngJ2Mh2E9osgTputJNSsMrbISQkes7JJbuw30f2mN7fq1Qq0XX5K8ikExsnal
        rjrcYt32kDUe/IOi8zAYT0sG/kjKwf6r4RYPj+5Apdi/t45R3UrBAOh+7CFmJgvS
        XgFtPlDd1h4wqnyuVd+xg9gv2IAiHakO/aUB196PT1yTZMcTOjC0XZWJrMn/RxNF
        KtErxRzWVFlPyhcUcs0HVztXjR7W0NXCKenRtDzBEXOQDAnzSD1oTfJ2BmYPcFA=
        =SG5h
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: mariadb-operator
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:qlLII+/P61jjICmcra6ksvb/gorq9SB0q9c+EfbTWV/88FOoYKTpS3isS8BM7c48si68KZ1B8wUFKD5+Qn8CaQ==,iv:kwIn7Tk2l7VGcoxTcrarPjX+h8BA4bpBouXOyYKtjEY=,tag:meFeGF//VbqkNNFhhXmMtQ==,type:str]
sops:
  age:
    - recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweXk3MmJHYnNJNUNXZ2Iz
        dXAyNG0vT3pQcytXczk1c3RjdDN3c0FMRlZrCnA1ek5LVEVsM0NMM3pQaThKUms0
        Zk1FVUdaa3lUMWVXZXppQlVkYVRMUmsKLS0tIGxwQmJIMXpYS1hUamtvT2FIc2ZD
        Wk40UFUyN0dGbWE2dHc3Yk9yUjR4MEkKBbd1JIDFY5PTHtCS3+NrFsm6aGVj5ykG
        VBkOvnoMS5/TjHMSWIjalbJubgy0goJZy4UT1A/IMwkukgndHJ0GPw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rukdr63zmsh22l8hfwdc402agdt4cv6u2pk0z4pxjcdu2lrh05vqphmllc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmemtDRFl1aUMzOGttb1Iv
        VGZMK0IyQXNKanovN0g2UWR0RkFQYnQxWUZFCm5GRWFsTTE5alJncTVCOFo1QUtl
        d2xJMFovMy9wSm9DTzBpQWJSbnN5OFUKLS0tIEh1Vk5kbFRnSVNuZm12SU12Y1BZ
        L0M5ZmxndEJvRnQwMGhVSXlkdTJkY0UKCJ5BaL8JGnywGItYXqJP8KTphXXI6eGL
        XMjfWVEYGPUsDiySikRp4NWSVPX/SG9Xp2sXPmBAxKewrWuAUj87Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T21:41:16Z"
  mac: ENC[AES256_GCM,data:42shUBqEz9F03MOSOQy0DtIsAFdPXGFF8YKGp9pfhHO5ipUL/OdR5uUrHPB00ma+u6p9Qt01to8yaG27kNWWc2+wVoqOGMAzMtGfqsUEft5AAf/YsYWzlcrAJbg/Z85guzIM2e0L1bgK3Dp9GrH0ZrrKq+/mgndxxShNJdxOJNU=,iv:qSpw2UZCjEg0uStOPfd77YhwmIJc3xEEukIxPACEvOs=,tag:SyLfzb9WnFOIAP4Mbezz2w==,type:str]
  pgp:
    - created_at: "2026-07-15T18:30:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIAQ//Uj/4W/8WhgFaXLCzRMkBd4Dr6IVhCHl1ArC/50y8UElV
        +0LjcRLEZDbG7AMZWWms3giREsf9BG7FRRLp06yEjnkW87WteYxlab8PCBo4x+3x
        d3MML/aHwqsYSMCQpSSa8/5EDPS7kCgqYbQJ/XhMQVKGCJ+KRKf3TTVthj0fWsR1
        rzUIvGpDR8ranwQgpXPsd8kobqeCdwzPI7SrcDqczpL49AaIjKDZOsZyKJm38fvx
        tFFPXX1dy+6vyHVPvfdxV/kAS14hw7ROD4moLZ7SiDdSV0BliAuUkVkxHuakBSyE
        AHyjlmkHkgfK2liGWYOxqhieNdvBl2/7tKo29Aue0QGHRpi7LpdTkjoquQ5YMsA0
        AsV4TpfnjoFSAtF5DyllnhoY8v2m1H7sIlD0CqaGR9WeDQEJMAt2S6o6WwtFgTX7
        m5jo8564q8BlJDlKuAMO8nNwWDfMegBEosVL7DZTjWgucZn1hwh9g807cOojWjHP
        MIJ7PKRvLyQ883MdJ7ueuli08XRVigqqRfWFfN9f9wK0OA0laD4asXjEnwlc5ufS
        D3HzMEjp7LUM88ni+31vKEI4P+1ShrWunJjN0ovTza6n97VDmotCmjEvJ0UdagiZ
        JHrnUy25oCCEYhiL2I2zSyIbtTARKX54Iu+rWaAHPZFoSkoszj3gRhgaYNNa5UnS
        XgHx6zYAB5MhwwmOFdL0BeI80BZPOFUMcbAx5TOUzR8r4uBvxUwuBlHImJp2PVQm
        tl4mDCk3dagOlhaj3qrgI0xBXKa2uvOPDWl4BKA9GzbFHCq3dLJInVke9vnc7+A=
        =wwLs
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-15T18:30:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAy1kH7si6NcFT2rTiWKskB+mgSlT/1udEq0FiEUNxCwm2
        iRz2QULLrHkIdCgTaBIuaiMhyceRwLBKIkNlQjls/4qq96zmXkGoTfnDUHVB219a
        aV5Qmk8BxkGlbTTTpFRXJpRrAjzEByWOLU/2DB1dloToSlJTEhVvSIEhVw1sgsE+
        QdGI/7M5h3VCNPPGVz7bLLxzdfjexjj9e9yI4fhBDYkkTlvf4SssLU8zo7JmFSXj
        IqBMTcSJUEPSwn8xOcKlqRjb0jjb5NjlQdgYvKOhFlxtQvApNZ5TIPCZ4AvVLdch
        LcnQ29F6iDWZCItDClbhmcfetDvEWuGvKMNt0Ch6569x6e31XzeQDsbKQr0Exv2x
        k8O9TTVHh0FNwMY/Q/tRZA8u4Wj1uqbv/trL566pByf0P52pPIguR9ow9zKuI5Td
        Rk/YJSAa0SeJoaxUagLZQXSgYAQdnYHLPK1qaOSmjUN1RO4OZBp0BXxJ4IDFyRiu
        BiihRnNmnBOPAIhlWvW4mFH8BGpZME/pdYU/7tQab2gaO7Fghz322fQSjUSPtKTu
        h0LngJ2Mh2E9osgTputJNSsMrbISQkes7JJbuw30f2mN7fq1Qq0XX5K8ikExsnal
        rjrcYt32kDUe/IOi8zAYT0sG/kjKwf6r4RYPj+5Apdi/t45R3UrBAOh+7CFmJgvS
        XgFtPlDd1h4wqnyuVd+xg9gv2IAiHakO/aUB196PT1yTZMcTOjC0XZWJrMn/RxNF
        KtErxRzWVFlPyhcUcs0HVztXjR7W0NXCKenRtDzBEXOQDAnzSD1oTfJ2BmYPcFA=
        =SG5h
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
