apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:qlLII+/P61jjICmcra6ksvb/gorq9SB0q9c+EfbTWV/88FOoYKTpS3isS8BM7c48si68KZ1B8wUFKD5+Qn8CaQ==,iv:kwIn7Tk2l7VGcoxTcrarPjX+h8BA4bpBouXOyYKtjEY=,tag:meFeGF//VbqkNNFhhXmMtQ==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:HyrjfXl1WyiwTTbCYdJTqf41PbP80ngVo3Xs/3Vtk8hQx3DpnPZ3TlSJ/Hm9ZB1c0tcHMZaK0WuZCVbwf2uv+A==,iv:DXK4fJTqbH2zRJa1IeXnYq57vXHxJEOrrouZrhUQN3o=,tag:Ku5YAbP0Uy4mUkywU3u3Zg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTFdCYms2d0tQdlNWMGht
        a3BDNE82RWl0Sk5IaEYxZjNMakx2b3BNZUVnCnNNMThXOC9yWER5YSs4aVVLM0x4
        WDMzcUtTNEZTS0dYQjRxWG5WUXZnSG8KLS0tIDFYRDdBbjVIV056RGo3TFlkWnJh
        UzJ2d1FSNlhsMmU1SnNQVTNUbld2ejgKhWaJAb1IRkYk86/9WsDfsoOpyiLkcXnx
        OYfYzMzkFbb289Thr49W/1cvbzFuX+VCzc+tvJ2Jc3+k4wW8GGN+gQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NEhyS2o3UWNIbCtUUGEx
        NG1sNW1YdG0xS282dG1HWGxFUGhMUmQ2NGpzClgxNGZoVEMvOGJLVGNBZ3Vvd0hC
        Q2hXQkIyeFZFbklOQWNVYXBrTXU3Y0UKLS0tIERLUFRHUjFRYlhzSFp6czZ5a0xI
        aWtLcEh3S3FGWXZDQVNKbW9QaDN6TXMK0RUxkdFHhWgZ9elFW7lF4L4ZsjQCk8NF
        /Qg5G2zsNnjBfo78ChiS/JwHCNBV63OXhaE7lOnCLa5EMLX0q3nRBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-03-05T21:41:16Z"
  mac: ENC[AES256_GCM,data:42shUBqEz9F03MOSOQy0DtIsAFdPXGFF8YKGp9pfhHO5ipUL/OdR5uUrHPB00ma+u6p9Qt01to8yaG27kNWWc2+wVoqOGMAzMtGfqsUEft5AAf/YsYWzlcrAJbg/Z85guzIM2e0L1bgK3Dp9GrH0ZrrKq+/mgndxxShNJdxOJNU=,iv:qSpw2UZCjEg0uStOPfd77YhwmIJc3xEEukIxPACEvOs=,tag:SyLfzb9WnFOIAP4Mbezz2w==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIARAApOUItSjk9UwzSJFnWUyCFfBk3nLymBxjXUVqmdg4ZK1G
        s/OyEj1q1Sfva6d3AWS+CnwbngXAByTmcDwiUtDBelcCzDttyaYAqxtm0oeGoKps
        upJ6XRzJHZMUAt3etzJtegawvcOU1CrKERy6Dldos/O3wF/9RyZsx6Z+iArT2wGP
        skZFYqCnqs7OkK6c6R8h6tjs3BOUMUFbXDo1lcrKgs5WqBgO3GE8S2N+zgpOKMeF
        mcYVgt7HghT6w7DJF3FbOT3rcjaH0gZGJS1EjNfmmMhUQ88a8PYQ7uCSGBePQHZK
        eA5YCH7pq6JTnPaYkxrT0KwwNqPPjAO2OmtKdDlgUw/MVuoAA0jUV0tTgeJqRr32
        B7ZGYsO+V09WtIZJXmDi6f38BbbFaFTCAhNSo8gUpeC5Fme1JB5YFE1d7czIWQAu
        W5FH11FeVs18Y5QREtejVMasfL7sZGtbQJFK4U/CX1dU3TGKSSWsCm21c6BxK0IQ
        rM2+O88fLosDB6hlBfUzCIP87hzcrwgpsMDdPqDuwgxK5gUTiuXGtVYgadJAkfsy
        WAg3rtOn9xOrN/Aa9taGv8LW/lwTXPw1AbaqmkLdc8B/o9KL87nMIERNEKc+8ePV
        bK7jsxBcFea3D8nDc/BO1101IZDIw9csYUtuI5CYxPHe+h+9mMsbk1naIIIB9xrS
        XgGnf/8/Pq7DI5E/nHDVOqEoZbnFPaiCXdbCGIvwDQPr/HAHAtWGm+pHXTX+u3BV
        GgKXg58FDUq7esu/xfIRLrmpjuywCI0hR3efMnoMfMhnGNtXa647omZ4JuzMVn8=
        =eIsu
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAyzIN8Vd0k/W5bSK/NkoeQLUm7Hf9smCaG9Uy+ft/XiW8
        KYXZ86mp0XsSg8lZTRabQmm2VolWomX8pzUrFouLsivrwW4qEeanWL3UJtZwiQbN
        w+HrYnASHUH861JpaoNUDK6HlpxOvKcuXFaaQixtOqsCD74o7cu+mAjhfDyZMpMA
        25SQ+mrFhdQK0Q/zXjxnaGeRYnZcwxmKpDgivJJltXohk1wWWp5l5VMLnwKy7+2X
        DQGhhc6A8NR7c+o9ByHMp+w4DULDtDKGKfAT8sIlSeZrWWKgk+PQTw1J/yu97WFH
        FM105DJ79ViHBIcU/Vx+C/dz9sr66T7VcPEoJSkprGkJu3x0dWAtYTsTlaYHXB3C
        H6K6Wo8mMnc9CvPqjqLKkuEDK46rSz3qji63fgnQy19jb0Aj36YU2rVQQxFGUV+F
        WAx7W0n1ZWc7dJxiONZAsmQvA/yfCX18m6gx46M41V88PgXMWnoGn2Op4/LnbkBU
        VxlIDPOOykw13AZT/nymovpbfkws2ZC3BqbGzA2Aqr/vWHC4sCk3CTjNp6oQcRwQ
        xPK6bzjPOkYXTIJbDXJQy8BYRLEIKALTaDprmZ/SY8cGTZ82nfcfI0TGpLM8CJsE
        eKNoV0BZxpUlyE0wFrCkb75iNOVQBIsF/5VYwDexmuhd2Ve41Qj/PAhl3FzM23nS
        XgHz96tca7z6gQJ2DpkxCXTpAPHsxAkIMC/z83PuLoofjZ2ON7ilEDpapwjQIGIB
        3ozx6ni2h8dbMYTwZ1IBbpDj7V3V0yp8hu903t5TeUL/i31F2IyctJgzzI60SZ0=
        =6FVQ
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: mariadb-operator
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:qlLII+/P61jjICmcra6ksvb/gorq9SB0q9c+EfbTWV/88FOoYKTpS3isS8BM7c48si68KZ1B8wUFKD5+Qn8CaQ==,iv:kwIn7Tk2l7VGcoxTcrarPjX+h8BA4bpBouXOyYKtjEY=,tag:meFeGF//VbqkNNFhhXmMtQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTFdCYms2d0tQdlNWMGht
        a3BDNE82RWl0Sk5IaEYxZjNMakx2b3BNZUVnCnNNMThXOC9yWER5YSs4aVVLM0x4
        WDMzcUtTNEZTS0dYQjRxWG5WUXZnSG8KLS0tIDFYRDdBbjVIV056RGo3TFlkWnJh
        UzJ2d1FSNlhsMmU1SnNQVTNUbld2ejgKhWaJAb1IRkYk86/9WsDfsoOpyiLkcXnx
        OYfYzMzkFbb289Thr49W/1cvbzFuX+VCzc+tvJ2Jc3+k4wW8GGN+gQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zn5g4ltncuya0csq2vse043vlll55nkxumcyzt6x38h0a0d4ysgscj4e4t
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NEhyS2o3UWNIbCtUUGEx
        NG1sNW1YdG0xS282dG1HWGxFUGhMUmQ2NGpzClgxNGZoVEMvOGJLVGNBZ3Vvd0hC
        Q2hXQkIyeFZFbklOQWNVYXBrTXU3Y0UKLS0tIERLUFRHUjFRYlhzSFp6czZ5a0xI
        aWtLcEh3S3FGWXZDQVNKbW9QaDN6TXMK0RUxkdFHhWgZ9elFW7lF4L4ZsjQCk8NF
        /Qg5G2zsNnjBfo78ChiS/JwHCNBV63OXhaE7lOnCLa5EMLX0q3nRBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dee7myl6p5435rxx76j7csqfky2hgx84xrymdx6l8xctjs22nd7qe8k7sf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-03-05T21:41:16Z"
  mac: ENC[AES256_GCM,data:42shUBqEz9F03MOSOQy0DtIsAFdPXGFF8YKGp9pfhHO5ipUL/OdR5uUrHPB00ma+u6p9Qt01to8yaG27kNWWc2+wVoqOGMAzMtGfqsUEft5AAf/YsYWzlcrAJbg/Z85guzIM2e0L1bgK3Dp9GrH0ZrrKq+/mgndxxShNJdxOJNU=,iv:qSpw2UZCjEg0uStOPfd77YhwmIJc3xEEukIxPACEvOs=,tag:SyLfzb9WnFOIAP4Mbezz2w==,type:str]
  pgp:
    - created_at: "2026-07-09T21:05:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA669/IaxfGcIARAApOUItSjk9UwzSJFnWUyCFfBk3nLymBxjXUVqmdg4ZK1G
        s/OyEj1q1Sfva6d3AWS+CnwbngXAByTmcDwiUtDBelcCzDttyaYAqxtm0oeGoKps
        upJ6XRzJHZMUAt3etzJtegawvcOU1CrKERy6Dldos/O3wF/9RyZsx6Z+iArT2wGP
        skZFYqCnqs7OkK6c6R8h6tjs3BOUMUFbXDo1lcrKgs5WqBgO3GE8S2N+zgpOKMeF
        mcYVgt7HghT6w7DJF3FbOT3rcjaH0gZGJS1EjNfmmMhUQ88a8PYQ7uCSGBePQHZK
        eA5YCH7pq6JTnPaYkxrT0KwwNqPPjAO2OmtKdDlgUw/MVuoAA0jUV0tTgeJqRr32
        B7ZGYsO+V09WtIZJXmDi6f38BbbFaFTCAhNSo8gUpeC5Fme1JB5YFE1d7czIWQAu
        W5FH11FeVs18Y5QREtejVMasfL7sZGtbQJFK4U/CX1dU3TGKSSWsCm21c6BxK0IQ
        rM2+O88fLosDB6hlBfUzCIP87hzcrwgpsMDdPqDuwgxK5gUTiuXGtVYgadJAkfsy
        WAg3rtOn9xOrN/Aa9taGv8LW/lwTXPw1AbaqmkLdc8B/o9KL87nMIERNEKc+8ePV
        bK7jsxBcFea3D8nDc/BO1101IZDIw9csYUtuI5CYxPHe+h+9mMsbk1naIIIB9xrS
        XgGnf/8/Pq7DI5E/nHDVOqEoZbnFPaiCXdbCGIvwDQPr/HAHAtWGm+pHXTX+u3BV
        GgKXg58FDUq7esu/xfIRLrmpjuywCI0hR3efMnoMfMhnGNtXa647omZ4JuzMVn8=
        =eIsu
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
    - created_at: "2026-07-09T21:05:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2JDmTLJk6NHARAAyzIN8Vd0k/W5bSK/NkoeQLUm7Hf9smCaG9Uy+ft/XiW8
        KYXZ86mp0XsSg8lZTRabQmm2VolWomX8pzUrFouLsivrwW4qEeanWL3UJtZwiQbN
        w+HrYnASHUH861JpaoNUDK6HlpxOvKcuXFaaQixtOqsCD74o7cu+mAjhfDyZMpMA
        25SQ+mrFhdQK0Q/zXjxnaGeRYnZcwxmKpDgivJJltXohk1wWWp5l5VMLnwKy7+2X
        DQGhhc6A8NR7c+o9ByHMp+w4DULDtDKGKfAT8sIlSeZrWWKgk+PQTw1J/yu97WFH
        FM105DJ79ViHBIcU/Vx+C/dz9sr66T7VcPEoJSkprGkJu3x0dWAtYTsTlaYHXB3C
        H6K6Wo8mMnc9CvPqjqLKkuEDK46rSz3qji63fgnQy19jb0Aj36YU2rVQQxFGUV+F
        WAx7W0n1ZWc7dJxiONZAsmQvA/yfCX18m6gx46M41V88PgXMWnoGn2Op4/LnbkBU
        VxlIDPOOykw13AZT/nymovpbfkws2ZC3BqbGzA2Aqr/vWHC4sCk3CTjNp6oQcRwQ
        xPK6bzjPOkYXTIJbDXJQy8BYRLEIKALTaDprmZ/SY8cGTZ82nfcfI0TGpLM8CJsE
        eKNoV0BZxpUlyE0wFrCkb75iNOVQBIsF/5VYwDexmuhd2Ve41Qj/PAhl3FzM23nS
        XgHz96tca7z6gQJ2DpkxCXTpAPHsxAkIMC/z83PuLoofjZ2ON7ilEDpapwjQIGIB
        3ozx6ni2h8dbMYTwZ1IBbpDj7V3V0yp8hu903t5TeUL/i31F2IyctJgzzI60SZ0=
        =6FVQ
        -----END PGP MESSAGE-----
      fp: 75B5F14CB9CF5A951C935E86203E3E4D22C1B89B
  version: 3.10.2
